In [141]:
import pdfplumber
import pandas as pd

In [142]:
pdf = pdfplumber.open("danicapension.pdf")

In [143]:
tabs = []



for page in pdf.pages:
    tabs.append(page.extract_tables(table_settings={"vertical_strategy": "text", "horizontal_strategy": "text", "text_keep_blank_chars": False}))


tabs

[[[['DANICA PENSIO', 'N, Specifikation af kapitalandele', '', ''],
   ['', '', '', ''],
   ['', '', 'MARKEDSVÆRDI', ''],
   ['', '', '', ''],
   ['MIO. KR.', '', '31-12-2024 andel %', ''],
   ['', '', '', ''],
   ['BØRSNOTEREDE', 'KAPITALANDELE', '', ''],
   ['', '', '', ''],
   ['Apple Inc.', '', '7.407', '3,9%'],
   ['', '', '', ''],
   ['Microsoft Corp.', '', '6.941', '3,7%'],
   ['', '', '', ''],
   ['Nvidia Corp. (US)', '', '6.773', '3,6%'],
   ['', '', '', ''],
   ['Amazon.com', '', '5.526', '2,9%'],
   ['', '', '', ''],
   ['Novo Nordisk B', '', '4.311', '2,3%'],
   ['', '', '', ''],
   ['Alphabet Inc C', '', '3.438', '1,8%'],
   ['', '', '', ''],
   ['Meta Platforms A', '(US)', '3.053', '1,6%'],
   ['', '', '', ''],
   ['Broadcom Inc', '', '2.707', '1,4%'],
   ['', '', '', ''],
   ['Mastercard Inc-C', 'lass A', '2.258', '1,2%'],
   ['', '', '', ''],
   ['Alphabet Inc A', '', '1.955', '1,0%'],
   ['', '', '', ''],
   ['Tesla Inc (US)', '', '1.754', '0,9%'],
   ['', '', '', ''],
   ['Coca Cola Co (US', ')', '1.644', '0,9%'],
   ['', '', '', ''],
   ['Oracle Corp.', '', '1.640', '0,9%'],
   ['', '', '', ''],
   ['Boston Scientific', 'Corp.', '1.617', '0,9%'],
   ['', '', '', ''],
   ['DSV A/S', '', '1.537', '0,8%'],
   ['', '', '', ''],
   ['Abbott Laborator', 'ies (US)', '1.418', '0,8%'],
   ['', '', '', ''],
   ['Fiserv Inc.', '', '1.356', '0,7%'],
   ['', '', '', ''],
   ['Bank of America', 'Corp.', '1.330', '0,7%'],
   ['', '', '', ''],
   ['AstraZeneca Ord', '(GBP)', '1.309', '0,7%'],
   ['', '', '', ''],
   ['ASML Holding NV', '', '1.261', '0,7%'],
   ['', '', '', ''],
   ['Taiwan Semicond', 'uctor Manufacturing Co.', '1.218', '0,6%'],
   ['', '', '', ''],
   ['UnitedHealth Gro', 'up Inc.', '1.155', '0,6%'],
   ['', '', '', ''],
   ['Eaton Corporatio', 'n Plc (USD)', '1.102', '0,6%'],
   ['', '', '', ''],
   ['NextEra Energy In', 'c.', '1.068', '0,6%'],
   ['', '', '', ''],
   ['Elevance Health I', 'nc', '1.061', '0,6%'],
   ['', '', '', ''],
   ['Taiwan Semicond', 'uctor Manufactoring Co. (', '1.060', '0,6%'],
   ['', '', '', ''],
   ['JPMorgan Chase', '& Co.', '1.059', '0,6%'],
   ['', '', '', ''],
   ['Salesforce Inc', '', '1.012', '0,5%'],
   ['', '', '', ''],
   ['Walmart Inc', '', '992', '0,5%'],
   ['', '', '', ''],
   ['NetFlix Inc', '', '963', '0,5%'],
   ['', '', '', ''],
   ['Prudential Plc Or', 'd', '940', '0,5%'],
   ['', '', '', ''],
   ['Thermo Fisher Sc', 'ientific Inc', '927', '0,5%'],
   ['', '', '', ''],
   ['Danske Bank', '', '910', '0,5%'],
   ['', '', '', ''],
   ['Tencent Holdings', 'Ltd.', '902', '0,5%'],
   ['', '', '', ''],
   ['Eli Lilly & Co.', '', '891', '0,5%'],
   ['', '', '', ''],
   ['Crowdstrike Hold', 'ings Inc. A', '874', '0,5%'],
   ['', '', '', ''],
   ['argenx SE ADR', '', '869', '0,5%']]],
 [[['Novonesis (Novo', 'zymes) B', '867', '0,5%'],
   ['', '', '', ''],
   ['BP Plc', '', '842', '0,4%'],
   ['', '', '', ''],
   ['Berkshire Hatha', 'way Inc. B', '835', '0,4%'],
   ['', '', '', ''],
   ['AIA Group Ltd', '', '832', '0,4%'],
   ['', '', '', ''],
   ['Samsonite Intern', 'ational SA (HKD)', '818', '0,4%'],
   ['', '', '', ''],
   ['Accor SA', '', '810', '0,4%'],
   ['', '', '', ''],
   ['Advanced Micro', 'Devices Inc.', '799', '0,4%'],
   ['', '', '', ''],
   ['Prosus N.V.', '', '790', '0,4%'],
   ['', '', '', ''],
   ['TransUnion', '', '780', '0,4%'],
   ['', '', '', ''],
   ['Home Depot Inc.', '', '774', '0,4%'],
   ['', '', '', ''],
   ['GE AEROSPACE', '(US)', '770', '0,4%'],
   ['', '', '', ''],
   ['Visa Inc Class A', '', '751', '0,4%'],
   ['', '', '', ''],
   ['adidas AG Reg.', '', '743', '0,4%'],
   ['', '', '', ''],
   ['London Stock Ex', 'change Group Plc', '709', '0,4%'],
   ['', '', '', ''],
   ['Coloplast B', '', '677', '0,4%'],
   ['', '', '', ''],
   ['Uber Technologi', 'es Inc', '677', '0,4%'],
   ['', '', '', ''],
   ['Siemens AG (Re', 'gd)', '666', '0,4%'],
   ['', '', '', ''],
   ['Teledyne Techno', 'logies Inc.', '611', '0,3%'],
   ['', '', '', ''],
   ['SAP SE (Ord)', '', '603', '0,3%'],
   ['', '', '', ''],
   ['Pandora', '', '600', '0,3%'],
   ['', '', '', ''],
   ['Costco Wholesa', 'le Corp.', '591', '0,3%'],
   ['', '', '', ''],
   ['Keysight Techno', 'logies Inc', '585', '0,3%'],
   ['', '', '', ''],
   ['Lonza Group (Re', 'gd)', '580', '0,3%'],
   ['', '', '', ''],
   ['Heineken', '', '579', '0,3%'],
   ['', '', '', ''],
   ['West Pharmace', 'uticals Services', '574', '0,3%'],
   ['', '', '', ''],
   ['Micron Technolo', 'gy', '570', '0,3%'],
   ['', '', '', ''],
   ['Zscaler Inc', '', '563', '0,3%'],
   ['', '', '', ''],
   ['Procter & Gambl', 'e Co.', '556', '0,3%'],
   ['', '', '', ''],
   ['Keyence Corp.', '', '537', '0,3%'],
   ['', '', '', ''],
   ['Puma SE', '', '535', '0,3%'],
   ['', '', '', ''],
   ['Estee Lauder Co.', 'A', '522', '0,3%'],
   ['', '', '', ''],
   ['Johnson & Johns', 'on', '517', '0,3%'],
   ['', '', '', ''],
   ['Blue Owl Capital', 'Inc A', '510', '0,3%'],
   ['', '', '', ''],
   ['BNP Paribas S.A', '.', '510', '0,3%'],
   ['', '', '', ''],
   ['Adobe Inc. (US)', '', '509', '0,3%'],
   ['', '', '', ''],
   ['Sea A Ltd ADR', '', '506', '0,3%'],
   ['', '', '', ''],
   ['U.S. Bancorp', '', '496', '0,3%'],
   ['', '', '', ''],
   ['Netcompany Gro', 'up A/S', '492', '0,3%'],
   ['', '', '', ''],
   ['ServiceNow Inc.', '', '490', '0,3%'],
   ['', '', '', ''],
   ['Techtronic Indus', 'tries Co. Ltd.', '485', '0,3%'],
   ['', '', '', ''],
   ['Trimble Inc', '', '484', '0,3%'],
   ['', '', '', ''],
   ['AutoZone Inc.', '', '476', '0,3%'],
   ['', '', '', ''],
   ['Parker-Hannifin', 'Corp.', '467', '0,2%'],
   ['', '', '', ''],
   ['Shopify Inc A (US', ')', '463', '0,2%'],
   ['', '', '', ''],
   ['Linde PLC (US)', '', '462', '0,2%'],
   ['', '', '', ''],
   ['Tryg A/S', '', '458', '0,2%'],
   ['', '', '', ''],
   ['Tokyo Electron', '', '456', '0,2%']]],
 [[['AbbVie Inc', '', '', '444', '0,2%'],
   ['', '', '', '', ''],
   ['HDFC Bank Ltd', '', '', '439', '0,2%'],
   ['', '', '', '', ''],
   ['Coca Cola HBC Na', 'men', 'Akt. (GBP)', '436', '0,2%'],
   ['', '', '', '', ''],
   ['Arista Networks I', 'nc (U', 'S)', '429', '0,2%'],
   ['', '', '', '', ''],
   ['Erste Group Bank', 'AG (', 'AT) (EUR)', '428', '0,2%'],
   ['', '', '', '', ''],
   ['Centene Corp', '', '', '420', '0,2%'],
   ['', '', '', '', ''],
   ['Hiscox Ltd', '', '', '418', '0,2%'],
   ['', '', '', '', ''],
   ['Chevron Corp.', '', '', '410', '0,2%'],
   ['', '', '', '', ''],
   ['Danaher Corp. (US', ')', '', '405', '0,2%'],
   ['', '', '', '', ''],
   ['Ally Financial Inc', '', '', '397', '0,2%'],
   ['', '', '', '', ''],
   ['S&P Global Inc', '', '', '394', '0,2%'],
   ['', '', '', '', ''],
   ['Merck & Co. Inc. (', 'US)', '', '393', '0,2%'],
   ['', '', '', '', ''],
   ['Toyota Motor Cor', 'p.', '', '392', '0,2%'],
   ['', '', '', '', ''],
   ['Ctrip.com Internat', 'iona', 'l Ltd ADR', '387', '0,2%'],
   ['', '', '', '', ''],
   ['Quanta Services In', 'c.', '', '381', '0,2%'],
   ['', '', '', '', ''],
   ['Alibaba Group Hol', 'ding', 'Ltd', '361', '0,2%'],
   ['', '', '', '', ''],
   ['Colgate-Palmolive', 'Co.', '', '360', '0,2%'],
   ['', '', '', '', ''],
   ['Vestas Wind Syst', 'ems', 'A/S', '349', '0,2%'],
   ['', '', '', '', ''],
   ['PepsiCo Inc.', '', '', '349', '0,2%'],
   ['', '', '', '', ''],
   ['Cisco Systems Inc', '.', '', '346', '0,2%'],
   ['', '', '', '', ''],
   ['Ørsted A/S', '', '', '339', '0,2%'],
   ['', '', '', '', ''],
   ['Atlassian Corpora', 'tion', 'PLC A', '339', '0,2%'],
   ['', '', '', '', ''],
   ['ICICI Bank (ADR)', '', '', '338', '0,2%'],
   ['', '', '', '', ''],
   ['Genmab A/S', '', '', '337', '0,2%'],
   ['', '', '', '', ''],
   ['Ascendis Pharma', 'A/S', '(ADR)', '336', '0,2%'],
   ['', '', '', '', ''],
   ['Wells Fargo Co. (U', 'S)', '', '336', '0,2%'],
   ['', '', '', '', ''],
   ['Workday Inc', '', '', '333', '0,2%'],
   ['', '', '', '', ''],
   ['A.P. Moller - Mars', 'k B', '', '323', '0,2%'],
   ['', '', '', '', ''],
   ['Ferrovial SE (ES)', '', '', '316', '0,2%'],
   ['', '', '', '', ''],
   ['Goldman Sachs G', 'roup', 'Inc.', '315', '0,2%'],
   ['', '', '', '', ''],
   ['Infineon Technolog', 'ies', 'AG', '313', '0,2%'],
   ['', '', '', '', ''],
   ['Accenture Plc A (', 'USD)', '', '311', '0,2%'],
   ['', '', '', '', ''],
   ['Carlsberg B', '', '', '311', '0,2%'],
   ['', '', '', '', ''],
   ['Samsung Electron', 'ics (', 'Pref.)', '307', '0,2%'],
   ['', '', '', '', ''],
   ['McDonalds Corp.', '', '', '305', '0,2%'],
   ['', '', '', '', ''],
   ['Norfolk Southern', 'Corp', '', '300', '0,2%'],
   ['', '', '', '', ''],
   ['ING Groep NV', '', '', '300', '0,2%'],
   ['', '', '', '', ''],
   ['IBM', '', '', '299', '0,2%'],
   ['', '', '', '', ''],
   ['Citigroup Inc. (US)', '', '', '295', '0,2%'],
   ['', '', '', '', ''],
   ['Live Nation Entert', 'ainm', 'ent Inc.', '294', '0,2%'],
   ['', '', '', '', ''],
   ['Meituan B', '', '', '293', '0,2%'],
   ['', '', '', '', ''],
   ['PNC Financial Ser', 'vice', 's Group Inc.', '290', '0,2%'],
   ['', '', '', '', ''],
   ['Walt Disney (USD', ')', '', '288', '0,2%'],
   ['', '', '', '', ''],
   ['DBS Group Holdin', 'g', '', '285', '0,2%'],
   ['', '', '', '', ''],
   ['Intuit Inc.', '', '', '281', '0,1%'],
   ['', '', '', '', ''],
   ['RTX Corporation (', 'US)', '', '280', '0,1%'],
   ['', '', '', '', ''],
   ['Xylem Inc', '', '', '278', '0,1%']]],
 [[['Siemens Energy', 'AG', '', '275', '0,1%'],
   ['', '', '', '', ''],
   ['SK Hynix Inc.', '', '', '270', '0,1%'],
   ['', '', '', '', ''],
   ['SAAB AB B', '', '', '266', '0,1%'],
   ['', '', '', '', ''],
   ['Sony Group Corp', '', '', '262', '0,1%'],
   ['', '', '', '', ''],
   ['Union Pacific Cor', 'p.', '', '260', '0,1%'],
   ['', '', '', '', ''],
   ['Intuitive Surgical', 'Inc.', '', '260', '0,1%'],
   ['', '', '', '', ''],
   ['Vertex Pharmace', 'uticals', 'Inc. (USD)', '256', '0,1%'],
   ['', '', '', '', ''],
   ['Mitsubishi UFJ Fi', 'nancial', 'Group', '250', '0,1%'],
   ['', '', '', '', ''],
   ['MediaTek Inc.', '', '', '249', '0,1%'],
   ['', '', '', '', ''],
   ['Verizon Commun', 'ication', 's Inc. (US)', '248', '0,1%'],
   ['', '', '', '', ''],
   ['Texas Instrument', 's (USD', ')', '244', '0,1%'],
   ['', '', '', '', ''],
   ['QUALCOMM Inc.', '(US)', '', '242', '0,1%'],
   ['', '', '', '', ''],
   ['Caterpillar Inc.', '', '', '242', '0,1%'],
   ['', '', '', '', ''],
   ['Ecolab Inc.', '', '', '241', '0,1%'],
   ['', '', '', '', ''],
   ['American Expres', 's', '', '240', '0,1%'],
   ['', '', '', '', ''],
   ['AT&T Inc.', '', '', '238', '0,1%'],
   ['', '', '', '', ''],
   ['Tetragon Financi', 'al Group', 'Ltd (NL)', '237', '0,1%'],
   ['', '', '', '', ''],
   ['Vinci SA', '', '', '236', '0,1%'],
   ['', '', '', '', ''],
   ['Royal Bank of Ca', 'nada', '', '236', '0,1%'],
   ['', '', '', '', ''],
   ['MARVELL TECH', 'NOLOG', 'Y INC (US)', '233', '0,1%'],
   ['', '', '', '', ''],
   ['Progressive Corp', '', '', '233', '0,1%'],
   ['', '', '', '', ''],
   ['Booking Holdings', 'Inc', '', '231', '0,1%'],
   ['', '', '', '', ''],
   ['Schneider Electri', 'c', '', '230', '0,1%'],
   ['', '', '', '', ''],
   ['Adyen B.V.', '', '', '227', '0,1%'],
   ['', '', '', '', ''],
   ['Demant A/S', '', '', '226', '0,1%'],
   ['', '', '', '', ''],
   ['Ringkjobing Land', 'bobank', 'A/S', '225', '0,1%'],
   ['', '', '', '', ''],
   ['Pfizer Inc. (US)', '', '', '225', '0,1%'],
   ['', '', '', '', ''],
   ['Indian Hotels Co.', 'Ltd', '', '224', '0,1%'],
   ['', '', '', '', ''],
   ['Lowes Co.', '', '', '222', '0,1%'],
   ['', '', '', '', ''],
   ['Hitachi', '', '', '222', '0,1%'],
   ['', '', '', '', ''],
   ['Amadeus IT Grou', 'p S.A', '', '220', '0,1%'],
   ['', '', '', '', ''],
   ['Morgan Stanley', '', '', '220', '0,1%'],
   ['', '', '', '', ''],
   ['BlackRock Inc', '', '', '218', '0,1%'],
   ['', '', '', '', ''],
   ['Sanofi (FR)', '', '', '217', '0,1%'],
   ['', '', '', '', ''],
   ['Commonwealth B', 'ank of', 'Australia', '215', '0,1%'],
   ['', '', '', '', ''],
   ['TotalEnergies SE', '(FR)', '', '215', '0,1%'],
   ['', '', '', '', ''],
   ['Comcast Corp. A', '', '', '212', '0,1%'],
   ['', '', '', '', ''],
   ['Palantir Technolo', 'gies Inc', '', '212', '0,1%'],
   ['', '', '', '', ''],
   ['Hoya Corp.', '', '', '209', '0,1%'],
   ['', '', '', '', ''],
   ['INVISIO AB', '', '', '207', '0,1%'],
   ['', '', '', '', ''],
   ['Applied Materials', 'Inc.', '', '206', '0,1%'],
   ['', '', '', '', ''],
   ['Honeywell Intern', 'ational I', 'nc.', '201', '0,1%'],
   ['', '', '', '', ''],
   ['Amgen Inc.', '', '', '200', '0,1%'],
   ['', '', '', '', ''],
   ['GE VERNOVA LL', 'C (US)', '', '198', '0,1%'],
   ['', '', '', '', ''],
   ['Palo Alto Networ', 'ks Inc', '', '195', '0,1%'],
   ['', '', '', '', ''],
   ['MetLife Inc.', '', '', '194', '0,1%'],
   ['', '', '', '', ''],
   ['TJX Co. Inc.', '', '', '192', '0,1%']]],
 [[['Recruit Holdings', 'Co.Ltd.', '191', '0,1%'],
   ['', '', '', ''],
   ['CBRE Group Inc', '', '191', '0,1%'],
   ['', '', '', ''],
   ['State Bank of Ind', 'ia', '189', '0,1%'],
   ['', '', '', ''],
   ['Nike Inc B', '', '188', '0,1%'],
   ['', '', '', ''],
   ['KLA Corporation', '', '188', '0,1%'],
   ['', '', '', ''],
   ['Tyler Technologie', 's Inc', '185', '0,1%'],
   ['', '', '', ''],
   ['Unilever Plc Ord', '', '184', '0,1%'],
   ['', '', '', ''],
   ['Automatic Data', 'Processing Inc', '183', '0,1%'],
   ['', '', '', ''],
   ['ChemoMetec', '', '183', '0,1%'],
   ['', '', '', ''],
   ['Stryker Corp.', '', '180', '0,1%'],
   ['', '', '', ''],
   ['RELX PLC', '', '179', '0,1%'],
   ['', '', '', ''],
   ['T-Mobile US Inc', '', '178', '0,1%'],
   ['', '', '', ''],
   ['PayPal Holdings I', 'nc (US)', '178', '0,1%'],
   ['', '', '', ''],
   ['BHP GROUP Ltd', '', '177', '0,1%'],
   ['', '', '', ''],
   ['Equinor ASA', '', '176', '0,1%'],
   ['', '', '', ''],
   ['Blackstone Inc', '', '175', '0,1%'],
   ['', '', '', ''],
   ['SEMPRA', '', '175', '0,1%'],
   ['', '', '', ''],
   ['Dassault System', 'es SA', '174', '0,1%'],
   ['', '', '', ''],
   ['Shopify Inc A', '', '173', '0,1%'],
   ['', '', '', ''],
   ['Bristol-Myers Sq', 'uibb Co. (US)', '173', '0,1%'],
   ['', '', '', ''],
   ['Elis SA', '', '172', '0,1%'],
   ['', '', '', ''],
   ['Softbank Group C', 'orp (JP)', '170', '0,1%'],
   ['', '', '', ''],
   ['Sumitomo Mitsui', 'Financial Group Inc.', '170', '0,1%'],
   ['', '', '', ''],
   ['Charles Schwab', 'Corp.', '169', '0,1%'],
   ['', '', '', ''],
   ['DANONE SA', '', '168', '0,1%'],
   ['', '', '', ''],
   ['ON Semiconduct', 'or Corp.', '165', '0,1%'],
   ['', '', '', ''],
   ['Consolidated Edi', 'son Inc.', '165', '0,1%'],
   ['', '', '', ''],
   ['Hong Kong Excha', 'nges & Clearing Ltd.', '165', '0,1%'],
   ['', '', '', ''],
   ['Nordea Bank Abp', '(DK) DKK', '164', '0,1%'],
   ['', '', '', ''],
   ['Chroma Ate Inc.', '', '164', '0,1%'],
   ['', '', '', ''],
   ['Marsh & McLenn', 'an Co. Inc.', '163', '0,1%'],
   ['', '', '', ''],
   ['Chubb Ltd (USD)', '', '163', '0,1%'],
   ['', '', '', ''],
   ['Gilead Sciences I', 'nc.', '160', '0,1%'],
   ['', '', '', ''],
   ['Amber Enterpris', 'es India Ltd', '159', '0,1%'],
   ['', '', '', ''],
   ['Per Aarsleff Hold', 'ing A/S', '158', '0,1%'],
   ['', '', '', ''],
   ['LVMH Moet Hen', 'nessy Louis Vuitton SE (FR)', '158', '0,1%'],
   ['', '', '', ''],
   ['APAR INDUSTRI', 'ES LTD (IN)', '158', '0,1%'],
   ['', '', '', ''],
   ['Truist Financial C', 'orporation', '158', '0,1%'],
   ['', '', '', ''],
   ['3M COMPANY L', 'TD', '156', '0,1%'],
   ['', '', '', ''],
   ['Williams Co. Inc.', '', '156', '0,1%'],
   ['', '', '', ''],
   ['Hexagon AB B', '', '156', '0,1%'],
   ['', '', '', ''],
   ['Deere & Co.', '', '156', '0,1%'],
   ['', '', '', ''],
   ['Medtronic PLC', '', '155', '0,1%'],
   ['', '', '', ''],
   ['Analog Devices I', 'nc', '155', '0,1%'],
   ['', '', '', ''],
   ['Equinix Inc (US)', '', '154', '0,1%'],
   ['', '', '', ''],
   ['ENEL SpA', '', '153', '0,1%'],
   ['', '', '', ''],
   ['Deutsche Börse', 'AG', '150', '0,1%']]],
 [[['Sunny Optical Tech', 'nology', '(Group) Co Ltd', '149', '0,1%'],
   ['', '', '', '', ''],
   ['Starbucks Corp', '', '', '148', '0,1%'],
   ['', '', '', '', ''],
   ['ProLogis Inc.', '', '', '146', '0,1%'],
   ['', '', '', '', ''],
   ['Kinder Morgan Inc', '', '', '146', '0,1%'],
   ['', '', '', '', ''],
   ['Welltower OP Inc', '', '', '143', '0,1%'],
   ['', '', '', '', ''],
   ['CRH PLC (US)', '', '', '143', '0,1%'],
   ['', '', '', '', ''],
   ['EOG Resources Inc', '.', '', '143', '0,1%'],
   ['', '', '', '', ''],
   ['Edison Internationa', 'l', '', '142', '0,1%'],
   ['', '', '', '', ''],
   ['PT Bank Central As', 'ia Tbk', '', '140', '0,1%'],
   ['', '', '', '', ''],
   ['AFLAC Inc.', '', '', '140', '0,1%'],
   ['', '', '', '', ''],
   ['Carrier Global Corp', 'oratio', 'n', '140', '0,1%'],
   ['', '', '', '', ''],
   ['Petershill Partners', 'PLC', '', '139', '0,1%'],
   ['', '', '', '', ''],
   ['Sage Group Plc Ord', '', '', '138', '0,1%'],
   ['', '', '', '', ''],
   ['Phoenix Mills Ltd./T', 'he', '', '138', '0,1%'],
   ['', '', '', '', ''],
   ['ONEOK Inc.', '', '', '135', '0,1%'],
   ['', '', '', '', ''],
   ['ISS', '', '', '134', '0,1%'],
   ['', '', '', '', ''],
   ['United Parcel Servi', 'ce Inc.', 'B U.P.S.', '134', '0,1%'],
   ['', '', '', '', ''],
   ['Tokio Marine Holdi', 'ngs Inc', '.', '133', '0,1%'],
   ['', '', '', '', ''],
   ['CME Group Inc', '', '', '132', '0,1%'],
   ['', '', '', '', ''],
   ['Sherwin-Williams', 'Co.', '', '132', '0,1%'],
   ['', '', '', '', ''],
   ['Lam Research Cor', 'p', '', '130', '0,1%'],
   ['', '', '', '', ''],
   ['Royal Unibrew', '', '', '130', '0,1%'],
   ['', '', '', '', ''],
   ['Fast Retailing', '', '', '129', '0,1%'],
   ['', '', '', '', ''],
   ['GN Store Nord', '', '', '129', '0,1%'],
   ['', '', '', '', ''],
   ['Waste Manageme', 'nt Inc.', '', '129', '0,1%'],
   ['', '', '', '', ''],
   ['Deutsche Post AG', '', '', '129', '0,1%'],
   ['', '', '', '', ''],
   ['American Tower C', 'orp', '', '129', '0,1%'],
   ['', '', '', '', ''],
   ['Toronto-Dominion', 'Bank (C', 'A)', '129', '0,1%'],
   ['', '', '', '', ''],
   ['Volvo B', '', '', '128', '0,1%'],
   ['', '', '', '', ''],
   ['KKR & Co Inc', 'A', '', '128', '0,1%'],
   ['', '', '', '', ''],
   ['Public Service Ente', 'rprise', 'Group', '127', '0,1%'],
   ['', '', '', '', ''],
   ['Intercontinental Ex', 'change', 'Inc', '125', '0,1%'],
   ['', '', '', '', ''],
   ['American Internati', 'onal Gr', 'oup Inc.', '125', '0,1%'],
   ['', '', '', '', ''],
   ['Mondelez Internati', 'onal In', 'c', '123', '0,1%'],
   ['', '', '', '', ''],
   ['Intel Corp.', '', '', '122', '0,1%'],
   ['', '', '', '', ''],
   ['Exelon Corp.', '', '', '122', '0,1%'],
   ['', '', '', '', ''],
   ['Motorola Solutions', 'Inc', '', '122', '0,1%'],
   ['', '', '', '', ''],
   ['Liberty Media Corp', 'C Libe', 'rty Formula One', '121', '0,1%'],
   ['', '', '', '', ''],
   ['Spotify Technology', 'SA (U', 'SD)', '120', '0,1%'],
   ['', '', '', '', ''],
   ['Newmont Corporat', 'ion', '', '120', '0,1%'],
   ['', '', '', '', ''],
   ['Illinois Tool Works', 'Inc.', '', '119', '0,1%'],
   ['', '', '', '', ''],
   ['MAKEMYTRIP LTD', '(US)', '', '118', '0,1%'],
   ['', '', '', '', ''],
   ['Nintendo', '', '', '118', '0,1%'],
   ['', '', '', '', ''],
   ['Chipotle Mexican G', 'rill Inc.', 'Class A', '118', '0,1%'],
   ['', '', '', '', ''],
   ['Melrose Industries', 'PLC', '', '117', '0,1%'],
   ['', '', '', '', ''],
   ['Hubbell Inc', '', '', '117', '0,1%'],
   ['', '', '', '', ''],
   ['Shin-Etsu Chemica', 'l Co', '', '117', '0,1%']]],
 [[['PG&E Corp.', '', '', '116', '0,1%'],
   ['', '', '', '', ''],
   ['Games Workshop', 'Group', '', '116', '0,1%'],
   ['', '', '', '', ''],
   ['Kering', '', '', '115', '0,1%'],
   ['', '', '', '', ''],
   ['Moodys Corp.', '', '', '115', '0,1%'],
   ['', '', '', '', ''],
   ['Amphenol Corp. A', '', '', '114', '0,1%'],
   ['', '', '', '', ''],
   ['Zealand Pharma', 'A/S', '', '114', '0,1%'],
   ['', '', '', '', ''],

In [144]:
biglist=sum(tabs, [])

In [145]:
biggerlist=sum(biglist, [])

In [146]:
biggestlist=[]

for i in range(len(biggerlist)):
    if biggerlist[i]!= ['', '', '', '']:
        if biggerlist[i]!=['', '', '', '', '']:
            biggestlist.append(biggerlist[i])

biggestlist

[['DANICA PENSIO', 'N, Specifikation af kapitalandele', '', ''],
 ['', '', 'MARKEDSVÆRDI', ''],
 ['MIO. KR.', '', '31-12-2024 andel %', ''],
 ['BØRSNOTEREDE', 'KAPITALANDELE', '', ''],
 ['Apple Inc.', '', '7.407', '3,9%'],
 ['Microsoft Corp.', '', '6.941', '3,7%'],
 ['Nvidia Corp. (US)', '', '6.773', '3,6%'],
 ['Amazon.com', '', '5.526', '2,9%'],
 ['Novo Nordisk B', '', '4.311', '2,3%'],
 ['Alphabet Inc C', '', '3.438', '1,8%'],
 ['Meta Platforms A', '(US)', '3.053', '1,6%'],
 ['Broadcom Inc', '', '2.707', '1,4%'],
 ['Mastercard Inc-C', 'lass A', '2.258', '1,2%'],
 ['Alphabet Inc A', '', '1.955', '1,0%'],
 ['Tesla Inc (US)', '', '1.754', '0,9%'],
 ['Coca Cola Co (US', ')', '1.644', '0,9%'],
 ['Oracle Corp.', '', '1.640', '0,9%'],
 ['Boston Scientific', 'Corp.', '1.617', '0,9%'],
 ['DSV A/S', '', '1.537', '0,8%'],
 ['Abbott Laborator', 'ies (US)', '1.418', '0,8%'],
 ['Fiserv Inc.', '', '1.356', '0,7%'],
 ['Bank of America', 'Corp.', '1.330', '0,7%'],
 ['AstraZeneca Ord', '(GBP)', '1.309', '0,7%'],
 ['ASML Holding NV', '', '1.261', '0,7%'],
 ['Taiwan Semicond', 'uctor Manufacturing Co.', '1.218', '0,6%'],
 ['UnitedHealth Gro', 'up Inc.', '1.155', '0,6%'],
 ['Eaton Corporatio', 'n Plc (USD)', '1.102', '0,6%'],
 ['NextEra Energy In', 'c.', '1.068', '0,6%'],
 ['Elevance Health I', 'nc', '1.061', '0,6%'],
 ['Taiwan Semicond', 'uctor Manufactoring Co. (', '1.060', '0,6%'],
 ['JPMorgan Chase', '& Co.', '1.059', '0,6%'],
 ['Salesforce Inc', '', '1.012', '0,5%'],
 ['Walmart Inc', '', '992', '0,5%'],
 ['NetFlix Inc', '', '963', '0,5%'],
 ['Prudential Plc Or', 'd', '940', '0,5%'],
 ['Thermo Fisher Sc', 'ientific Inc', '927', '0,5%'],
 ['Danske Bank', '', '910', '0,5%'],
 ['Tencent Holdings', 'Ltd.', '902', '0,5%'],
 ['Eli Lilly & Co.', '', '891', '0,5%'],
 ['Crowdstrike Hold', 'ings Inc. A', '874', '0,5%'],
 ['argenx SE ADR', '', '869', '0,5%'],
 ['Novonesis (Novo', 'zymes) B', '867', '0,5%'],
 ['BP Plc', '', '842', '0,4%'],
 ['Berkshire Hatha', 'way Inc. B', '835', '0,4%'],
 ['AIA Group Ltd', '', '832', '0,4%'],
 ['Samsonite Intern', 'ational SA (HKD)', '818', '0,4%'],
 ['Accor SA', '', '810', '0,4%'],
 ['Advanced Micro', 'Devices Inc.', '799', '0,4%'],
 ['Prosus N.V.', '', '790', '0,4%'],
 ['TransUnion', '', '780', '0,4%'],
 ['Home Depot Inc.', '', '774', '0,4%'],
 ['GE AEROSPACE', '(US)', '770', '0,4%'],
 ['Visa Inc Class A', '', '751', '0,4%'],
 ['adidas AG Reg.', '', '743', '0,4%'],
 ['London Stock Ex', 'change Group Plc', '709', '0,4%'],
 ['Coloplast B', '', '677', '0,4%'],
 ['Uber Technologi', 'es Inc', '677', '0,4%'],
 ['Siemens AG (Re', 'gd)', '666', '0,4%'],
 ['Teledyne Techno', 'logies Inc.', '611', '0,3%'],
 ['SAP SE (Ord)', '', '603', '0,3%'],
 ['Pandora', '', '600', '0,3%'],
 ['Costco Wholesa', 'le Corp.', '591', '0,3%'],
 ['Keysight Techno', 'logies Inc', '585', '0,3%'],
 ['Lonza Group (Re', 'gd)', '580', '0,3%'],
 ['Heineken', '', '579', '0,3%'],
 ['West Pharmace', 'uticals Services', '574', '0,3%'],
 ['Micron Technolo', 'gy', '570', '0,3%'],
 ['Zscaler Inc', '', '563', '0,3%'],
 ['Procter & Gambl', 'e Co.', '556', '0,3%'],
 ['Keyence Corp.', '', '537', '0,3%'],
 ['Puma SE', '', '535', '0,3%'],
 ['Estee Lauder Co.', 'A', '522', '0,3%'],
 ['Johnson & Johns', 'on', '517', '0,3%'],
 ['Blue Owl Capital', 'Inc A', '510', '0,3%'],
 ['BNP Paribas S.A', '.', '510', '0,3%'],
 ['Adobe Inc. (US)', '', '509', '0,3%'],
 ['Sea A Ltd ADR', '', '506', '0,3%'],
 ['U.S. Bancorp', '', '496', '0,3%'],
 ['Netcompany Gro', 'up A/S', '492', '0,3%'],
 ['ServiceNow Inc.', '', '490', '0,3%'],
 ['Techtronic Indus', 'tries Co. Ltd.', '485', '0,3%'],
 ['Trimble Inc', '', '484', '0,3%'],
 ['AutoZone Inc.', '', '476', '0,3%'],
 ['Parker-Hannifin', 'Corp.', '467', '0,2%'],
 ['Shopify Inc A (US', ')', '463', '0,2%'],
 ['Linde PLC (US)', '', '462', '0,2%'],
 ['Tryg A/S', '', '458', '0,2%'],
 ['Tokyo Electron', '', '456', '0,2%'],
 ['AbbVie Inc', '', '', '444', '0,2%'],
 ['HDFC Bank Ltd', '', '', '439', '0,2%'],
 ['Coca Cola HBC Na', 'men', 'Akt. (GBP)', '436', '0,2%'],
 ['Arista Networks I', 'nc (U', 'S)', '429', '0,2%'],
 ['Erste Group Bank', 'AG (', 'AT) (EUR)', '428', '0,2%'],
 ['Centene Corp', '', '', '420', '0,2%'],
 ['Hiscox Ltd', '', '', '418', '0,2%'],
 ['Chevron Corp.', '', '', '410', '0,2%'],
 ['Danaher Corp. (US', ')', '', '405', '0,2%'],
 ['Ally Financial Inc', '', '', '397', '0,2%'],
 ['S&P Global Inc', '', '', '394', '0,2%'],
 ['Merck & Co. Inc. (', 'US)', '', '393', '0,2%'],
 ['Toyota Motor Cor', 'p.', '', '392', '0,2%'],
 ['Ctrip.com Internat', 'iona', 'l Ltd ADR', '387', '0,2%'],
 ['Quanta Services In', 'c.', '', '381', '0,2%'],
 ['Alibaba Group Hol', 'ding', 'Ltd', '361', '0,2%'],
 ['Colgate-Palmolive', 'Co.', '', '360', '0,2%'],
 ['Vestas Wind Syst', 'ems', 'A/S', '349', '0,2%'],
 ['PepsiCo Inc.', '', '', '349', '0,2%'],
 ['Cisco Systems Inc', '.', '', '346', '0,2%'],
 ['Ørsted A/S', '', '', '339', '0,2%'],
 ['Atlassian Corpora', 'tion', 'PLC A', '339', '0,2%'],
 ['ICICI Bank (ADR)', '', '', '338', '0,2%'],
 ['Genmab A/S', '', '', '337', '0,2%'],
 ['Ascendis Pharma', 'A/S', '(ADR)', '336', '0,2%'],
 ['Wells Fargo Co. (U', 'S)', '', '336', '0,2%'],
 ['Workday Inc', '', '', '333', '0,2%'],
 ['A.P. Moller - Mars', 'k B', '', '323', '0,2%'],
 ['Ferrovial SE (ES)', '', '', '316', '0,2%'],
 ['Goldman Sachs G', 'roup', 'Inc.', '315', '0,2%'],
 ['Infineon Technolog', 'ies', 'AG', '313', '0,2%'],
 ['Accenture Plc A (', 'USD)', '', '311', '0,2%'],
 ['Carlsberg B', '', '', '311', '0,2%'],
 ['Samsung Electron', 'ics (', 'Pref.)', '307', '0,2%'],
 ['McDonalds Corp.', '', '', '305', '0,2%'],
 ['Norfolk Southern', 'Corp', '', '300', '0,2%'],
 ['ING Groep NV', '', '', '300', '0,2%'],
 ['IBM', '', '', '299', '0,2%'],
 ['Citigroup Inc. (US)', '', '', '295', '0,2%'],
 ['Live Nation Entert', 'ainm', 'ent Inc.', '294', '0,2%'],
 ['Meituan B', '', '', '293', '0,2%'],
 ['PNC Financial Ser', 'vice', 's Group Inc.', '290', '0,2%'],
 ['Walt Disney (USD', ')', '', '288', '0,2%'],
 ['DBS Group Holdin', 'g', '', '285', '0,2%'],
 ['Intuit Inc.', '', '', '281', '0,1%'],
 ['RTX Corporation (', 'US)', '', '280', '0,1%'],
 ['Xylem Inc', '', '', '278', '0,1%'],
 ['Siemens Energy', 'AG', '', '275', '0,1%'],
 ['SK Hynix Inc.', '', '', '270', '0,1%'],
 ['SAAB AB B', '', '', '266', '0,1%'],
 ['Sony Group Corp', '', '', '262', '0,1%'],
 ['Union Pacific Cor', 'p.', '', '260', '0,1%'],
 ['Intuitive Surgical', 'Inc.', '', '260', '0,1%'],
 ['Vertex Pharmace', 'uticals', 'Inc. (USD)', '256', '0,1%'],
 ['Mitsubishi UFJ Fi', 'nancial', 'Group', '250', '0,1%'],
 ['MediaTek Inc.', '', '', '249', '0,1%'],
 ['Verizon Commun', 'ication', 's Inc. (US)', '248', '0,1%'],
 ['Texas Instrument', 's (USD', ')', '244', '0,1%'],
 ['QUALCOMM Inc.', '(US)', '', '242', '0,1%'],
 ['Caterpillar Inc.', '', '', '242', '0,1%'],
 ['Ecolab Inc.', '', '', '241', '0,1%'],
 ['American Expres', 's', '', '240', '0,1%'],
 ['AT&T Inc.', '', '', '238', '0,1%'],
 ['Tetragon Financi', 'al Group', 'Ltd (NL)', '237', '0,1%'],
 ['Vinci SA', '', '', '236', '0,1%'],
 ['Royal Bank of Ca', 'nada', '', '236', '0,1%'],
 ['MARVELL TECH', 'NOLOG', 'Y INC (US)', '233', '0,1%'],
 ['Progressive Corp', '', '', '233', '0,1%'],
 ['Booking Holdings', 'Inc', '', '231', '0,1%'],
 ['Schneider Electri', 'c', '', '230', '0,1%'],
 ['Adyen B.V.', '', '', '227', '0,1%'],
 ['Demant A/S', '', '', '226', '0,1%'],
 ['Ringkjobing Land', 'bobank', 'A/S', '225', '0,1%'],
 ['Pfizer Inc. (US)', '', '', '225', '0,1%'],
 ['Indian Hotels Co.', 'Ltd', '', '224', '0,1%'],
 ['Lowes Co.', '', '', '222', '0,1%'],
 ['Hitachi', '', '', '222', '0,1%'],
 ['Amadeus IT Grou', 'p S.A', '', '220', '0,1%'],
 ['Morgan Stanley', '', '', '220', '0,1%'],
 ['BlackRock Inc', '', '', '218', '0,1%'],
 ['Sanofi (FR)', '', '', '217', '0,1%'],
 ['Commonwealth B', 'ank of', 'Australia', '215', '0,1%'],
 ['TotalEnergies SE', '(FR)', '', '215', '0,1%'],
 ['Comcast Corp. A', '', '', '212', '0,1%'],
 ['Palantir Technolo', 'gies Inc', '', '212', '0,1%'],
 ['Hoya Corp.', '', '', '209', '0,1%'],
 ['INVISIO AB', '', '', '207', '0,1%'],
 ['Applied Materials', 'Inc.', '', '206', '0,1%'],
 ['Honeywell Intern', 'ational I', 'nc.', '201', '0,1%'],
 ['Amgen Inc.', '', '', '200', '0,1%'],
 ['GE VERNOVA LL', 'C (US)', '', '198', '0,1%'],
 ['Palo Alto Networ', 'ks Inc', '', '195', '0,1%'],
 ['MetLife Inc.', '', '', '194', '0,1%'],
 ['TJX Co. Inc.', '', '', '192', '0,1%'],
 ['Recruit Holdings', 'Co.Ltd.', '191', '0,1%'],
 ['CBRE Group Inc', '', '191', '0,1%'],
 ['State Bank of Ind', 'ia', '189', '0,1%'],
 ['Nike Inc B', '', '188', '0,1%'],
 ['KLA Corporation', '', '188', '0,1%'],
 ['Tyler Technologie', 's Inc', '185', '0,1%'],
 ['Unilever Plc Ord', '', '184', '0,1%'],
 ['Automatic Data', 'Processing Inc', '183', '0,1%'],
 ['ChemoMetec', '', '183', '0,1%'],
 ['Stryker Corp.', '', '180', '0,1%'],
 ['RELX PLC', '', '179', '0,1%'],
 ['T-Mobile US Inc', '', '178', '0,1%'],
 ['PayPal Holdings I', 'nc (US)', '178', '0,1%'],
 ['BHP GROUP Ltd', '', '177', '0,1%'],
 ['Equinor ASA', '', '176', '0,1%'],
 ['Blackstone Inc', '', '175', '0,1%'],
 ['SEMPRA', '', '175', '0,1%'],
 ['Dassault System', 'es SA', '174', '0,1%'],
 ['Shopify Inc A', '', '173', '0,1%'],
 ['Bristol-Myers Sq', 'uibb Co. (US)', '173', '0,1%'],
 ['Elis SA', '', '172', '0,1%'],
 ['Softbank Group C', 'orp (JP)', '170', '0,1%'],
 ['Sumitomo Mitsui', 'Financial Group Inc.', '170', '0,1%'],
 ['Charles Schwab', 'Corp.', '169', '0,1%'],
 ['DANONE SA', '', '168', '0,1%'],
 ['ON Semiconduct', 'or Corp.', '165', '0,1%'],
 ['Consolidated Edi', 'son Inc.', '165', '0,1%'],
 ['Hong Kong Excha', 'nges & Clearing Ltd.', '165', '0,1%'],
 ['Nordea Bank Abp', '(DK) DKK', '164', '0,1%'],
 ['Chroma Ate Inc.', '', '164', '0,1%'],
 ['Marsh & McLenn', 'an Co. Inc.', '163', '0,1%'],
 ['Chubb Ltd (USD)', '', '163', '0,1%'],
 ['Gilead Sciences I', 'nc.', '160', '0,1%'],
 ['Amber Enterpris', 'es India Ltd', '159', '0,1%'],
 ['Per Aarsleff Hold', 'ing A/S', '158', '0,1%'],
 ['LVMH Moet Hen', 'nessy Louis Vuitton SE (FR)', '158', '0,1%'],
 ['APAR INDUSTRI', 'ES LTD (IN)', '158', '0,1%'],
 ['Truist Financial C', 'orporation', '158', '0,1%'],
 ['3M COMPANY L', 'TD', '156', '0,1%'],
 ['Williams Co. Inc.', '', '156', '0,1%'],
 ['Hexagon AB B', '', '156', '0,1%'],
 ['Deere & Co.', '', '156', '0,1%'],
 ['Medtronic PLC', '', '155', '0,1%'],
 ['Analog Devices I', 'nc', '155', '0,1%'],
 ['Equinix Inc (US)', '', '154', '0,1%'],
 ['ENEL SpA', '', '153', '0,1%'],
 ['Deutsche Börse', 'AG', '150', '0,1%'],
 ['Sunny Optical Tech', 'nology', '(Group) Co Ltd', '149', '0,1%'],
 ['Starbucks Corp', '', '', '148', '0,1%'],
 ['ProLogis Inc.', '', '', '146', '0,1%'],
 ['Kinder Morgan Inc', '', '', '146', '0,1%'],
 ['Welltower OP Inc', '', '', '143', '0,1%'],
 ['CRH PLC (US)', '', '', '143', '0,1%'],
 ['EOG Resources Inc', '.', '', '143', '0,1%'],
 ['Edison Internationa', 'l', '', '142', '0,1%'],
 ['PT Bank Central As', 'ia Tbk', '', '140', '0,1%'],
 ['AFLAC Inc.', '', '', '140', '0,1%'],
 ['Carrier Global Corp', 'oratio', 'n', '140', '0,1%'],
 ['Petershill Partners', 'PLC', '', '139', '0,1%'],
 ['Sage Group Plc Ord', '', '', '138', '0,1%'],
 ['Phoenix Mills Ltd./T', 'he', '', '138', '0,1%'],
 ['ONEOK Inc.', '', '', '135', '0,1%'],
 ['ISS', '', '', '134', '0,1%'],
 ['United Parcel Servi', 'ce Inc.', 'B U.P.S.', '134', '0,1%'],
 ['Tokio Marine Holdi', 'ngs Inc', '.', '133', '0,1%'],
 ['CME Group Inc', '', '', '132', '0,1%'],
 ['Sherwin-Williams', 'Co.', '', '132', '0,1%'],
 ['Lam Research Cor', 'p', '', '130', '0,1%'],
 ['Royal Unibrew', '', '', '130', '0,1%'],
 ['Fast Retailing', '', '', '129', '0,1%'],
 ['GN Store Nord', '', '', '129', '0,1%'],
 ['Waste Manageme', 'nt Inc.', '', '129', '0,1%'],
 ['Deutsche Post AG', '', '', '129', '0,1%'],
 ['American Tower C', 'orp', '', '129', '0,1%'],
 ['Toronto-Dominion', 'Bank (C', 'A)', '129', '0,1%'],
 ['Volvo B', '', '', '128', '0,1%'],
 ['KKR & Co Inc', 'A', '', '128', '0,1%'],
 ['Public Service Ente', 'rprise', 'Group', '127', '0,1%'],
 ['Intercontinental Ex', 'change', 'Inc', '125', '0,1%'],
 ['American Internati', 'onal Gr', 'oup Inc.', '125', '0,1%'],
 ['Mondelez Internati', 'onal In', 'c', '123', '0,1%'],
 ['Intel Corp.', '', '', '122', '0,1%'],
 ['Exelon Corp.', '', '', '122', '0,1%'],
 ['Motorola Solutions', 'Inc', '', '122', '0,1%'],
 ['Liberty Media Corp', 'C Libe', 'rty Formula One', '121', '0,1%'],
 ['Spotify Technology', 'SA (U', 'SD)', '120', '0,1%'],
 ['Newmont Corporat', 'ion', '', '120', '0,1%'],
 ['Illinois Tool Works', 'Inc.', '', '119', '0,1%'],
 ['MAKEMYTRIP LTD', '(US)', '', '118', '0,1%'],
 ['Nintendo', '', '', '118', '0,1%'],
 ['Chipotle Mexican G', 'rill Inc.', 'Class A', '118', '0,1%'],
 ['Melrose Industries', 'PLC', '', '117', '0,1%'],
 ['Hubbell Inc', '', '', '117', '0,1%'],
 ['Shin-Etsu Chemica', 'l Co', '', '117', '0,1%'],
 ['PG&E Corp.', '', '', '116', '0,1%'],
 ['Games Workshop', 'Group', '', '116', '0,1%'],
 ['Kering', '', '', '115', '0,1%'],
 ['Moodys Corp.', '', '', '115', '0,1%'],
 ['Amphenol Corp. A', '', '', '114', '0,1%'],
 ['Zealand Pharma', 'A/S', '', '114', '0,1%'],
 ['Cadence Design S', 'ystems Inc.', '', '114', '0,1%'],
 ['Itochu Corp.', '', '', '113', '0,1%'],
 ['MercadoLibre Inc', '', '', '113', '0,1%'],
 ['Mizuho Financial', 'Group Inc.', '', '113', '0,1%'],
 ['Cellnex Telecom S', '.A.', '', '113', '0,1%'],
 ['CSL Ltd.', '', '', '111', '0,1%'],
 ['Ultra Tech Cemen', 't Ltd.', '', '111', '0,1%'],
 ['Zoetis Inc A', '', '', '110', '0,1%'],
 ['The Cigna Group', '', '', '110', '0,1%'],
 ['COMPUTER AGE', 'MANAGEM', 'ENT SERVICES LTD (IN', '110', '0,1%'],
 ['BROOKFIELD COR', 'P (CA)', '', '109', '0,1%'],
 ['Occidental Petrol', 'eum Corp', '', '109', '0,1%'],
 ['Cheniere Energy I', 'nc.', '', '108', '0,1%'],
 ['Regeneron Pharm', 'aceuticals I', 'nc.', '108', '0,1%'],
 ['Trainline Plc', '', '', '108', '0,1%'],
 ['Aon PLC', '', '', '107', '0,1%'],
 ['Emerson Electric', 'Co.', '', '107', '0,1%'],
 ['Trane Technologi', 'es PLC', '', '107', '0,1%'],
 ['McKesson Corp.', '', '', '107', '0,1%'],
 ['China Merchants', 'Bank - H', '', '107', '0,1%'],
 ['ALCHIP TECHNO', 'LOGIES LTD', 'K (TW)', '107', '0,1%'],
 ['Mitsubishi Corp.', '', '', '107', '0,1%'],
 ['Shenzhou Interna', 'tional Group', 'Ltd', '106', '0,1%'],
 ['NTG Nordic Trans', 'port Group', 'A/S', '106', '0,1%'],
 ['Prestige Estates', 'Projects Ltd', '', '106', '0,1%'],
 ['Macom Technolo', 'gy Solutions', 'Holdings Inc', '105', '0,1%'],
 ['Digital Realty Tru', 'st Inc.', '', '104', '0,1%'],
 ['Pembina Pipeline', 'Corporation', '', '104', '0,1%'],
 ['SLB (USD)', '', '', '103', '0,1%'],
 ['Synopsys Inc.', '', '', '103', '0,1%'],
 ['Becton Dickinson', '& Co.', '', '103', '0,1%'],
 ['Samsung Electron', 'ics', '', '103', '0,1%'],
 ['KEC INTERNATIO', 'NAL LTD (IN', ')', '103', '0,1%'],
 ['Mitsui and Co', '', '', '102', '0,1%'],
 ['L Oreal', '', '', '102', '0,1%'],
 ['CONSTELLATION', 'ENERGY W', '/I (US)', '102', '0,1%'],
 ['RWE AG (Ord)', '', '', '102', '0,1%'],
 ['Novartis (Regd) (C', 'HF)', '', '102', '0,1%'],
 ['Monolithic Power', 'Systems Inc', '.', '101', '0,1%'],
 ['Lyondellbasell Ind', 'ustries NV A', '(USD)', '101', '0,1%'],
 ['Howmet Aerospa', 'ce Inc', '', '100', '0,1%'],
 ['Tractor Supply C', 'o', '', '100', '0,1%'],
 ['National Australi', 'a Bank Lt', 'd', '100', '0,1%'],
 ['Teradyne Inc.', '', '', '100', '0,1%'],
 ['Cintas Corp.', '', '', '100', '0,1%'],
 ['Arthur J. Gallagh', 'er & Co', '', '100', '0,1%'],
 ['Westinghouse A', 'ir Brake T', 'echnologies Corp', '99', '0,1%'],
 ['Alm. Brand', '', '', '99', '0,1%'],
 ['HubSpot Inc', '', '', '98', '0,1%'],
 ['Equifax Inc.', '', '', '97', '0,1%'],
 ['Royal Philips NV', '(NL)', '', '97', '0,1%'],
 ['TC Energy Corpo', 'ration', '', '97', '0,1%'],
 ['Bank of Montrea', 'l (CAD)', '', '96', '0,1%'],
 ['Westpac Bankin', 'g Corp', '', '96', '0,1%'],
 ['Air Products & C', 'hemicals', 'Inc', '96', '0,1%'],
 ['Targa Resources', 'Corp', '', '96', '0,1%'],
 ['Marriott Internat', 'ional Inc.', 'A', '96', '0,1%'],
 ['Daiichi Sankyo C', 'o. Ltd.', '', '95', '0,1%'],
 ['GALDERMA GRO', 'UP AG (C', 'H)', '95', '0,1%'],
 ['O Reilly Automot', 'ive Inc', '', '95', '0,1%'],
 ['KDDI Corp.', '', '', '95', '0,1%'],
 ['JD.com Inc', '', '', '95', '0,1%'],
 ['FedEx Corp.', '', '', '94', '0,1%'],
 ['Capital One Finan', 'cial Corp.', '', '94', '0,0%'],
 ['ARM HOLDINGS', 'PLC ADR', '(US)', '92', '0,0%'],
 ['Canadian Pacific', 'Kansas C', 'ity Limited', '92', '0,0%'],
 ['Apollo Global Ma', 'nagement', 'Inc (US)', '92', '0,0%'],
 ['Hilton Inc', '', '', '92', '0,0%'],
 ['APPLOVIN CORP', 'A (US)', '', '92', '0,0%'],
 ['Mips AB', '', '', '91', '0,0%'],
 ['Ping An Insuranc', 'e (Group)', 'Comp. of China', '91', '0,0%'],
 ['CSX Corp.', '', '', '91', '0,0%'],
 ['Invesco Senior L', 'oan ETF', '', '91', '0,0%'],
 ['Veeva Systems I', 'nc A', '', '90', '0,0%'],
 ['Bank of Nova Sco', 'tia', '', '90', '0,0%'],
 ['Hess Corp.', '', '', '89', '0,0%'],
 ['Target Corp', '', '', '88', '0,0%'],
 ['Legrand SA', '', '', '88', '0,0%'],
 ['Quest Diagnostic', 's Inc.', '', '87', '0,0%'],
 ['Autodesk Inc.', '', '', '87', '0,0%'],
 ['Verisk Analytics', 'Inc. Class', 'A', '86', '0,0%'],
 ['United Rentals In', 'c.', '', '86', '0,0%'],
 ['Lattice Semicond', 'uctor Cor', 'p.', '86', '0,0%'],
 ['Advantest Corp.', '', '', '86', '0,0%'],
 ['ALK-Abello B', '', '', '86', '0,0%'],
 ['Simon Property', 'Group Inc', '', '86', '0,0%'],
 ['Baker Hughes Co', 'mpany A', '', '86', '0,0%'],
 ['Fortinet Inc', '', '', '86', '0,0%'],
 ['Mitsubishi Heav', 'y Industry', '86', '0,0%'],
 ['Bank of New Yor', 'k Mellon Corp.', '85', '0,0%'],
 ['Packaging Corp', 'of America', '85', '0,0%'],
 ['Honda Motor Co', '. Ltd.', '85', '0,0%'],
 ['Bank Rakyat Ind', 'onesia (Persero) Tbk', '85', '0,0%'],
 ['Roche Holding (g', 'enusscheine)', '85', '0,0%'],
 ['Travelers Comp', 'anies Inc.', '85', '0,0%'],
 ['Ametek Inc.', '', '85', '0,0%'],
 ['SS&C Technolo', 'gies Holdings Inc', '84', '0,0%'],
 ['Airtac Internatio', 'nal Group', '84', '0,0%'],
 ['Constellation So', 'ftware Inc', '84', '0,0%'],
 ['General Motors', 'Co.', '84', '0,0%'],
 ['Veracyte Inc.', '', '84', '0,0%'],
 ['Textron Inc.', '', '83', '0,0%'],
 ['HCA Healthcare', 'Inc', '83', '0,0%'],
 ['Twist Bioscienc', 'e Corporation', '83', '0,0%'],
 ['Takeda Pharma', 'ceutical Co Ltd', '83', '0,0%'],
 ['Reply SPA', '', '82', '0,0%'],
 ['Republic Service', 's Inc.', '82', '0,0%'],
 ['CVS Health Cor', 'p.', '82', '0,0%'],
 ['Diamondback En', 'ergy Inc.', '81', '0,0%'],
 ['Symbiotics Sica', 'v - SEB Microfinance Life', '81', '0,0%'],
 ['Reliance Industr', 'ies', '81', '0,0%'],
 ['Mensch und Ma', 'schine Software SE', '81', '0,0%'],
 ['Airbnb Inc A', '', '80', '0,0%'],
 ['PACCAR Inc.', '', '80', '0,0%'],
 ['Canadian Imperi', 'al Bank of Commerce', '80', '0,0%'],
 ['Guidewire Softw', 'are Inc', '80', '0,0%'],
 ['AAK AB', '', '80', '0,0%'],
 ['Titan Company L', 'td', '80', '0,0%'],
 ['Manulife Financi', 'al Corp.', '80', '0,0%'],
 ['Axon Enterprise', 'Inc', '80', '0,0%'],
 ['HEMNET GROU', 'P AB (SE)', '79', '0,0%'],
 ['Tradeweb Mark', 'ets Inc. (A)', '79', '0,0%'],
 ['Coterra Energy I', 'nc', '79', '0,0%'],
 ['Beijer Ref AB B', '', '79', '0,0%'],
 ['Roper Technolo', 'gies Inc', '79', '0,0%'],
 ['Nestle (Regd)', '', '79', '0,0%'],
 ['Nu Holdings Lim', 'ited A (US)', '79', '0,0%'],
 ['ConvaTec Group', 'PLC', '78', '0,0%'],
 ['Allstate Corp.', '', '78', '0,0%'],
 ['Sandoz Group Lt', 'd (CHF)', '78', '0,0%'],
 ['Valero Energy C', 'orp.', '78', '0,0%'],
 ['ANZ Australia &', 'New Zealand Banking Grou', '78', '0,0%'],
 ['GoDaddy Inc A', '', '77', '0,0%'],
 ['Waste Connecti', 'ons Inc (USD)', '77', '0,0%'],
 ['Royal Caribbean', 'Group (USD)', '76', '0,0%'],
 ['UCB S.A.', '', '75', '0,0%'],
 ['Realty Income C', 'orp (US)', '75', '0,0%'],
 ['Ameriprise Fin', 'ancial Inc.', '75', '0,0%'],
 ['Godrej Properti', 'es Ltd', '75', '0,0%'],
 ['CLEARWATER', 'ANALYTICS HOLDINGS INC A (US)', '75', '0,0%'],
 ['NXP Semicond', 'uctors N.V. (USD)', '75', '0,0%'],
 ['Better Collectiv', 'e A/S (DK)', '74', '0,0%'],
 ['Saia Inc', '', '74', '0,0%'],

In [147]:
test = biggestlist[300][0:-2]

test2 = " ".join(test)
test2

'McKesson Corp.  '

In [148]:
for i in range(len(biggestlist)):
    combo = []
    combo = biggestlist[i][0:-2]
    del biggestlist[i][0:-2]
    combo = "".join(combo)
    biggestlist[i].append(combo)

biggestlist

[['', '', 'DANICA PENSION, Specifikation af kapitalandele'],
 ['MARKEDSVÆRDI', '', ''],
 ['31-12-2024 andel %', '', 'MIO. KR.'],
 ['', '', 'BØRSNOTEREDEKAPITALANDELE'],
 ['7.407', '3,9%', 'Apple Inc.'],
 ['6.941', '3,7%', 'Microsoft Corp.'],
 ['6.773', '3,6%', 'Nvidia Corp. (US)'],
 ['5.526', '2,9%', 'Amazon.com'],
 ['4.311', '2,3%', 'Novo Nordisk B'],
 ['3.438', '1,8%', 'Alphabet Inc C'],
 ['3.053', '1,6%', 'Meta Platforms A(US)'],
 ['2.707', '1,4%', 'Broadcom Inc'],
 ['2.258', '1,2%', 'Mastercard Inc-Class A'],
 ['1.955', '1,0%', 'Alphabet Inc A'],
 ['1.754', '0,9%', 'Tesla Inc (US)'],
 ['1.644', '0,9%', 'Coca Cola Co (US)'],
 ['1.640', '0,9%', 'Oracle Corp.'],
 ['1.617', '0,9%', 'Boston ScientificCorp.'],
 ['1.537', '0,8%', 'DSV A/S'],
 ['1.418', '0,8%', 'Abbott Laboratories (US)'],
 ['1.356', '0,7%', 'Fiserv Inc.'],
 ['1.330', '0,7%', 'Bank of AmericaCorp.'],
 ['1.309', '0,7%', 'AstraZeneca Ord(GBP)'],
 ['1.261', '0,7%', 'ASML Holding NV'],
 ['1.218', '0,6%', 'Taiwan Semiconductor Manufacturing Co.'],
 ['1.155', '0,6%', 'UnitedHealth Group Inc.'],
 ['1.102', '0,6%', 'Eaton Corporation Plc (USD)'],
 ['1.068', '0,6%', 'NextEra Energy Inc.'],
 ['1.061', '0,6%', 'Elevance Health Inc'],
 ['1.060', '0,6%', 'Taiwan Semiconductor Manufactoring Co. ('],
 ['1.059', '0,6%', 'JPMorgan Chase& Co.'],
 ['1.012', '0,5%', 'Salesforce Inc'],
 ['992', '0,5%', 'Walmart Inc'],
 ['963', '0,5%', 'NetFlix Inc'],
 ['940', '0,5%', 'Prudential Plc Ord'],
 ['927', '0,5%', 'Thermo Fisher Scientific Inc'],
 ['910', '0,5%', 'Danske Bank'],
 ['902', '0,5%', 'Tencent HoldingsLtd.'],
 ['891', '0,5%', 'Eli Lilly & Co.'],
 ['874', '0,5%', 'Crowdstrike Holdings Inc. A'],
 ['869', '0,5%', 'argenx SE ADR'],
 ['867', '0,5%', 'Novonesis (Novozymes) B'],
 ['842', '0,4%', 'BP Plc'],
 ['835', '0,4%', 'Berkshire Hathaway Inc. B'],
 ['832', '0,4%', 'AIA Group Ltd'],
 ['818', '0,4%', 'Samsonite International SA (HKD)'],
 ['810', '0,4%', 'Accor SA'],
 ['799', '0,4%', 'Advanced MicroDevices Inc.'],
 ['790', '0,4%', 'Prosus N.V.'],
 ['780', '0,4%', 'TransUnion'],
 ['774', '0,4%', 'Home Depot Inc.'],
 ['770', '0,4%', 'GE AEROSPACE(US)'],
 ['751', '0,4%', 'Visa Inc Class A'],
 ['743', '0,4%', 'adidas AG Reg.'],
 ['709', '0,4%', 'London Stock Exchange Group Plc'],
 ['677', '0,4%', 'Coloplast B'],
 ['677', '0,4%', 'Uber Technologies Inc'],
 ['666', '0,4%', 'Siemens AG (Regd)'],
 ['611', '0,3%', 'Teledyne Technologies Inc.'],
 ['603', '0,3%', 'SAP SE (Ord)'],
 ['600', '0,3%', 'Pandora'],
 ['591', '0,3%', 'Costco Wholesale Corp.'],
 ['585', '0,3%', 'Keysight Technologies Inc'],
 ['580', '0,3%', 'Lonza Group (Regd)'],
 ['579', '0,3%', 'Heineken'],
 ['574', '0,3%', 'West Pharmaceuticals Services'],
 ['570', '0,3%', 'Micron Technology'],
 ['563', '0,3%', 'Zscaler Inc'],
 ['556', '0,3%', 'Procter & Gamble Co.'],
 ['537', '0,3%', 'Keyence Corp.'],
 ['535', '0,3%', 'Puma SE'],
 ['522', '0,3%', 'Estee Lauder Co.A'],
 ['517', '0,3%', 'Johnson & Johnson'],
 ['510', '0,3%', 'Blue Owl CapitalInc A'],
 ['510', '0,3%', 'BNP Paribas S.A.'],
 ['509', '0,3%', 'Adobe Inc. (US)'],
 ['506', '0,3%', 'Sea A Ltd ADR'],
 ['496', '0,3%', 'U.S. Bancorp'],
 ['492', '0,3%', 'Netcompany Group A/S'],
 ['490', '0,3%', 'ServiceNow Inc.'],
 ['485', '0,3%', 'Techtronic Industries Co. Ltd.'],
 ['484', '0,3%', 'Trimble Inc'],
 ['476', '0,3%', 'AutoZone Inc.'],
 ['467', '0,2%', 'Parker-HannifinCorp.'],
 ['463', '0,2%', 'Shopify Inc A (US)'],
 ['462', '0,2%', 'Linde PLC (US)'],
 ['458', '0,2%', 'Tryg A/S'],
 ['456', '0,2%', 'Tokyo Electron'],
 ['444', '0,2%', 'AbbVie Inc'],
 ['439', '0,2%', 'HDFC Bank Ltd'],
 ['436', '0,2%', 'Coca Cola HBC NamenAkt. (GBP)'],
 ['429', '0,2%', 'Arista Networks Inc (US)'],
 ['428', '0,2%', 'Erste Group BankAG (AT) (EUR)'],
 ['420', '0,2%', 'Centene Corp'],
 ['418', '0,2%', 'Hiscox Ltd'],
 ['410', '0,2%', 'Chevron Corp.'],
 ['405', '0,2%', 'Danaher Corp. (US)'],
 ['397', '0,2%', 'Ally Financial Inc'],
 ['394', '0,2%', 'S&P Global Inc'],
 ['393', '0,2%', 'Merck & Co. Inc. (US)'],
 ['392', '0,2%', 'Toyota Motor Corp.'],
 ['387', '0,2%', 'Ctrip.com International Ltd ADR'],
 ['381', '0,2%', 'Quanta Services Inc.'],
 ['361', '0,2%', 'Alibaba Group HoldingLtd'],
 ['360', '0,2%', 'Colgate-PalmoliveCo.'],
 ['349', '0,2%', 'Vestas Wind SystemsA/S'],
 ['349', '0,2%', 'PepsiCo Inc.'],
 ['346', '0,2%', 'Cisco Systems Inc.'],
 ['339', '0,2%', 'Ørsted A/S'],
 ['339', '0,2%', 'Atlassian CorporationPLC A'],
 ['338', '0,2%', 'ICICI Bank (ADR)'],
 ['337', '0,2%', 'Genmab A/S'],
 ['336', '0,2%', 'Ascendis PharmaA/S(ADR)'],
 ['336', '0,2%', 'Wells Fargo Co. (US)'],
 ['333', '0,2%', 'Workday Inc'],
 ['323', '0,2%', 'A.P. Moller - Marsk B'],
 ['316', '0,2%', 'Ferrovial SE (ES)'],
 ['315', '0,2%', 'Goldman Sachs GroupInc.'],
 ['313', '0,2%', 'Infineon TechnologiesAG'],
 ['311', '0,2%', 'Accenture Plc A (USD)'],
 ['311', '0,2%', 'Carlsberg B'],
 ['307', '0,2%', 'Samsung Electronics (Pref.)'],
 ['305', '0,2%', 'McDonalds Corp.'],
 ['300', '0,2%', 'Norfolk SouthernCorp'],
 ['300', '0,2%', 'ING Groep NV'],
 ['299', '0,2%', 'IBM'],
 ['295', '0,2%', 'Citigroup Inc. (US)'],
 ['294', '0,2%', 'Live Nation Entertainment Inc.'],
 ['293', '0,2%', 'Meituan B'],
 ['290', '0,2%', 'PNC Financial Services Group Inc.'],
 ['288', '0,2%', 'Walt Disney (USD)'],
 ['285', '0,2%', 'DBS Group Holding'],
 ['281', '0,1%', 'Intuit Inc.'],
 ['280', '0,1%', 'RTX Corporation (US)'],
 ['278', '0,1%', 'Xylem Inc'],
 ['275', '0,1%', 'Siemens EnergyAG'],
 ['270', '0,1%', 'SK Hynix Inc.'],
 ['266', '0,1%', 'SAAB AB B'],
 ['262', '0,1%', 'Sony Group Corp'],
 ['260', '0,1%', 'Union Pacific Corp.'],
 ['260', '0,1%', 'Intuitive SurgicalInc.'],
 ['256', '0,1%', 'Vertex PharmaceuticalsInc. (USD)'],
 ['250', '0,1%', 'Mitsubishi UFJ FinancialGroup'],
 ['249', '0,1%', 'MediaTek Inc.'],
 ['248', '0,1%', 'Verizon Communications Inc. (US)'],
 ['244', '0,1%', 'Texas Instruments (USD)'],
 ['242', '0,1%', 'QUALCOMM Inc.(US)'],
 ['242', '0,1%', 'Caterpillar Inc.'],
 ['241', '0,1%', 'Ecolab Inc.'],
 ['240', '0,1%', 'American Express'],
 ['238', '0,1%', 'AT&T Inc.'],
 ['237', '0,1%', 'Tetragon Financial GroupLtd (NL)'],
 ['236', '0,1%', 'Vinci SA'],
 ['236', '0,1%', 'Royal Bank of Canada'],
 ['233', '0,1%', 'MARVELL TECHNOLOGY INC (US)'],
 ['233', '0,1%', 'Progressive Corp'],
 ['231', '0,1%', 'Booking HoldingsInc'],
 ['230', '0,1%', 'Schneider Electric'],
 ['227', '0,1%', 'Adyen B.V.'],
 ['226', '0,1%', 'Demant A/S'],
 ['225', '0,1%', 'Ringkjobing LandbobankA/S'],
 ['225', '0,1%', 'Pfizer Inc. (US)'],
 ['224', '0,1%', 'Indian Hotels Co.Ltd'],
 ['222', '0,1%', 'Lowes Co.'],
 ['222', '0,1%', 'Hitachi'],
 ['220', '0,1%', 'Amadeus IT Group S.A'],
 ['220', '0,1%', 'Morgan Stanley'],
 ['218', '0,1%', 'BlackRock Inc'],
 ['217', '0,1%', 'Sanofi (FR)'],
 ['215', '0,1%', 'Commonwealth Bank ofAustralia'],
 ['215', '0,1%', 'TotalEnergies SE(FR)'],
 ['212', '0,1%', 'Comcast Corp. A'],
 ['212', '0,1%', 'Palantir Technologies Inc'],
 ['209', '0,1%', 'Hoya Corp.'],
 ['207', '0,1%', 'INVISIO AB'],
 ['206', '0,1%', 'Applied MaterialsInc.'],
 ['201', '0,1%', 'Honeywell International Inc.'],
 ['200', '0,1%', 'Amgen Inc.'],
 ['198', '0,1%', 'GE VERNOVA LLC (US)'],
 ['195', '0,1%', 'Palo Alto Networks Inc'],
 ['194', '0,1%', 'MetLife Inc.'],
 ['192', '0,1%', 'TJX Co. Inc.'],
 ['191', '0,1%', 'Recruit HoldingsCo.Ltd.'],
 ['191', '0,1%', 'CBRE Group Inc'],
 ['189', '0,1%', 'State Bank of India'],
 ['188', '0,1%', 'Nike Inc B'],
 ['188', '0,1%', 'KLA Corporation'],
 ['185', '0,1%', 'Tyler Technologies Inc'],
 ['184', '0,1%', 'Unilever Plc Ord'],
 ['183', '0,1%', 'Automatic DataProcessing Inc'],
 ['183', '0,1%', 'ChemoMetec'],
 ['180', '0,1%', 'Stryker Corp.'],
 ['179', '0,1%', 'RELX PLC'],
 ['178', '0,1%', 'T-Mobile US Inc'],
 ['178', '0,1%', 'PayPal Holdings Inc (US)'],
 ['177', '0,1%', 'BHP GROUP Ltd'],
 ['176', '0,1%', 'Equinor ASA'],
 ['175', '0,1%', 'Blackstone Inc'],
 ['175', '0,1%', 'SEMPRA'],
 ['174', '0,1%', 'Dassault Systemes SA'],
 ['173', '0,1%', 'Shopify Inc A'],
 ['173', '0,1%', 'Bristol-Myers Squibb Co. (US)'],
 ['172', '0,1%', 'Elis SA'],
 ['170', '0,1%', 'Softbank Group Corp (JP)'],
 ['170', '0,1%', 'Sumitomo MitsuiFinancial Group Inc.'],
 ['169', '0,1%', 'Charles SchwabCorp.'],
 ['168', '0,1%', 'DANONE SA'],
 ['165', '0,1%', 'ON Semiconductor Corp.'],
 ['165', '0,1%', 'Consolidated Edison Inc.'],
 ['165', '0,1%', 'Hong Kong Exchanges & Clearing Ltd.'],
 ['164', '0,1%', 'Nordea Bank Abp(DK) DKK'],
 ['164', '0,1%', 'Chroma Ate Inc.'],
 ['163', '0,1%', 'Marsh & McLennan Co. Inc.'],
 ['163', '0,1%', 'Chubb Ltd (USD)'],
 ['160', '0,1%', 'Gilead Sciences Inc.'],
 ['159', '0,1%', 'Amber Enterprises India Ltd'],
 ['158', '0,1%', 'Per Aarsleff Holding A/S'],
 ['158', '0,1%', 'LVMH Moet Hennessy Louis Vuitton SE (FR)'],
 ['158', '0,1%', 'APAR INDUSTRIES LTD (IN)'],
 ['158', '0,1%', 'Truist Financial Corporation'],
 ['156', '0,1%', '3M COMPANY LTD'],
 ['156', '0,1%', 'Williams Co. Inc.'],
 ['156', '0,1%', 'Hexagon AB B'],
 ['156', '0,1%', 'Deere & Co.'],
 ['155', '0,1%', 'Medtronic PLC'],
 ['155', '0,1%', 'Analog Devices Inc'],
 ['154', '0,1%', 'Equinix Inc (US)'],
 ['153', '0,1%', 'ENEL SpA'],
 ['150', '0,1%', 'Deutsche BörseAG'],
 ['149', '0,1%', 'Sunny Optical Technology(Group) Co Ltd'],
 ['148', '0,1%', 'Starbucks Corp'],
 ['146', '0,1%', 'ProLogis Inc.'],
 ['146', '0,1%', 'Kinder Morgan Inc'],
 ['143', '0,1%', 'Welltower OP Inc'],
 ['143', '0,1%', 'CRH PLC (US)'],
 ['143', '0,1%', 'EOG Resources Inc.'],
 ['142', '0,1%', 'Edison International'],
 ['140', '0,1%', 'PT Bank Central Asia Tbk'],
 ['140', '0,1%', 'AFLAC Inc.'],
 ['140', '0,1%', 'Carrier Global Corporation'],
 ['139', '0,1%', 'Petershill PartnersPLC'],
 ['138', '0,1%', 'Sage Group Plc Ord'],
 ['138', '0,1%', 'Phoenix Mills Ltd./The'],
 ['135', '0,1%', 'ONEOK Inc.'],
 ['134', '0,1%', 'ISS'],
 ['134', '0,1%', 'United Parcel Service Inc.B U.P.S.'],
 ['133', '0,1%', 'Tokio Marine Holdings Inc.'],
 ['132', '0,1%', 'CME Group Inc'],
 ['132', '0,1%', 'Sherwin-WilliamsCo.'],
 ['130', '0,1%', 'Lam Research Corp'],
 ['130', '0,1%', 'Royal Unibrew'],
 ['129', '0,1%', 'Fast Retailing'],
 ['129', '0,1%', 'GN Store Nord'],
 ['129', '0,1%', 'Waste Management Inc.'],
 ['129', '0,1%', 'Deutsche Post AG'],
 ['129', '0,1%', 'American Tower Corp'],
 ['129', '0,1%', 'Toronto-DominionBank (CA)'],
 ['128', '0,1%', 'Volvo B'],
 ['128', '0,1%', 'KKR & Co IncA'],
 ['127', '0,1%', 'Public Service EnterpriseGroup'],
 ['125', '0,1%', 'Intercontinental ExchangeInc'],
 ['125', '0,1%', 'American International Group Inc.'],
 ['123', '0,1%', 'Mondelez International Inc'],
 ['122', '0,1%', 'Intel Corp.'],
 ['122', '0,1%', 'Exelon Corp.'],
 ['122', '0,1%', 'Motorola SolutionsInc'],
 ['121', '0,1%', 'Liberty Media CorpC Liberty Formula One'],
 ['120', '0,1%', 'Spotify TechnologySA (USD)'],
 ['120', '0,1%', 'Newmont Corporation'],
 ['119', '0,1%', 'Illinois Tool WorksInc.'],
 ['118', '0,1%', 'MAKEMYTRIP LTD(US)'],
 ['118', '0,1%', 'Nintendo'],
 ['118', '0,1%', 'Chipotle Mexican Grill Inc.Class A'],
 ['117', '0,1%', 'Melrose IndustriesPLC'],
 ['117', '0,1%', 'Hubbell Inc'],
 ['117', '0,1%', 'Shin-Etsu Chemical Co'],
 ['116', '0,1%', 'PG&E Corp.'],
 ['116', '0,1%', 'Games WorkshopGroup'],
 ['115', '0,1%', 'Kering'],
 ['115', '0,1%', 'Moodys Corp.'],
 ['114', '0,1%', 'Amphenol Corp. A'],
 ['114', '0,1%', 'Zealand PharmaA/S'],
 ['114', '0,1%', 'Cadence Design Systems Inc.'],
 ['113', '0,1%', 'Itochu Corp.'],
 ['113', '0,1%', 'MercadoLibre Inc'],
 ['113', '0,1%', 'Mizuho FinancialGroup Inc.'],
 ['113', '0,1%', 'Cellnex Telecom S.A.'],
 ['111', '0,1%', 'CSL Ltd.'],
 ['111', '0,1%', 'Ultra Tech Cement Ltd.'],
 ['110', '0,1%', 'Zoetis Inc A'],
 ['110', '0,1%', 'The Cigna Group'],
 ['110', '0,1%', 'COMPUTER AGEMANAGEMENT SERVICES LTD (IN'],
 ['109', '0,1%', 'BROOKFIELD CORP (CA)'],
 ['109', '0,1%', 'Occidental Petroleum Corp'],
 ['108', '0,1%', 'Cheniere Energy Inc.'],
 ['108', '0,1%', 'Regeneron Pharmaceuticals Inc.'],
 ['108', '0,1%', 'Trainline Plc'],
 ['107', '0,1%', 'Aon PLC'],
 ['107', '0,1%', 'Emerson ElectricCo.'],
 ['107', '0,1%', 'Trane Technologies PLC'],
 ['107', '0,1%', 'McKesson Corp.'],
 ['107', '0,1%', 'China MerchantsBank - H'],
 ['107', '0,1%', 'ALCHIP TECHNOLOGIES LTDK (TW)'],
 ['107', '0,1%', 'Mitsubishi Corp.'],
 ['106', '0,1%', 'Shenzhou International GroupLtd'],
 ['106', '0,1%', 'NTG Nordic Transport GroupA/S'],
 ['106', '0,1%', 'Prestige EstatesProjects Ltd'],
 ['105', '0,1%', 'Macom Technology SolutionsHoldings Inc'],
 ['104', '0,1%', 'Digital Realty Trust Inc.'],
 ['104', '0,1%', 'Pembina PipelineCorporation'],
 ['103', '0,1%', 'SLB (USD)'],
 ['103', '0,1%', 'Synopsys Inc.'],
 ['103', '0,1%', 'Becton Dickinson& Co.'],
 ['103', '0,1%', 'Samsung Electronics'],
 ['103', '0,1%', 'KEC INTERNATIONAL LTD (IN)'],
 ['102', '0,1%', 'Mitsui and Co'],
 ['102', '0,1%', 'L Oreal'],
 ['102', '0,1%', 'CONSTELLATIONENERGY W/I (US)'],
 ['102', '0,1%', 'RWE AG (Ord)'],
 ['102', '0,1%', 'Novartis (Regd) (CHF)'],
 ['101', '0,1%', 'Monolithic PowerSystems Inc.'],
 ['101', '0,1%', 'Lyondellbasell Industries NV A(USD)'],
 ['100', '0,1%', 'Howmet Aerospace Inc'],
 ['100', '0,1%', 'Tractor Supply Co'],
 ['100', '0,1%', 'National Australia Bank Ltd'],
 ['100', '0,1%', 'Teradyne Inc.'],
 ['100', '0,1%', 'Cintas Corp.'],
 ['100', '0,1%', 'Arthur J. Gallagher & Co'],
 ['99', '0,1%', 'Westinghouse Air Brake Technologies Corp'],
 ['99', '0,1%', 'Alm. Brand'],
 ['98', '0,1%', 'HubSpot Inc'],
 ['97', '0,1%', 'Equifax Inc.'],
 ['97', '0,1%', 'Royal Philips NV(NL)'],
 ['97', '0,1%', 'TC Energy Corporation'],
 ['96', '0,1%', 'Bank of Montreal (CAD)'],
 ['96', '0,1%', 'Westpac Banking Corp'],
 ['96', '0,1%', 'Air Products & ChemicalsInc'],
 ['96', '0,1%', 'Targa ResourcesCorp'],
 ['96', '0,1%', 'Marriott International Inc.A'],
 ['95', '0,1%', 'Daiichi Sankyo Co. Ltd.'],
 ['95', '0,1%', 'GALDERMA GROUP AG (CH)'],
 ['95', '0,1%', 'O Reilly Automotive Inc'],
 ['95', '0,1%', 'KDDI Corp.'],
 ['95', '0,1%', 'JD.com Inc'],
 ['94', '0,1%', 'FedEx Corp.'],
 ['94', '0,0%', 'Capital One Financial Corp.'],
 ['92', '0,0%', 'ARM HOLDINGSPLC ADR(US)'],
 ['92', '0,0%', 'Canadian PacificKansas City Limited'],
 ['92', '0,0%', 'Apollo Global ManagementInc (US)'],
 ['92', '0,0%', 'Hilton Inc'],
 ['92', '0,0%', 'APPLOVIN CORPA (US)'],
 ['91', '0,0%', 'Mips AB'],
 ['91', '0,0%', 'Ping An Insurance (Group)Comp. of China'],
 ['91', '0,0%', 'CSX Corp.'],
 ['91', '0,0%', 'Invesco Senior Loan ETF'],
 ['90', '0,0%', 'Veeva Systems Inc A'],
 ['90', '0,0%', 'Bank of Nova Scotia'],
 ['89', '0,0%', 'Hess Corp.'],
 ['88', '0,0%', 'Target Corp'],
 ['88', '0,0%', 'Legrand SA'],
 ['87', '0,0%', 'Quest Diagnostics Inc.'],
 ['87', '0,0%', 'Autodesk Inc.'],
 ['86', '0,0%', 'Verisk AnalyticsInc. ClassA'],
 ['86', '0,0%', 'United Rentals Inc.'],
 ['86', '0,0%', 'Lattice Semiconductor Corp.'],
 ['86', '0,0%', 'Advantest Corp.'],
 ['86', '0,0%', 'ALK-Abello B'],
 ['86', '0,0%', 'Simon PropertyGroup Inc'],
 ['86', '0,0%', 'Baker Hughes Company A'],
 ['86', '0,0%', 'Fortinet Inc'],
 ['86', '0,0%', 'Mitsubishi Heavy Industry'],
 ['85', '0,0%', 'Bank of New York Mellon Corp.'],
 ['85', '0,0%', 'Packaging Corpof America'],
 ['85', '0,0%', 'Honda Motor Co. Ltd.'],
 ['85', '0,0%', 'Bank Rakyat Indonesia (Persero) Tbk'],
 ['85', '0,0%', 'Roche Holding (genusscheine)'],
 ['85', '0,0%', 'Travelers Companies Inc.'],
 ['85', '0,0%', 'Ametek Inc.'],
 ['84', '0,0%', 'SS&C Technologies Holdings Inc'],
 ['84', '0,0%', 'Airtac International Group'],
 ['84', '0,0%', 'Constellation Software Inc'],
 ['84', '0,0%', 'General MotorsCo.'],
 ['84', '0,0%', 'Veracyte Inc.'],
 ['83', '0,0%', 'Textron Inc.'],
 ['83', '0,0%', 'HCA HealthcareInc'],
 ['83', '0,0%', 'Twist Bioscience Corporation'],
 ['83', '0,0%', 'Takeda Pharmaceutical Co Ltd'],
 ['82', '0,0%', 'Reply SPA'],
 ['82', '0,0%', 'Republic Services Inc.'],
 ['82', '0,0%', 'CVS Health Corp.'],
 ['81', '0,0%', 'Diamondback Energy Inc.'],
 ['81', '0,0%', 'Symbiotics Sicav - SEB Microfinance Life'],
 ['81', '0,0%', 'Reliance Industries'],
 ['81', '0,0%', 'Mensch und Maschine Software SE'],
 ['80', '0,0%', 'Airbnb Inc A'],
 ['80', '0,0%', 'PACCAR Inc.'],
 ['80', '0,0%', 'Canadian Imperial Bank of Commerce'],
 ['80', '0,0%', 'Guidewire Software Inc'],
 ['80', '0,0%', 'AAK AB'],
 ['80', '0,0%', 'Titan Company Ltd'],
 ['80', '0,0%', 'Manulife Financial Corp.'],
 ['80', '0,0%', 'Axon EnterpriseInc'],
 ['79', '0,0%', 'HEMNET GROUP AB (SE)'],
 ['79', '0,0%', 'Tradeweb Markets Inc. (A)'],
 ['79', '0,0%', 'Coterra Energy Inc'],
 ['79', '0,0%', 'Beijer Ref AB B'],
 ['79', '0,0%', 'Roper Technologies Inc'],
 ['79', '0,0%', 'Nestle (Regd)'],
 ['79', '0,0%', 'Nu Holdings Limited A (US)'],
 ['78', '0,0%', 'ConvaTec GroupPLC'],
 ['78', '0,0%', 'Allstate Corp.'],
 ['78', '0,0%', 'Sandoz Group Ltd (CHF)'],
 ['78', '0,0%', 'Valero Energy Corp.'],
 ['78', '0,0%', 'ANZ Australia &New Zealand Banking Grou'],
 ['77', '0,0%', 'GoDaddy Inc A'],
 ['77', '0,0%', 'Waste Connections Inc (USD)'],
 ['76', '0,0%', 'Royal CaribbeanGroup (USD)'],
 ['75', '0,0%', 'UCB S.A.'],
 ['75', '0,0%', 'Realty Income Corp (US)'],
 ['75', '0,0%', 'Ameriprise Financial Inc.'],
 ['75', '0,0%', 'Godrej Properties Ltd'],
 ['75', '0,0%', 'CLEARWATERANALYTICS HOLDINGS INC A (US)'],
 ['75', '0,0%', 'NXP Semiconductors N.V. (USD)'],
 ['74', '0,0%', 'Better Collective A/S (DK)'],
 ['74', '0,0%', 'Saia Inc'],
 ['74', '0,0%', 'Smiths Group Plc Ord'],
 ['74', '0,0%', 'Nemetschek SE'],
 ['74', '0,0%', 'International Container Terminal Service'],
 ['73', '0,0%', 'MicroStrategy Inc. A'],
 ['73', '0,0%', 'Paychex'],
 ['73', '0,0%', 'Proya Cosmetics Co., Ltd A'],
 ['73', '0,0%', 'Harvia Oyj'],
 ['72', '0,0%', 'W.W. GraingerInc.'],
 ['72', '0,0%', 'Copart Inc.'],
 ['72', '0,0%', 'Atmos EnergyCorp.'],
 ['72', '0,0%', 'Better Collective A/S (SEK)'],
 ['72', '0,0%', 'ID Logistics Group'],
 ['72', '0,0%', 'TRADE DESK INC THE -CLASS A'],
 ['72', '0,0%', 'Public Storage'],
 ['72', '0,0%', 'SHELL PLC (GB)'],
 ['71', '0,0%', 'Canadian National Railway Co. (CA)'],
 ['71', '0,0%', 'SIG Group AG'],
 ['70', '0,0%', 'ABB (Regd)'],
 ['70', '0,0%', 'Kerry Group A'],
 ['70', '0,0%', 'HSBC HoldingsPlc Ord (UK Reg)'],
 ['70', '0,0%', 'Medicover ABB'],
 ['70', '0,0%', 'Infosys Ltd. (ADR)'],
 ['70', '0,0%', 'SoftBank Corp'],
 ['69', '0,0%', 'DoorDash Inc A'],
 ['69', '0,0%', 'Devon Energy Corp.'],
 ['69', '0,0%', 'Wesfarmers Ltd'],
 ['69', '0,0%', 'Eversource Energy'],
 ['69', '0,0%', 'Volkswagen AG(Pref)'],
 ['69', '0,0%', 'Kimberly-ClarkCorp.'],
 ['68', '0,0%', 'Ross Stores Inc.'],
 ['68', '0,0%', 'Trifork Group AG'],
 ['68', '0,0%', 'Johnson Controls International PLC (USD)'],
 ['68', '0,0%', 'Shimano Inc.'],
 ['67', '0,0%', 'Seven & I Holdings Co. Ltd.'],
 ['67', '0,0%', 'Pure Storage Inc -A'],
 ['67', '0,0%', 'cBrain'],
 ['67', '0,0%', 'Cummins Inc.'],
 ['67', '0,0%', 'KE Holdings IncADR A'],
 ['67', '0,0%', 'MSCI Inc'],
 ['67', '0,0%', 'Fair Isaac Corp.'],
 ['67', '0,0%', 'SITC International Holdings Co Ltd'],
 ['66', '0,0%', 'Coinbase Global Inc A'],
 ['66', '0,0%', 'General Mills Inc.'],
 ['66', '0,0%', 'SM Investments Corp.'],
 ['66', '0,0%', 'GUDENG PRECISION INDUSTRIAL CO LTD (TW)'],
 ['66', '0,0%', 'iRhythm Technologies Inc'],
 ['65', '0,0%', 'Edwards Lifesciences Corp.'],
 ['65', '0,0%', 'SNOWFLAKE INC-CLASS A (US)'],
 ['65', '0,0%', 'Fastenal Company'],
 ['65', '0,0%', 'Sydbank'],
 ['65', '0,0%', 'Samsung Electronics GDR USD (GB)'],
 ['64', '0,0%', 'OX2 AB (publ)'],
 ['64', '0,0%', 'Anta Sports Products Ltd'],
 ['64', '0,0%', 'Bharti Airtel Limited'],
 ['64', '0,0%', 'KENVUE INC (US)'],
 ['64', '0,0%', 'Block Inc A'],
 ['64', '0,0%', 'Keyera Corp'],
 ['64', '0,0%', 'Universal Music Group N.V. (NL)'],
 ['64', '0,0%', 'Illumina Inc.'],
 ['63', '0,0%', 'Mitsubishi Electric'],
 ['63', '0,0%', 'Tencent MusicEntertainment Group ADR A'],
 ['63', '0,0%', 'Kroger Co'],
 ['63', '0,0%', 'Castle International Corp'],
 ['62', '0,0%', 'Gubra A/S'],
 ['62', '0,0%', 'Agnico Eagle Mines (CAD)'],
 ['62', '0,0%', 'EDP-Energias de Portugal S.A.'],

In [149]:
table = pd.DataFrame(biggestlist[4:-5], columns=['marketvalue', 'share%', 'listedshares'])
table

     marketvalue share%                                      listedshares
0          7.407   3,9%                                        Apple Inc.
1          6.941   3,7%                                   Microsoft Corp.
2          6.773   3,6%                                 Nvidia Corp. (US)
3          5.526   2,9%                                        Amazon.com
4          4.311   2,3%                                    Novo Nordisk B
...          ...    ...                                               ...
2557           2   0,0%                     Global Infrastructure Partner
2558           2   0,0%            Mount Kellet Capital Partners CaymanLP
2559           1   0,0%  Angelo Gordon CapitalRecovery Partners VIII, L.P
2560           1   0,0%       ICG Asia Pacific Mezzanine Fund 2005 LP USD
2561           1   0,0%         Saga Private Equity Partners III (USD)K/S

[2562 rows x 3 columns]

In [150]:
reorder = ['listedshares', 'marketvalue', 'share%']
table2 = table[reorder]
table2

                                          listedshares marketvalue share%
0                                           Apple Inc.       7.407   3,9%
1                                      Microsoft Corp.       6.941   3,7%
2                                    Nvidia Corp. (US)       6.773   3,6%
3                                           Amazon.com       5.526   2,9%
4                                       Novo Nordisk B       4.311   2,3%
...                                                ...         ...    ...
2557                     Global Infrastructure Partner           2   0,0%
2558            Mount Kellet Capital Partners CaymanLP           2   0,0%
2559  Angelo Gordon CapitalRecovery Partners VIII, L.P           1   0,0%
2560       ICG Asia Pacific Mezzanine Fund 2005 LP USD           1   0,0%
2561         Saga Private Equity Partners III (USD)K/S           1   0,0%

[2562 rows x 3 columns]

In [152]:
table2.to_csv('danicapension.csv')