In [77]:
import pdfplumber
import pandas as pd

In [78]:
pdf = pdfplumber.open("PKA.pdf")

In [79]:
tabs=[]
for page in pdf.pages:
    tabs.append(page.extract_tables(table_settings={"vertical_strategy": "text", "text_x_tolerance": 10}))

tabs

CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox

[[[['3I GROUP', 'US88557W1018', '29.605.115,44', '0,07', '%'],
   ['AAC TECHNOLOGIES (CN)', 'KYG2953R1149', '2.655.026,62', '0,01', '%'],
   ['3M CO', 'GB00B1YW4409', '49.450.996,40', '0,12', '%'],
   ['ABB INDIA', 'US88579Y1010', '2.652.723,48', '0,01', '%'],
   ['ABB LTD', 'KYG2953R1149', '53.407.655,61', '0,13', '%'],
   ['ABBOTT LABORATORIES', 'INE117A01022', '138.627.032,19', '0,34', '%'],
   ['ABBVIE', 'CH0012221716', '234.088.585,31', '0,57', '%'],
   ['ABN AMRO BANK A', 'US0028241000', '9.684.515,34', '0,02', '%'],
   ['ABSA GROUP', 'US00287Y1091', '3.307.828,00', '0,01', '%'],
   ['ABU DHABI COMM BANK', 'NL0011540547', '8.921.788,71', '0,02', '%'],
   ['ABU DHABI NATL OIL CO', 'ZAE000255915', '4.752.599,36', '0,01', '%'],
   ['ACCENTURE A', 'AEA000201011', '124.753.863,37', '0,30', '%'],
   ['ACCIONA', 'AEA006101017', '188.359,26', '0,00', '%'],
   ['ACCOR', 'IE00B4BNMY34', '4.838.817,36', '0,01', '%'],
   ['ACCTON TECHNOLOGY CORP', 'ES0125220311', '2.755.815,44', '0,01', '%'],
   ['ACER', 'FR0000120404', '3.004.846,89', '0,01', '%'],
   ['ACS ACTIV CONST Y SVCS', 'TW0002345006', '2.219.996,65', '0,01', '%'],
   ['ADANI ENTERPRISES', 'TW0002353000', '1.841.928,36', '0,00', '%'],
   ['ADANI PORTS AND SEZ', 'ES0167050915', '3.388.746,48', '0,01', '%'],
   ['ADDTECH B', 'INE423A01024', '5.780.304,51', '0,01', '%'],
   ['ADIDAS', 'INE742F01042', '22.863.541,39', '0,06', '%']]],
 [[['ADNOC DRILLING COMPANY', 'DE000A1EWWW0', '4.283.287,49', '0,01', '%'],
   ['ADOBE', 'GB00B02J6398', '108.629.735,16', '0,27', '%'],
   ['ADP', 'AEA007301012', '1.042.973,97', '0,00', '%'],
   ['ADVANCED INFO SERVICE-NVDR', 'US00724F1012', '3.331.197,52', '0,01', '%'],
   ['ADVANCED MICRO DEVICES', 'FR0010340141', '116.363.442,50', '0,28', '%'],
   ['ADVANTEST CORP', 'TH0268010R11', '22.717.726,53', '0,06', '%'],
   ['ADYEN NV', 'US0079031078', '18.912.755,29', '0,05', '%'],
   ['AECOM', 'JP3122400009', '8.188.891,77', '0,02', '%'],
   ['AEGON', 'NL0012969182', '9.200.334,70', '0,02', '%'],
   ['AENA', 'US00766T1007', '16.875.532,53', '0,04', '%'],
   ['AEON CO', 'BMG0112X1056', '11.517.698,26', '0,03', '%'],
   ['AERCAP HOLDINGS NV', 'ES0105046009', '18.558.075,83', '0,05', '%'],
   ['AFLAC', 'JP3388200002', '37.575.282,52', '0,09', '%'],
   ['AGC', 'NL0000687663', '3.980.231,18', '0,01', '%'],
   ['AGEAS', 'US0010551028', '3.541.409,54', '0,01', '%'],
   ['AGILENT TECHNOLOGIES', 'JP3112000009', '26.161.264,32', '0,06', '%'],
   ['AGNICO EAGLE MINES', 'BE0974264930', '40.416.110,44', '0,10', '%'],
   ['AGRI BANK OF CHINA H', 'US00846U1016', '2.849.995,78', '0,01', '%'],
   ['AGRI BANK OF CN A (HK-C)', 'CA0084741085', '4.130.870,83', '0,01', '%'],
   ['AHOLD DELHAIZE', 'CNE100000RJ0', '18.326.117,57', '0,04', '%'],
   ['AIA GROUP', 'CNE100000Q43', '54.804.772,85', '0,13', '%']]],
 [[['AIR CANADA V', 'V', 'IE00BF0L3536', '2.400.373,98', '0,01', '%'],
   ['AIR LIQUIDE', '', 'CA0089118776', '47.400.016,68', '0,12', '%'],
   ['AIR PRODUCT',
    'S & CHEMICALS',
    'FR0000120073',
    '35.998.524,75',
    '0,09',
    '%'],
   ['AIRBNB A', '', 'US0091581068', '30.514.520,39', '0,07', '%'],
   ['AIRPORTS OF',
    'THAILAND PCL-FOR',
    'US0090661010',
    '3.287.054,70',
    '0,01',
    '%'],
   ['AIRTAC INTER', 'NATIONAL', 'TH0765010Z16', '2.074.350,21', '0,01', '%'],
   ['AISIN CORP', '', 'KYG014081064', '1.574.163,77', '0,00', '%'],
   ['AJINOMOTO C', 'O', 'JP3102000001', '12.407.098,27', '0,03', '%'],
   ['AKAMAI TECH', 'NOLOGIES', 'JP3119600009', '8.403.771,49', '0,02', '%'],
   ['AKBANK', '', 'US00971T1016', '1.596.557,50', '0,00', '%'],
   ['AKER BP', '', 'TRAAKBNK91N6', '10.736.347,09', '0,03', '%'],
   ['AKESO (CN)', '', 'NO0010345853', '2.570.471,64', '0,01', '%'],
   ['AKZO NOBEL', '', 'KYG0146B1032', '11.288.852,30', '0,03', '%'],
   ['AL RAJHI BAN',
    'KING & INV',
    'NL0013267909',
    '17.797.732,47',
    '0,04',
    '%'],
   ['AL RAJHI FOR', 'COPR INS', 'SA0007879113', '2.289.537,83', '0,01', '%'],
   ['ALBEMARLE C', 'ORP', 'SA12A0540J14', '6.415.226,32', '0,02', '%'],
   ['ALBERTSONS', 'COMPANIES A', 'US0126531013', '4.185.156,63', '0,01', '%'],
   ['ALCHIP TECH', 'NOLOGIES', 'US0130911037', '2.849.839,34', '0,01', '%'],
   ['ALCON', '', 'KYG022421088', '26.511.367,44', '0,06', '%'],
   ['ALDAR PROPE', 'RTIES', 'CH0432492467', '5.653.694,22', '0,01', '%'],
   ['ALEXANDRIA R',
    'EAL ESTATE',
    'AEA002001013',
    '9.568.100,62',
    '0,02',
    '%']]],
 [[['ALIBABA GRP HLDG (HK)', 'SE0000695876', '92.405.341,23', '0,23', '%'],
   ['ALIGN TECHNOLOGY', 'KYG017191142', '7.024.256,74', '0,02', '%'],
   ['ALIMENTATION COUCHE', 'US0162551016', '22.275.440,81', '0,05', '%'],
   ['ALINMA BANK', 'CA01626P1484', '4.193.570,92', '0,01', '%'],
   ['ALLEGION', 'SA122050HV19', '7.656.198,08', '0,02', '%'],
   ['ALLIANZ', 'IE00BFRT3W74', '101.224.088,34', '0,25', '%'],
   ['ALLSTATE CORP', 'DE0008404005', '34.820.325,88', '0,09', '%'],
   ['ALLY FINANCIAL', 'US0200021014', '5.201.468,28', '0,01', '%'],
   ['ALMARAI CO', 'US02005N1000', '3.117.267,28', '0,01', '%'],
   ['ALNYLAM PHARMACEUTICALS', 'SA000A0ETHT1', '20.741.921,97', '0,05', '%'],
   ['ALPHABET A', 'US02043Q1076', '569.553.183,07', '1,39', '%'],
   ['ALPHABET C', 'US02079K3059', '486.949.144,67', '1,19', '%'],
   ['ALSTOM', 'US02079K1079', '5.023.785,85', '0,01', '%'],
   ['ALTAGAS', 'FR0010220475', '3.857.313,06', '0,01', '%'],
   ['ALTEOGEN', 'CA0213611001', '3.112.514,21', '0,01', '%'],
   ['AMADEUS IT GROUP A', 'KR7196170005', '18.982.340,31', '0,05', '%'],
   ['AMAZON.COM', 'ES0109067019', '1.130.902.275,54', '2,76', '%'],
   ['AMCOR', 'US0231351067', '8.023.246,36', '0,02', '%'],
   ['AMEREN CORPORATION', 'JE00BJ1F3079', '8.018.143,47', '0,02', '%'],
   ['AMERICA MOVIL B', 'US0235865062', '6.808.077,95', '0,02', '%'],
   ['AMERICAN ELECTRIC POWER', 'US0236081024', '15.275.765,76', '0,04', '%']]],
 [[['AMERICAN FINANCIAL GROUP', 'US0255371017', '7.031.126,36', '0,02', '%'],
   ['AMERICAN HOMES 4 RENT A', 'US0258161092', '8.736.507,60', '0,02', '%'],
   ['AMERICAN INTL GROUP', 'US0259321042', '35.396.984,15', '0,09', '%'],
   ['AMERICAN TOWER CORP', 'US02665T3068', '61.433.898,66', '0,15', '%'],
   ['AMERICAN WATER WORKS CO', 'US0268747849', '21.163.060,43', '0,05', '%'],
   ['AMERIPRISE FINANCIAL', 'US03027X1000', '34.027.814,78', '0,08', '%'],
   ['AMETEK', 'US0304201033', '25.446.416,29', '0,06', '%'],
   ['AMGEN', 'US03076C1062', '106.655.147,46', '0,26', '%'],
   ['AMPHENOL CORP', 'US0311001004', '45.955.598,63', '0,11', '%'],
   ['AMUNDI', 'US0311621009', '8.624.692,34', '0,02', '%'],
   ['ANALOG DEVICES', 'US0320951017', '61.559.408,86', '0,15', '%'],
   ['ANGLO AMERICAN', 'FR0004125920', '25.485.417,75', '0,06', '%'],
   ['ANGLO AMERICAN PLATINUM', 'US0326541051', '1.959.951,13', '0,00', '%'],
   ['ANGLOGOLD ASHANTI', 'ZAE000013181', '6.646.369,78', '0,02', '%'],
   ['ANHEUSER-BUSCH INBEV', 'GB00B1XZS820', '32.060.780,76', '0,08', '%'],
   ['ANNALY CAPITAL MGMT', 'GB00BRXH2664', '4.491.600,86', '0,01', '%'],
   ['ANSYS', 'BE0974293251', '15.632.636,49', '0,04', '%'],
   ['ANTA SPORTS PRODUCTS', 'US0357108390', '5.504.635,36', '0,01', '%'],
   ['ANTOFAGASTA', 'US03662Q1058', '6.048.721,61', '0,01', '%'],
   ['ANZ GROUP HOLDINGS', 'KYG040111059', '37.650.838,16', '0,09', '%'],
   ['AON PLC A', 'GB0000456144', '47.732.444,64', '0,12', '%']]],
 [[['AP MOLLER MAERSK B', 'IE00BLP1HW54', '5.525.084,99', '0,01', '%'],
   ['APA GROUP', 'DK0010244425', '3.063.133,01', '0,01', '%'],
   ['APOLLO GLOBAL MGMT A', 'DK0010244508', '34.601.243,20', '0,08', '%'],
   ['APOLLO HOSPITALS', 'AU000000APA1', '6.023.134,65', '0,01', '%'],
   ['APPLE', 'US03769M1062', '2.120.228.282,96', '5,18', '%'],
   ['APPLIED MATERIALS', 'INE437A01024', '73.997.757,43', '0,18', '%'],
   ['APPLOVIN CORP A', 'US0378331005', '34.052.048,30', '0,08', '%'],
   ['APTIV PLC', 'US0382221051', '14.329.360,00', '0,04', '%'],
   ['ARAB NATIONAL BANK', 'US03831W1080', '3.438.648,96', '0,01', '%'],
   ['ARC RESOURCES', 'JE00BTDN8H13', '7.225.391,23', '0,02', '%'],
   ['ARCELORMITTAL A', 'SA0007879105', '3.339.422,01', '0,01', '%'],
   ['ARCH CAPITAL GROUP', 'CA00208D4084', '21.103.029,58', '0,05', '%'],
   ['ARCHER-DANIELS-MIDLAND', 'LU1598757687', '13.501.363,83', '0,03', '%'],
   ['ARES MANAGEMENT CORP', 'BMG0450A1053', '17.944.114,01', '0,04', '%'],
   ['ARGEN X', 'US0394831020', '20.379.761,42', '0,05', '%'],
   ['ARISTA NETWORKS', 'US03990B1017', '53.145.427,91', '0,13', '%'],
   ['ARISTOCRAT LEISURE', 'NL0010832176', '13.312.223,12', '0,03', '%'],
   ['ARKEMA', 'US0404132054', '4.706.027,12', '0,01', '%'],
   ['ASAHI GROUP HOLDINGS', 'AU000000ALL7', '9.740.383,22', '0,02', '%'],
   ['ASAHI KASEI CORP', 'FR0010313833', '5.435.328,13', '0,01', '%'],
   ['ASE TECHNOLOGY HOLDING', 'US3635761097', '5.855.330,45', '0,01', '%']]],
 [[['ASHTEAD GROUP', 'JP3111200006', '12.821.101,08', '0,03', '%'],
   ['ASIA VITAL COMPONENTS', 'TW0003711008', '1.699.918,76', '0,00', '%'],
   ['ASIAN PAINTS', 'INE208A01029', '4.077.265,57', '0,01', '%'],
   ['ASICS CORP', 'GB0000536739', '10.472.942,25', '0,03', '%'],
   ['ASM INTERNATIONAL', 'TW0003017000', '12.399.632,09', '0,03', '%'],
   ['ASML HLDG', 'INE021A01026', '164.424.223,09', '0,40', '%'],
   ['ASR NEDERLAND', 'JP3118000003', '9.590.651,43', '0,02', '%'],
   ['ASSA ABLOY B', 'NL0000334118', '17.382.407,36', '0,04', '%'],
   ['ASSICURAZIONI GENERALI', 'NL0010273215', '26.620.513,63', '0,07', '%'],
   ['ASSOCIATED BRITISH FOODS', 'US29109X1063', '1.539.988,25', '0,00', '%'],
   ['ASSURANT', 'NL0011872643', '8.694.972,08', '0,02', '%'],
   ['ASTELLAS PHARMA', 'SE0007100581', '12.139.089,78', '0,03', '%'],
   ['ASTRAZENECA', 'IT0000062072', '145.536.118,07', '0,36', '%'],
   ['ASUSTEK COMPUTER', 'GB0006731235', '4.053.844,46', '0,01', '%'],
   ['ASX', 'US04621X1081', '2.030.058,21', '0,00', '%'],
   ['AT&T', 'JP3942400007', '122.622.704,58', '0,30', '%'],
   ['ATLAS COPCO A', 'GB0009895292', '28.239.144,36', '0,07', '%'],
   ['ATLAS COPCO B', 'TW0002357001', '10.725.040,49', '0,03', '%'],
   ['ATLASSIAN (US)', 'AU000000ASX7', '20.390.392,18', '0,05', '%'],
   ['ATMOS ENERGY CORP', 'US00206R1023', '19.691.483,64', '0,05', '%'],
   ['AUCKLAND INTL AIRPORT', 'SE0017486889', '3.835.518,17', '0,01', '%']]],
 [[['AUTO TRADER GROUP', 'US0494681010', '5.093.349,87', '0,01', '%'],
   ['AUTODESK', 'US0495601058', '34.288.371,28', '0,08', '%'],
   ['AUTOMATIC DATA PROCESS', 'NZAIAE0002S6', '81.774.553,69', '0,20', '%'],
   ['AUTOZONE', 'TW0002409000', '39.184.549,51', '0,10', '%'],
   ['AVALONBAY COMMUNITIES', 'GB00BVYVFW23', '24.813.950,04', '0,06', '%'],
   ['AVANTOR', 'US0527691069', '7.287.761,31', '0,02', '%'],
   ['AVENUE SUPERMARTS', 'US0530151036', '3.242.394,16', '0,01', '%'],
   ['AVERY DENNISON CORP', 'US0533321024', '10.097.746,66', '0,02', '%'],
   ['AVIVA', 'US0534841012', '13.744.839,39', '0,03', '%'],
   ['AVOLTA', 'US05352A1007', '650.866,55', '0,00', '%'],
   ['AXA', 'INE192R01011', '54.197.477,97', '0,13', '%'],
   ['AXIS BANK', 'US0536111091', '12.298.643,40', '0,03', '%'],
   ['AXON ENTERPRISE', 'GB00BPQY8M80', '22.209.565,11', '0,05', '%'],
   ['AYALA CORP', 'CH0023405456', '1.973.487,28', '0,00', '%'],
   ['AZRIELI GROUP', 'FR0000120628', '4.448.631,28', '0,01', '%'],
   ['B3', 'INE238A01034', '7.199.336,95', '0,02', '%'],
   ['BAIDU (HK)', 'US05464C1018', '10.798.447,22', '0,03', '%'],
   ['BAJAJ AUTO', 'PHY0486V1154', '2.112.435,29', '0,01', '%'],
   ['BAJAJ FINANCE', 'IL0011194789', '10.111.353,62', '0,02', '%'],
   ['BAJAJ FINSERV', 'BRB3SAACNOR6', '3.938.202,99', '0,01', '%'],
   ['BAKER HUGHES CO', 'KYG070341048', '31.280.745,61', '0,08', '%']]],
 [[['BALOISE HOLDI', 'NG', 'INE296A01024', '1.726.212,74', '0,00', '%'],
   ['BANCO BPM', '', 'INE918I01026', '7.023.647,05', '0,02', '%'],
   ['BANCO BRADES', 'CO ON', 'US05722G1004', '4.852.658,39', '0,01', '%'],
   ['BANCO BRADES', 'CO PN', 'US0584981064', '3.498.421,06', '0,01', '%'],
   ['BANCO BTG PAC', 'TUAL', 'CH0012410517', '3.441.607,04', '0,01', '%'],
   ['BANCO SABADE', 'LL', 'ES0113211835', '8.095.815,92', '0,02', '%'],
   ['BANCO SANTAN', 'DER', 'IT0005218380', '58.183.356,56', '0,14', '%'],
   ['BANCOLOMBIA', 'PREF', 'BRBBDCACNOR1', '2.934.114,80', '0,01', '%'],
   ['BANDAI NAMCO', 'HOLDINGS', 'BRBBDCACNPR8', '11.902.473,98', '0,03', '%'],
   ['BANGKOK DUSIT',
    'MED SERVI-NVDR',
    'BRBPACUNT006',
    '3.284.270,65',
    '0,01',
    '%'],
   ['BANK ALBILAD', '', 'ES0113860A34', '2.616.921,97', '0,01', '%'],
   ['BANK CENTRAL', 'ASIA', 'CLP1506A1070', '10.896.203,99', '0,03', '%'],
   ['BANK MANDIRI', '', 'ES0113900J37', '3.819.627,16', '0,01', '%'],
   ['BANK MONTREA', 'L', 'COB07PA00086', '47.331.586,30', '0,12', '%'],
   ['BANK NEW YORK', 'MELLON', 'JP3778630008', '43.288.432,91', '0,11', '%'],
   ['BANK NOVA SCO', 'TIA', 'TH0264010R10', '41.405.599,74', '0,10', '%'],
   ['BANK OF AMERI', 'CA CORP', 'SA000A0D9HK3', '183.285.409,53', '0,45', '%'],
   ['BANK OF CHINA', 'H', 'ID1000109507', '17.119.859,53', '0,04', '%'],
   ['BANK OF COMM', 'U A (HK-C)', 'ID1000095003', '3.542.106,49', '0,01', '%'],
   ['BANK OF IRELAN', 'D GROUP', 'US0605051046', '7.174.228,22', '0,02', '%'],
   ['BANK OF PHIL IS', 'LANDS', 'CNE1000001Z5', '7.285.780,08', '0,02', '%']]],
 [[['BANQUE CANTONALE VAUDOIS', 'IE00BD1RP616', '687.815,92', '0,00', '%'],
   ['BANQUE SAUDI FRANSI', 'CA0636711016', '3.150.775,39', '0,01', '%'],
   ['BARCLAYS', 'US0640581007', '32.115.999,66', '0,08', '%'],
   ['BARRATT REDROW', 'CA0641491075', '7.785.747,03', '0,02', '%'],
   ['BARRY CALLEBAUT', 'PHY0967S1694', '466.602,19', '0,00', '%'],
   ['BARWA REAL ESTATE CO', 'ID1000118201', '2.183.260,03', '0,01', '%'],
   ['BAXTER INTERNATIONAL', 'CH0531751755', '11.869.272,38', '0,03', '%'],
   ['BAYER', 'SA0007879782', '13.617.499,02', '0,03', '%'],
   ['BBVA', 'GB0031348658', '43.663.205,89', '0,11', '%'],
   ['BCE INC', 'GB0000811801', '3.440.264,37', '0,01', '%'],
   ['BCO SANTANDER CHILE (NEW', 'CH0009002962', '6.944.108,89', '0,02', '%'],
   ['BE SEMICONDUCTOR IND', 'QA000A0KD6J5', '5.409.683,30', '0,01', '%'],
   ['BECTON DICKINSON', 'US0718131099', '41.843.566,38', '0,10', '%'],
   ['BEIERSDORF', 'DE000BAY0017', '5.451.669,32', '0,01', '%'],
   ['BEIGENE (HK)', 'DE0005190003', '6.713.000,26', '0,02', '%'],
   ['BEIJER REF B', 'DE0005190037', '2.975.280,10', '0,01', '%'],
   ['BENTLEY SYSTEMS B', 'CA05534B7604', '2.566.023,30', '0,01', '%'],
   ['BERKLEY (W.R.) CORP', 'NL0012866412', '14.152.667,20', '0,03', '%'],
   ['BEST BUY CO', 'US0758871091', '13.291.657,85', '0,03', '%'],
   ['BHARAT ELECTRONICS', 'DE0005200000', '5.227.305,79', '0,01', '%'],
   ['BHARAT PETROLEUM CORP', 'KYG1146Y1017', '2.014.295,97', '0,00', '%']]],
 [[['BID CORPORATION', 'US08265T2087', '3.101.176,42', '0,01', '%'],
   ['BIDVEST GROUP', 'US0865161014', '2.661.251,79', '0,01', '%'],
   ['BIM BIRLESIK MAGAZALAR', 'INE263A01024', '2.182.715,14', '0,01', '%'],
   ['BIOGEN', 'INE029A01011', '13.580.314,83', '0,03', '%'],
   ['BIOMARIN PHARMACEUTICAL', 'INE397D01024', '8.779.914,76', '0,02', '%'],
   ['BIOMERIEUX', 'ZAE000216537', '5.208.279,18', '0,01', '%'],
   ['BIO-RAD LABORATORIES A', 'ZAE000117321', '2.627.587,73', '0,01', '%'],
   ['BIO-TECHNE CORP', 'TREBIMM00018', '6.048.174,70', '0,01', '%'],
   ['BKW', 'US09062X1037', '6.167.067,93', '0,02', '%'],
   ['BLACKROCK', 'US09061G1013', '91.642.870,34', '0,22', '%'],
   ['BLACKSTONE GROUP', 'FR0013280286', '63.171.136,64', '0,15', '%'],
   ['BLOCK', 'US0905722072', '17.753.009,84', '0,04', '%'],
   ['BLUESCOPE STEEL', 'US09073M1045', '588.080,08', '0,00', '%'],
   ['BMW STAMM', 'CH0130293662', '14.646.676,78', '0,04', '%'],
   ['BMW VORZUG', 'US09290D1019', '5.611.723,81', '0,01', '%'],
   ['BNP PARIBAS', 'US09260D1072', '55.504.887,17', '0,14', '%'],
   ['BOC HONG KONG HOLDINGS', 'US8522341036', '10.118.357,94', '0,02', '%'],
   ['BOLIDEN', 'AU000000BSL0', '9.453.535,14', '0,02', '%'],
   ['BOLLORE', 'FR0000131104', '1.411.060,58', '0,00', '%'],
   ['BOOKING HOLDINGS', 'HK2388011192', '98.001.030,41', '0,24', '%'],
   ['BOOZ ALLEN HAMILTON A', 'SE0020050417', '8.006.717,13', '0,02', '%']]],
 [[['BOSTON SCIENTIFIC CORP', 'US09857L1089', '98.373.746,13', '0,24', '%'],
   ['BOUYGUES', 'US0995021062', '2.271.185,77', '0,01', '%'],
   ['BP', 'KYG126521064', '54.993.388,79', '0,13', '%'],
   ['BPER BANCA', 'US1011211018', '2.266.426,88', '0,01', '%'],
   ['BRAMBLES', 'US1011371077', '20.108.966,94', '0,05', '%'],
   ['BRENNTAG', 'FR0000120503', '6.567.061,85', '0,02', '%'],
   ['BRIDGESTONE CORP', 'GB0007980591', '16.570.280,61', '0,04', '%'],
   ['BRISTOL-MYERS SQUIBB CO', 'IT0000066123', '90.300.646,27', '0,22', '%'],
   ['BRITANNIA INDUSTRIES', 'AU000000BXB1', '2.779.755,98', '0,01', '%'],
   ['BROADCOM', 'DE000A1DAHH0', '471.000.183,16', '1,15', '%'],
   ['BROADRIDGE FINANCIAL', 'JP3830800003', '16.107.944,86', '0,04', '%'],
   ['BROOKFIELD ASSET MAN LTD', 'US1101221083', '9.581.353,59', '0,02', '%'],
   ['BROOKFIELD CORP A', 'INE216A01030', '44.580.792,39', '0,11', '%'],
   ['BROOKFIELD RENEWABLE', 'US11135F1012', '1.902.621,16', '0,00', '%'],
   ['BROWN & BROWN', 'US11133T1034', '19.114.457,55', '0,05', '%'],
   ['BROWN-FORMAN CORP B', 'CA1130041058', '1.099.630,67', '0,00', '%'],
   ['BT GROUP', 'CA11271J1075', '9.404.685,59', '0,02', '%'],
   ['BUILDERS FIRSTSOURCE', 'CA11285B1085', '8.759.523,47', '0,02', '%'],
   ['BUMRUNGRAD HOSPITAL PCL-NVDR',
    'US1152361010',
    '1.677.854,72',
    '0,00',
    '%'],
   ['BUNGE GLOBAL', 'US1156372096', '10.619.001,57', '0,03', '%'],
   ['BUNZL', 'GB0030913577', '8.872.213,94', '0,02', '%']]],
 [[['BUREAU VERITAS SA', 'TH0168010R13', '8.326.710,31', '0,02', '%'],
   ['BURLINGTON STORES', 'CH1300646267', '8.821.300,13', '0,02', '%'],
   ['BXP', 'GB00B0744B38', '8.806.017,37', '0,02', '%'],
   ['BYD CO A (HK-C)', 'SA1210540914', '8.319.593,85', '0,02', '%'],
   ['BYD CO H', 'FR0006174348', '11.298.415,58', '0,03', '%'],
   ['CADENCE DESIGN SYSTEMS', 'US1220171060', '44.522.261,68', '0,11', '%'],
   ['CAE', 'CNE100001526', '7.861.080,91', '0,02', '%'],
   ['CAIXABANK', 'CNE100000296', '18.717.084,94', '0,05', '%'],
   ['CAMDEN PROPERTY TRUST', 'US12541W2098', '7.871.651,57', '0,02', '%'],
   ['CAMECO CORP', 'US1273871087', '11.992.710,61', '0,03', '%'],
   ['CANADIAN IMPERIAL BANK', 'CA1247651088', '37.120.458,35', '0,09', '%'],
   ['CANADIAN NATL RAILWAY', 'ES0140609019', '32.084.536,90', '0,08', '%'],
   ['CANADIAN TIRE CORP A', 'US1331311027', '1.729.726,76', '0,00', '%'],
   ['CANADIAN UTILITIES A', 'CA13321L1085', '7.523.232,57', '0,02', '%'],
   ['CANON INC', 'US1344291091', '16.776.646,66', '0,04', '%'],
   ['CAPCOM CO', 'CA1360691010', '5.550.625,61', '0,01', '%'],
   ['CAPGEMINI', 'CA1363751027', '15.407.840,01', '0,04', '%'],
   ['CAPITAL ONE FINANCIAL', 'CA13646K1084', '43.185.682,63', '0,11', '%'],
   ['CAPITALAND ASCENDAS REIT', 'CA1366812024', '1.281.435,38', '0,00', '%'],
   ['CAPITALAND INTEGRATED', 'CA1367178326', '8.244.069,65', '0,02', '%'],
   ['CAPITALAND INVESTMENT', 'JP3242800005', '4.344.949,77', '0,01', '%']]],
 [[['CAR GROUP', 'FR0000125338', '5.160.033,86', '0,01', '%'],
   ['CARDINAL HEALTH', 'US14040H1059', '24.945.448,81', '0,06', '%'],
   ['CARLISLE COS', 'SG1M77906915', '9.385.749,83', '0,02', '%'],
   ['CARLSBERG B', 'SG1M51904654', '10.947.724,78', '0,03', '%'],
   ['CARLYLE GROUP', 'SGXE62145532', '5.967.666,17', '0,01', '%'],
   ['CARMAX', 'ZAE000035861', '8.816.831,50', '0,02', '%'],
   ['CARNIVAL CORP (US)', 'US14149Y1082', '7.696.419,76', '0,02', '%'],
   ['CARREFOUR', 'US1423391002', '7.976.236,53', '0,02', '%'],
   ['CARRIER GLOBAL', 'DK0010181759', '37.621.715,66', '0,09', '%'],
   ['CARVANA A', 'US14316J1088', '14.001.521,96', '0,03', '%'],
   ['CATHAY FINANCIAL HOLDING', 'US1431301027', '5.665.147,78', '0,01', '%'],
   ['CBOE GLOBAL MARKETS', 'PA1436583006', '14.194.401,54', '0,03', '%'],
   ['CBRE GROUP', 'FR0000120172', '28.774.170,25', '0,07', '%'],
   ['CCL INDUSTRIES B', 'US14448C1045', '5.047.148,63', '0,01', '%'],

In [80]:
tabs2 = sum(tabs, [])
tabs3 = sum(tabs2, [])
tabs3

[['3I GROUP', 'US88557W1018', '29.605.115,44', '0,07', '%'],
 ['AAC TECHNOLOGIES (CN)', 'KYG2953R1149', '2.655.026,62', '0,01', '%'],
 ['3M CO', 'GB00B1YW4409', '49.450.996,40', '0,12', '%'],
 ['ABB INDIA', 'US88579Y1010', '2.652.723,48', '0,01', '%'],
 ['ABB LTD', 'KYG2953R1149', '53.407.655,61', '0,13', '%'],
 ['ABBOTT LABORATORIES', 'INE117A01022', '138.627.032,19', '0,34', '%'],
 ['ABBVIE', 'CH0012221716', '234.088.585,31', '0,57', '%'],
 ['ABN AMRO BANK A', 'US0028241000', '9.684.515,34', '0,02', '%'],
 ['ABSA GROUP', 'US00287Y1091', '3.307.828,00', '0,01', '%'],
 ['ABU DHABI COMM BANK', 'NL0011540547', '8.921.788,71', '0,02', '%'],
 ['ABU DHABI NATL OIL CO', 'ZAE000255915', '4.752.599,36', '0,01', '%'],
 ['ACCENTURE A', 'AEA000201011', '124.753.863,37', '0,30', '%'],
 ['ACCIONA', 'AEA006101017', '188.359,26', '0,00', '%'],
 ['ACCOR', 'IE00B4BNMY34', '4.838.817,36', '0,01', '%'],
 ['ACCTON TECHNOLOGY CORP', 'ES0125220311', '2.755.815,44', '0,01', '%'],
 ['ACER', 'FR0000120404', '3.004.846,89', '0,01', '%'],
 ['ACS ACTIV CONST Y SVCS', 'TW0002345006', '2.219.996,65', '0,01', '%'],
 ['ADANI ENTERPRISES', 'TW0002353000', '1.841.928,36', '0,00', '%'],
 ['ADANI PORTS AND SEZ', 'ES0167050915', '3.388.746,48', '0,01', '%'],
 ['ADDTECH B', 'INE423A01024', '5.780.304,51', '0,01', '%'],
 ['ADIDAS', 'INE742F01042', '22.863.541,39', '0,06', '%'],
 ['ADNOC DRILLING COMPANY', 'DE000A1EWWW0', '4.283.287,49', '0,01', '%'],
 ['ADOBE', 'GB00B02J6398', '108.629.735,16', '0,27', '%'],
 ['ADP', 'AEA007301012', '1.042.973,97', '0,00', '%'],
 ['ADVANCED INFO SERVICE-NVDR', 'US00724F1012', '3.331.197,52', '0,01', '%'],
 ['ADVANCED MICRO DEVICES', 'FR0010340141', '116.363.442,50', '0,28', '%'],
 ['ADVANTEST CORP', 'TH0268010R11', '22.717.726,53', '0,06', '%'],
 ['ADYEN NV', 'US0079031078', '18.912.755,29', '0,05', '%'],
 ['AECOM', 'JP3122400009', '8.188.891,77', '0,02', '%'],
 ['AEGON', 'NL0012969182', '9.200.334,70', '0,02', '%'],
 ['AENA', 'US00766T1007', '16.875.532,53', '0,04', '%'],
 ['AEON CO', 'BMG0112X1056', '11.517.698,26', '0,03', '%'],
 ['AERCAP HOLDINGS NV', 'ES0105046009', '18.558.075,83', '0,05', '%'],
 ['AFLAC', 'JP3388200002', '37.575.282,52', '0,09', '%'],
 ['AGC', 'NL0000687663', '3.980.231,18', '0,01', '%'],
 ['AGEAS', 'US0010551028', '3.541.409,54', '0,01', '%'],
 ['AGILENT TECHNOLOGIES', 'JP3112000009', '26.161.264,32', '0,06', '%'],
 ['AGNICO EAGLE MINES', 'BE0974264930', '40.416.110,44', '0,10', '%'],
 ['AGRI BANK OF CHINA H', 'US00846U1016', '2.849.995,78', '0,01', '%'],
 ['AGRI BANK OF CN A (HK-C)', 'CA0084741085', '4.130.870,83', '0,01', '%'],
 ['AHOLD DELHAIZE', 'CNE100000RJ0', '18.326.117,57', '0,04', '%'],
 ['AIA GROUP', 'CNE100000Q43', '54.804.772,85', '0,13', '%'],
 ['AIR CANADA V', 'V', 'IE00BF0L3536', '2.400.373,98', '0,01', '%'],
 ['AIR LIQUIDE', '', 'CA0089118776', '47.400.016,68', '0,12', '%'],
 ['AIR PRODUCT',
  'S & CHEMICALS',
  'FR0000120073',
  '35.998.524,75',
  '0,09',
  '%'],
 ['AIRBNB A', '', 'US0091581068', '30.514.520,39', '0,07', '%'],
 ['AIRPORTS OF',
  'THAILAND PCL-FOR',
  'US0090661010',
  '3.287.054,70',
  '0,01',
  '%'],
 ['AIRTAC INTER', 'NATIONAL', 'TH0765010Z16', '2.074.350,21', '0,01', '%'],
 ['AISIN CORP', '', 'KYG014081064', '1.574.163,77', '0,00', '%'],
 ['AJINOMOTO C', 'O', 'JP3102000001', '12.407.098,27', '0,03', '%'],
 ['AKAMAI TECH', 'NOLOGIES', 'JP3119600009', '8.403.771,49', '0,02', '%'],
 ['AKBANK', '', 'US00971T1016', '1.596.557,50', '0,00', '%'],
 ['AKER BP', '', 'TRAAKBNK91N6', '10.736.347,09', '0,03', '%'],
 ['AKESO (CN)', '', 'NO0010345853', '2.570.471,64', '0,01', '%'],
 ['AKZO NOBEL', '', 'KYG0146B1032', '11.288.852,30', '0,03', '%'],
 ['AL RAJHI BAN', 'KING & INV', 'NL0013267909', '17.797.732,47', '0,04', '%'],
 ['AL RAJHI FOR', 'COPR INS', 'SA0007879113', '2.289.537,83', '0,01', '%'],
 ['ALBEMARLE C', 'ORP', 'SA12A0540J14', '6.415.226,32', '0,02', '%'],
 ['ALBERTSONS', 'COMPANIES A', 'US0126531013', '4.185.156,63', '0,01', '%'],
 ['ALCHIP TECH', 'NOLOGIES', 'US0130911037', '2.849.839,34', '0,01', '%'],
 ['ALCON', '', 'KYG022421088', '26.511.367,44', '0,06', '%'],
 ['ALDAR PROPE', 'RTIES', 'CH0432492467', '5.653.694,22', '0,01', '%'],
 ['ALEXANDRIA R', 'EAL ESTATE', 'AEA002001013', '9.568.100,62', '0,02', '%'],
 ['ALIBABA GRP HLDG (HK)', 'SE0000695876', '92.405.341,23', '0,23', '%'],
 ['ALIGN TECHNOLOGY', 'KYG017191142', '7.024.256,74', '0,02', '%'],
 ['ALIMENTATION COUCHE', 'US0162551016', '22.275.440,81', '0,05', '%'],
 ['ALINMA BANK', 'CA01626P1484', '4.193.570,92', '0,01', '%'],
 ['ALLEGION', 'SA122050HV19', '7.656.198,08', '0,02', '%'],
 ['ALLIANZ', 'IE00BFRT3W74', '101.224.088,34', '0,25', '%'],
 ['ALLSTATE CORP', 'DE0008404005', '34.820.325,88', '0,09', '%'],
 ['ALLY FINANCIAL', 'US0200021014', '5.201.468,28', '0,01', '%'],
 ['ALMARAI CO', 'US02005N1000', '3.117.267,28', '0,01', '%'],
 ['ALNYLAM PHARMACEUTICALS', 'SA000A0ETHT1', '20.741.921,97', '0,05', '%'],
 ['ALPHABET A', 'US02043Q1076', '569.553.183,07', '1,39', '%'],
 ['ALPHABET C', 'US02079K3059', '486.949.144,67', '1,19', '%'],
 ['ALSTOM', 'US02079K1079', '5.023.785,85', '0,01', '%'],
 ['ALTAGAS', 'FR0010220475', '3.857.313,06', '0,01', '%'],
 ['ALTEOGEN', 'CA0213611001', '3.112.514,21', '0,01', '%'],
 ['AMADEUS IT GROUP A', 'KR7196170005', '18.982.340,31', '0,05', '%'],
 ['AMAZON.COM', 'ES0109067019', '1.130.902.275,54', '2,76', '%'],
 ['AMCOR', 'US0231351067', '8.023.246,36', '0,02', '%'],
 ['AMEREN CORPORATION', 'JE00BJ1F3079', '8.018.143,47', '0,02', '%'],
 ['AMERICA MOVIL B', 'US0235865062', '6.808.077,95', '0,02', '%'],
 ['AMERICAN ELECTRIC POWER', 'US0236081024', '15.275.765,76', '0,04', '%'],
 ['AMERICAN FINANCIAL GROUP', 'US0255371017', '7.031.126,36', '0,02', '%'],
 ['AMERICAN HOMES 4 RENT A', 'US0258161092', '8.736.507,60', '0,02', '%'],
 ['AMERICAN INTL GROUP', 'US0259321042', '35.396.984,15', '0,09', '%'],
 ['AMERICAN TOWER CORP', 'US02665T3068', '61.433.898,66', '0,15', '%'],
 ['AMERICAN WATER WORKS CO', 'US0268747849', '21.163.060,43', '0,05', '%'],
 ['AMERIPRISE FINANCIAL', 'US03027X1000', '34.027.814,78', '0,08', '%'],
 ['AMETEK', 'US0304201033', '25.446.416,29', '0,06', '%'],
 ['AMGEN', 'US03076C1062', '106.655.147,46', '0,26', '%'],
 ['AMPHENOL CORP', 'US0311001004', '45.955.598,63', '0,11', '%'],
 ['AMUNDI', 'US0311621009', '8.624.692,34', '0,02', '%'],
 ['ANALOG DEVICES', 'US0320951017', '61.559.408,86', '0,15', '%'],
 ['ANGLO AMERICAN', 'FR0004125920', '25.485.417,75', '0,06', '%'],
 ['ANGLO AMERICAN PLATINUM', 'US0326541051', '1.959.951,13', '0,00', '%'],
 ['ANGLOGOLD ASHANTI', 'ZAE000013181', '6.646.369,78', '0,02', '%'],
 ['ANHEUSER-BUSCH INBEV', 'GB00B1XZS820', '32.060.780,76', '0,08', '%'],
 ['ANNALY CAPITAL MGMT', 'GB00BRXH2664', '4.491.600,86', '0,01', '%'],
 ['ANSYS', 'BE0974293251', '15.632.636,49', '0,04', '%'],
 ['ANTA SPORTS PRODUCTS', 'US0357108390', '5.504.635,36', '0,01', '%'],
 ['ANTOFAGASTA', 'US03662Q1058', '6.048.721,61', '0,01', '%'],
 ['ANZ GROUP HOLDINGS', 'KYG040111059', '37.650.838,16', '0,09', '%'],
 ['AON PLC A', 'GB0000456144', '47.732.444,64', '0,12', '%'],
 ['AP MOLLER MAERSK B', 'IE00BLP1HW54', '5.525.084,99', '0,01', '%'],
 ['APA GROUP', 'DK0010244425', '3.063.133,01', '0,01', '%'],
 ['APOLLO GLOBAL MGMT A', 'DK0010244508', '34.601.243,20', '0,08', '%'],
 ['APOLLO HOSPITALS', 'AU000000APA1', '6.023.134,65', '0,01', '%'],
 ['APPLE', 'US03769M1062', '2.120.228.282,96', '5,18', '%'],
 ['APPLIED MATERIALS', 'INE437A01024', '73.997.757,43', '0,18', '%'],
 ['APPLOVIN CORP A', 'US0378331005', '34.052.048,30', '0,08', '%'],
 ['APTIV PLC', 'US0382221051', '14.329.360,00', '0,04', '%'],
 ['ARAB NATIONAL BANK', 'US03831W1080', '3.438.648,96', '0,01', '%'],
 ['ARC RESOURCES', 'JE00BTDN8H13', '7.225.391,23', '0,02', '%'],
 ['ARCELORMITTAL A', 'SA0007879105', '3.339.422,01', '0,01', '%'],
 ['ARCH CAPITAL GROUP', 'CA00208D4084', '21.103.029,58', '0,05', '%'],
 ['ARCHER-DANIELS-MIDLAND', 'LU1598757687', '13.501.363,83', '0,03', '%'],
 ['ARES MANAGEMENT CORP', 'BMG0450A1053', '17.944.114,01', '0,04', '%'],
 ['ARGEN X', 'US0394831020', '20.379.761,42', '0,05', '%'],
 ['ARISTA NETWORKS', 'US03990B1017', '53.145.427,91', '0,13', '%'],
 ['ARISTOCRAT LEISURE', 'NL0010832176', '13.312.223,12', '0,03', '%'],
 ['ARKEMA', 'US0404132054', '4.706.027,12', '0,01', '%'],
 ['ASAHI GROUP HOLDINGS', 'AU000000ALL7', '9.740.383,22', '0,02', '%'],
 ['ASAHI KASEI CORP', 'FR0010313833', '5.435.328,13', '0,01', '%'],
 ['ASE TECHNOLOGY HOLDING', 'US3635761097', '5.855.330,45', '0,01', '%'],
 ['ASHTEAD GROUP', 'JP3111200006', '12.821.101,08', '0,03', '%'],
 ['ASIA VITAL COMPONENTS', 'TW0003711008', '1.699.918,76', '0,00', '%'],
 ['ASIAN PAINTS', 'INE208A01029', '4.077.265,57', '0,01', '%'],
 ['ASICS CORP', 'GB0000536739', '10.472.942,25', '0,03', '%'],
 ['ASM INTERNATIONAL', 'TW0003017000', '12.399.632,09', '0,03', '%'],
 ['ASML HLDG', 'INE021A01026', '164.424.223,09', '0,40', '%'],
 ['ASR NEDERLAND', 'JP3118000003', '9.590.651,43', '0,02', '%'],
 ['ASSA ABLOY B', 'NL0000334118', '17.382.407,36', '0,04', '%'],
 ['ASSICURAZIONI GENERALI', 'NL0010273215', '26.620.513,63', '0,07', '%'],
 ['ASSOCIATED BRITISH FOODS', 'US29109X1063', '1.539.988,25', '0,00', '%'],
 ['ASSURANT', 'NL0011872643', '8.694.972,08', '0,02', '%'],
 ['ASTELLAS PHARMA', 'SE0007100581', '12.139.089,78', '0,03', '%'],
 ['ASTRAZENECA', 'IT0000062072', '145.536.118,07', '0,36', '%'],
 ['ASUSTEK COMPUTER', 'GB0006731235', '4.053.844,46', '0,01', '%'],
 ['ASX', 'US04621X1081', '2.030.058,21', '0,00', '%'],
 ['AT&T', 'JP3942400007', '122.622.704,58', '0,30', '%'],
 ['ATLAS COPCO A', 'GB0009895292', '28.239.144,36', '0,07', '%'],
 ['ATLAS COPCO B', 'TW0002357001', '10.725.040,49', '0,03', '%'],
 ['ATLASSIAN (US)', 'AU000000ASX7', '20.390.392,18', '0,05', '%'],
 ['ATMOS ENERGY CORP', 'US00206R1023', '19.691.483,64', '0,05', '%'],
 ['AUCKLAND INTL AIRPORT', 'SE0017486889', '3.835.518,17', '0,01', '%'],
 ['AUTO TRADER GROUP', 'US0494681010', '5.093.349,87', '0,01', '%'],
 ['AUTODESK', 'US0495601058', '34.288.371,28', '0,08', '%'],
 ['AUTOMATIC DATA PROCESS', 'NZAIAE0002S6', '81.774.553,69', '0,20', '%'],
 ['AUTOZONE', 'TW0002409000', '39.184.549,51', '0,10', '%'],
 ['AVALONBAY COMMUNITIES', 'GB00BVYVFW23', '24.813.950,04', '0,06', '%'],
 ['AVANTOR', 'US0527691069', '7.287.761,31', '0,02', '%'],
 ['AVENUE SUPERMARTS', 'US0530151036', '3.242.394,16', '0,01', '%'],
 ['AVERY DENNISON CORP', 'US0533321024', '10.097.746,66', '0,02', '%'],
 ['AVIVA', 'US0534841012', '13.744.839,39', '0,03', '%'],
 ['AVOLTA', 'US05352A1007', '650.866,55', '0,00', '%'],
 ['AXA', 'INE192R01011', '54.197.477,97', '0,13', '%'],
 ['AXIS BANK', 'US0536111091', '12.298.643,40', '0,03', '%'],
 ['AXON ENTERPRISE', 'GB00BPQY8M80', '22.209.565,11', '0,05', '%'],
 ['AYALA CORP', 'CH0023405456', '1.973.487,28', '0,00', '%'],
 ['AZRIELI GROUP', 'FR0000120628', '4.448.631,28', '0,01', '%'],
 ['B3', 'INE238A01034', '7.199.336,95', '0,02', '%'],
 ['BAIDU (HK)', 'US05464C1018', '10.798.447,22', '0,03', '%'],
 ['BAJAJ AUTO', 'PHY0486V1154', '2.112.435,29', '0,01', '%'],
 ['BAJAJ FINANCE', 'IL0011194789', '10.111.353,62', '0,02', '%'],
 ['BAJAJ FINSERV', 'BRB3SAACNOR6', '3.938.202,99', '0,01', '%'],
 ['BAKER HUGHES CO', 'KYG070341048', '31.280.745,61', '0,08', '%'],
 ['BALOISE HOLDI', 'NG', 'INE296A01024', '1.726.212,74', '0,00', '%'],
 ['BANCO BPM', '', 'INE918I01026', '7.023.647,05', '0,02', '%'],
 ['BANCO BRADES', 'CO ON', 'US05722G1004', '4.852.658,39', '0,01', '%'],
 ['BANCO BRADES', 'CO PN', 'US0584981064', '3.498.421,06', '0,01', '%'],
 ['BANCO BTG PAC', 'TUAL', 'CH0012410517', '3.441.607,04', '0,01', '%'],
 ['BANCO SABADE', 'LL', 'ES0113211835', '8.095.815,92', '0,02', '%'],
 ['BANCO SANTAN', 'DER', 'IT0005218380', '58.183.356,56', '0,14', '%'],
 ['BANCOLOMBIA', 'PREF', 'BRBBDCACNOR1', '2.934.114,80', '0,01', '%'],
 ['BANDAI NAMCO', 'HOLDINGS', 'BRBBDCACNPR8', '11.902.473,98', '0,03', '%'],
 ['BANGKOK DUSIT',
  'MED SERVI-NVDR',
  'BRBPACUNT006',
  '3.284.270,65',
  '0,01',
  '%'],
 ['BANK ALBILAD', '', 'ES0113860A34', '2.616.921,97', '0,01', '%'],
 ['BANK CENTRAL', 'ASIA', 'CLP1506A1070', '10.896.203,99', '0,03', '%'],
 ['BANK MANDIRI', '', 'ES0113900J37', '3.819.627,16', '0,01', '%'],
 ['BANK MONTREA', 'L', 'COB07PA00086', '47.331.586,30', '0,12', '%'],
 ['BANK NEW YORK', 'MELLON', 'JP3778630008', '43.288.432,91', '0,11', '%'],
 ['BANK NOVA SCO', 'TIA', 'TH0264010R10', '41.405.599,74', '0,10', '%'],
 ['BANK OF AMERI', 'CA CORP', 'SA000A0D9HK3', '183.285.409,53', '0,45', '%'],
 ['BANK OF CHINA', 'H', 'ID1000109507', '17.119.859,53', '0,04', '%'],
 ['BANK OF COMM', 'U A (HK-C)', 'ID1000095003', '3.542.106,49', '0,01', '%'],
 ['BANK OF IRELAN', 'D GROUP', 'US0605051046', '7.174.228,22', '0,02', '%'],
 ['BANK OF PHIL IS', 'LANDS', 'CNE1000001Z5', '7.285.780,08', '0,02', '%'],
 ['BANQUE CANTONALE VAUDOIS', 'IE00BD1RP616', '687.815,92', '0,00', '%'],
 ['BANQUE SAUDI FRANSI', 'CA0636711016', '3.150.775,39', '0,01', '%'],
 ['BARCLAYS', 'US0640581007', '32.115.999,66', '0,08', '%'],
 ['BARRATT REDROW', 'CA0641491075', '7.785.747,03', '0,02', '%'],
 ['BARRY CALLEBAUT', 'PHY0967S1694', '466.602,19', '0,00', '%'],
 ['BARWA REAL ESTATE CO', 'ID1000118201', '2.183.260,03', '0,01', '%'],
 ['BAXTER INTERNATIONAL', 'CH0531751755', '11.869.272,38', '0,03', '%'],
 ['BAYER', 'SA0007879782', '13.617.499,02', '0,03', '%'],
 ['BBVA', 'GB0031348658', '43.663.205,89', '0,11', '%'],
 ['BCE INC', 'GB0000811801', '3.440.264,37', '0,01', '%'],
 ['BCO SANTANDER CHILE (NEW', 'CH0009002962', '6.944.108,89', '0,02', '%'],
 ['BE SEMICONDUCTOR IND', 'QA000A0KD6J5', '5.409.683,30', '0,01', '%'],
 ['BECTON DICKINSON', 'US0718131099', '41.843.566,38', '0,10', '%'],
 ['BEIERSDORF', 'DE000BAY0017', '5.451.669,32', '0,01', '%'],
 ['BEIGENE (HK)', 'DE0005190003', '6.713.000,26', '0,02', '%'],
 ['BEIJER REF B', 'DE0005190037', '2.975.280,10', '0,01', '%'],
 ['BENTLEY SYSTEMS B', 'CA05534B7604', '2.566.023,30', '0,01', '%'],
 ['BERKLEY (W.R.) CORP', 'NL0012866412', '14.152.667,20', '0,03', '%'],
 ['BEST BUY CO', 'US0758871091', '13.291.657,85', '0,03', '%'],
 ['BHARAT ELECTRONICS', 'DE0005200000', '5.227.305,79', '0,01', '%'],
 ['BHARAT PETROLEUM CORP', 'KYG1146Y1017', '2.014.295,97', '0,00', '%'],
 ['BID CORPORATION', 'US08265T2087', '3.101.176,42', '0,01', '%'],
 ['BIDVEST GROUP', 'US0865161014', '2.661.251,79', '0,01', '%'],
 ['BIM BIRLESIK MAGAZALAR', 'INE263A01024', '2.182.715,14', '0,01', '%'],
 ['BIOGEN', 'INE029A01011', '13.580.314,83', '0,03', '%'],
 ['BIOMARIN PHARMACEUTICAL', 'INE397D01024', '8.779.914,76', '0,02', '%'],
 ['BIOMERIEUX', 'ZAE000216537', '5.208.279,18', '0,01', '%'],
 ['BIO-RAD LABORATORIES A', 'ZAE000117321', '2.627.587,73', '0,01', '%'],
 ['BIO-TECHNE CORP', 'TREBIMM00018', '6.048.174,70', '0,01', '%'],
 ['BKW', 'US09062X1037', '6.167.067,93', '0,02', '%'],
 ['BLACKROCK', 'US09061G1013', '91.642.870,34', '0,22', '%'],
 ['BLACKSTONE GROUP', 'FR0013280286', '63.171.136,64', '0,15', '%'],
 ['BLOCK', 'US0905722072', '17.753.009,84', '0,04', '%'],
 ['BLUESCOPE STEEL', 'US09073M1045', '588.080,08', '0,00', '%'],
 ['BMW STAMM', 'CH0130293662', '14.646.676,78', '0,04', '%'],
 ['BMW VORZUG', 'US09290D1019', '5.611.723,81', '0,01', '%'],
 ['BNP PARIBAS', 'US09260D1072', '55.504.887,17', '0,14', '%'],
 ['BOC HONG KONG HOLDINGS', 'US8522341036', '10.118.357,94', '0,02', '%'],
 ['BOLIDEN', 'AU000000BSL0', '9.453.535,14', '0,02', '%'],
 ['BOLLORE', 'FR0000131104', '1.411.060,58', '0,00', '%'],
 ['BOOKING HOLDINGS', 'HK2388011192', '98.001.030,41', '0,24', '%'],
 ['BOOZ ALLEN HAMILTON A', 'SE0020050417', '8.006.717,13', '0,02', '%'],
 ['BOSTON SCIENTIFIC CORP', 'US09857L1089', '98.373.746,13', '0,24', '%'],
 ['BOUYGUES', 'US0995021062', '2.271.185,77', '0,01', '%'],
 ['BP', 'KYG126521064', '54.993.388,79', '0,13', '%'],
 ['BPER BANCA', 'US1011211018', '2.266.426,88', '0,01', '%'],
 ['BRAMBLES', 'US1011371077', '20.108.966,94', '0,05', '%'],
 ['BRENNTAG', 'FR0000120503', '6.567.061,85', '0,02', '%'],
 ['BRIDGESTONE CORP', 'GB0007980591', '16.570.280,61', '0,04', '%'],
 ['BRISTOL-MYERS SQUIBB CO', 'IT0000066123', '90.300.646,27', '0,22', '%'],
 ['BRITANNIA INDUSTRIES', 'AU000000BXB1', '2.779.755,98', '0,01', '%'],
 ['BROADCOM', 'DE000A1DAHH0', '471.000.183,16', '1,15', '%'],
 ['BROADRIDGE FINANCIAL', 'JP3830800003', '16.107.944,86', '0,04', '%'],
 ['BROOKFIELD ASSET MAN LTD', 'US1101221083', '9.581.353,59', '0,02', '%'],
 ['BROOKFIELD CORP A', 'INE216A01030', '44.580.792,39', '0,11', '%'],
 ['BROOKFIELD RENEWABLE', 'US11135F1012', '1.902.621,16', '0,00', '%'],
 ['BROWN & BROWN', 'US11133T1034', '19.114.457,55', '0,05', '%'],
 ['BROWN-FORMAN CORP B', 'CA1130041058', '1.099.630,67', '0,00', '%'],
 ['BT GROUP', 'CA11271J1075', '9.404.685,59', '0,02', '%'],
 ['BUILDERS FIRSTSOURCE', 'CA11285B1085', '8.759.523,47', '0,02', '%'],
 ['BUMRUNGRAD HOSPITAL PCL-NVDR', 'US1152361010', '1.677.854,72', '0,00', '%'],
 ['BUNGE GLOBAL', 'US1156372096', '10.619.001,57', '0,03', '%'],
 ['BUNZL', 'GB0030913577', '8.872.213,94', '0,02', '%'],
 ['BUREAU VERITAS SA', 'TH0168010R13', '8.326.710,31', '0,02', '%'],
 ['BURLINGTON STORES', 'CH1300646267', '8.821.300,13', '0,02', '%'],
 ['BXP', 'GB00B0744B38', '8.806.017,37', '0,02', '%'],
 ['BYD CO A (HK-C)', 'SA1210540914', '8.319.593,85', '0,02', '%'],
 ['BYD CO H', 'FR0006174348', '11.298.415,58', '0,03', '%'],
 ['CADENCE DESIGN SYSTEMS', 'US1220171060', '44.522.261,68', '0,11', '%'],
 ['CAE', 'CNE100001526', '7.861.080,91', '0,02', '%'],
 ['CAIXABANK', 'CNE100000296', '18.717.084,94', '0,05', '%'],
 ['CAMDEN PROPERTY TRUST', 'US12541W2098', '7.871.651,57', '0,02', '%'],
 ['CAMECO CORP', 'US1273871087', '11.992.710,61', '0,03', '%'],
 ['CANADIAN IMPERIAL BANK', 'CA1247651088', '37.120.458,35', '0,09', '%'],
 ['CANADIAN NATL RAILWAY', 'ES0140609019', '32.084.536,90', '0,08', '%'],
 ['CANADIAN TIRE CORP A', 'US1331311027', '1.729.726,76', '0,00', '%'],
 ['CANADIAN UTILITIES A', 'CA13321L1085', '7.523.232,57', '0,02', '%'],
 ['CANON INC', 'US1344291091', '16.776.646,66', '0,04', '%'],
 ['CAPCOM CO', 'CA1360691010', '5.550.625,61', '0,01', '%'],
 ['CAPGEMINI', 'CA1363751027', '15.407.840,01', '0,04', '%'],
 ['CAPITAL ONE FINANCIAL', 'CA13646K1084', '43.185.682,63', '0,11', '%'],
 ['CAPITALAND ASCENDAS REIT', 'CA1366812024', '1.281.435,38', '0,00', '%'],
 ['CAPITALAND INTEGRATED', 'CA1367178326', '8.244.069,65', '0,02', '%'],
 ['CAPITALAND INVESTMENT', 'JP3242800005', '4.344.949,77', '0,01', '%'],
 ['CAR GROUP', 'FR0000125338', '5.160.033,86', '0,01', '%'],
 ['CARDINAL HEALTH', 'US14040H1059', '24.945.448,81', '0,06', '%'],
 ['CARLISLE COS', 'SG1M77906915', '9.385.749,83', '0,02', '%'],
 ['CARLSBERG B', 'SG1M51904654', '10.947.724,78', '0,03', '%'],
 ['CARLYLE GROUP', 'SGXE62145532', '5.967.666,17', '0,01', '%'],
 ['CARMAX', 'ZAE000035861', '8.816.831,50', '0,02', '%'],
 ['CARNIVAL CORP (US)', 'US14149Y1082', '7.696.419,76', '0,02', '%'],
 ['CARREFOUR', 'US1423391002', '7.976.236,53', '0,02', '%'],
 ['CARRIER GLOBAL', 'DK0010181759', '37.621.715,66', '0,09', '%'],
 ['CARVANA A', 'US14316J1088', '14.001.521,96', '0,03', '%'],
 ['CATHAY FINANCIAL HOLDING', 'US1431301027', '5.665.147,78', '0,01', '%'],
 ['CBOE GLOBAL MARKETS', 'PA1436583006', '14.194.401,54', '0,03', '%'],
 ['CBRE GROUP', 'FR0000120172', '28.774.170,25', '0,07', '%'],
 ['CCL INDUSTRIES B', 'US14448C1045', '5.047.148,63', '0,01', '%'],
 ['CDW CORP', 'AU000000CAR3', '12.624.920,66', '0,03', '%'],
 ['CELESTICA', 'US1468691027', '6.130.743,80', '0,01', '%'],
 ['CELLNEX TELECOM', 'TW0002882008', '12.244.860,38', '0,03', '%'],
 ['CELLTRION', 'US12503M1080', '6.249.708,68', '0,02', '%'],
 ['CEMIG PN', 'US12504L1098', '5.011.717,36', '0,01', '%'],
 ['CENCORA', 'CA1249003098', '37.169.051,70', '0,09', '%'],
 ['CENTENE CORP', 'US12514G1085', '18.185.692,21', '0,04', '%'],
 ['CENTRAL JAPAN', 'RAILWAY CO', 'ES0105066007', '8.792.098,07', '0,02', '%'],
 ['CENTRAL PATTA', 'NA PCL-NVDR', 'KR7068270008', '2.119.445,79', '0,01', '%'],
 ['CENTRICA', '', 'US03073E1055', '13.000.985,46', '0,03', '%'],

In [81]:
tabs3[1][3:]

['0,01', '%']

In [82]:
for i in range(len(tabs3)):
    combo = []
    combo = tabs3[i][0:-4]
    del tabs3[i][0:-4]
    combo = "".join(combo)
    tabs3[i].append(combo)

tabs3

[['US88557W1018', '29.605.115,44', '0,07', '%', '3I GROUP'],
 ['KYG2953R1149', '2.655.026,62', '0,01', '%', 'AAC TECHNOLOGIES (CN)'],
 ['GB00B1YW4409', '49.450.996,40', '0,12', '%', '3M CO'],
 ['US88579Y1010', '2.652.723,48', '0,01', '%', 'ABB INDIA'],
 ['KYG2953R1149', '53.407.655,61', '0,13', '%', 'ABB LTD'],
 ['INE117A01022', '138.627.032,19', '0,34', '%', 'ABBOTT LABORATORIES'],
 ['CH0012221716', '234.088.585,31', '0,57', '%', 'ABBVIE'],
 ['US0028241000', '9.684.515,34', '0,02', '%', 'ABN AMRO BANK A'],
 ['US00287Y1091', '3.307.828,00', '0,01', '%', 'ABSA GROUP'],
 ['NL0011540547', '8.921.788,71', '0,02', '%', 'ABU DHABI COMM BANK'],
 ['ZAE000255915', '4.752.599,36', '0,01', '%', 'ABU DHABI NATL OIL CO'],
 ['AEA000201011', '124.753.863,37', '0,30', '%', 'ACCENTURE A'],
 ['AEA006101017', '188.359,26', '0,00', '%', 'ACCIONA'],
 ['IE00B4BNMY34', '4.838.817,36', '0,01', '%', 'ACCOR'],
 ['ES0125220311', '2.755.815,44', '0,01', '%', 'ACCTON TECHNOLOGY CORP'],
 ['FR0000120404', '3.004.846,89', '0,01', '%', 'ACER'],
 ['TW0002345006', '2.219.996,65', '0,01', '%', 'ACS ACTIV CONST Y SVCS'],
 ['TW0002353000', '1.841.928,36', '0,00', '%', 'ADANI ENTERPRISES'],
 ['ES0167050915', '3.388.746,48', '0,01', '%', 'ADANI PORTS AND SEZ'],
 ['INE423A01024', '5.780.304,51', '0,01', '%', 'ADDTECH B'],
 ['INE742F01042', '22.863.541,39', '0,06', '%', 'ADIDAS'],
 ['DE000A1EWWW0', '4.283.287,49', '0,01', '%', 'ADNOC DRILLING COMPANY'],
 ['GB00B02J6398', '108.629.735,16', '0,27', '%', 'ADOBE'],
 ['AEA007301012', '1.042.973,97', '0,00', '%', 'ADP'],
 ['US00724F1012', '3.331.197,52', '0,01', '%', 'ADVANCED INFO SERVICE-NVDR'],
 ['FR0010340141', '116.363.442,50', '0,28', '%', 'ADVANCED MICRO DEVICES'],
 ['TH0268010R11', '22.717.726,53', '0,06', '%', 'ADVANTEST CORP'],
 ['US0079031078', '18.912.755,29', '0,05', '%', 'ADYEN NV'],
 ['JP3122400009', '8.188.891,77', '0,02', '%', 'AECOM'],
 ['NL0012969182', '9.200.334,70', '0,02', '%', 'AEGON'],
 ['US00766T1007', '16.875.532,53', '0,04', '%', 'AENA'],
 ['BMG0112X1056', '11.517.698,26', '0,03', '%', 'AEON CO'],
 ['ES0105046009', '18.558.075,83', '0,05', '%', 'AERCAP HOLDINGS NV'],
 ['JP3388200002', '37.575.282,52', '0,09', '%', 'AFLAC'],
 ['NL0000687663', '3.980.231,18', '0,01', '%', 'AGC'],
 ['US0010551028', '3.541.409,54', '0,01', '%', 'AGEAS'],
 ['JP3112000009', '26.161.264,32', '0,06', '%', 'AGILENT TECHNOLOGIES'],
 ['BE0974264930', '40.416.110,44', '0,10', '%', 'AGNICO EAGLE MINES'],
 ['US00846U1016', '2.849.995,78', '0,01', '%', 'AGRI BANK OF CHINA H'],
 ['CA0084741085', '4.130.870,83', '0,01', '%', 'AGRI BANK OF CN A (HK-C)'],
 ['CNE100000RJ0', '18.326.117,57', '0,04', '%', 'AHOLD DELHAIZE'],
 ['CNE100000Q43', '54.804.772,85', '0,13', '%', 'AIA GROUP'],
 ['IE00BF0L3536', '2.400.373,98', '0,01', '%', 'AIR CANADA VV'],
 ['CA0089118776', '47.400.016,68', '0,12', '%', 'AIR LIQUIDE'],
 ['FR0000120073', '35.998.524,75', '0,09', '%', 'AIR PRODUCTS & CHEMICALS'],
 ['US0091581068', '30.514.520,39', '0,07', '%', 'AIRBNB A'],
 ['US0090661010', '3.287.054,70', '0,01', '%', 'AIRPORTS OFTHAILAND PCL-FOR'],
 ['TH0765010Z16', '2.074.350,21', '0,01', '%', 'AIRTAC INTERNATIONAL'],
 ['KYG014081064', '1.574.163,77', '0,00', '%', 'AISIN CORP'],
 ['JP3102000001', '12.407.098,27', '0,03', '%', 'AJINOMOTO CO'],
 ['JP3119600009', '8.403.771,49', '0,02', '%', 'AKAMAI TECHNOLOGIES'],
 ['US00971T1016', '1.596.557,50', '0,00', '%', 'AKBANK'],
 ['TRAAKBNK91N6', '10.736.347,09', '0,03', '%', 'AKER BP'],
 ['NO0010345853', '2.570.471,64', '0,01', '%', 'AKESO (CN)'],
 ['KYG0146B1032', '11.288.852,30', '0,03', '%', 'AKZO NOBEL'],
 ['NL0013267909', '17.797.732,47', '0,04', '%', 'AL RAJHI BANKING & INV'],
 ['SA0007879113', '2.289.537,83', '0,01', '%', 'AL RAJHI FORCOPR INS'],
 ['SA12A0540J14', '6.415.226,32', '0,02', '%', 'ALBEMARLE CORP'],
 ['US0126531013', '4.185.156,63', '0,01', '%', 'ALBERTSONSCOMPANIES A'],
 ['US0130911037', '2.849.839,34', '0,01', '%', 'ALCHIP TECHNOLOGIES'],
 ['KYG022421088', '26.511.367,44', '0,06', '%', 'ALCON'],
 ['CH0432492467', '5.653.694,22', '0,01', '%', 'ALDAR PROPERTIES'],
 ['AEA002001013', '9.568.100,62', '0,02', '%', 'ALEXANDRIA REAL ESTATE'],
 ['SE0000695876', '92.405.341,23', '0,23', '%', 'ALIBABA GRP HLDG (HK)'],
 ['KYG017191142', '7.024.256,74', '0,02', '%', 'ALIGN TECHNOLOGY'],
 ['US0162551016', '22.275.440,81', '0,05', '%', 'ALIMENTATION COUCHE'],
 ['CA01626P1484', '4.193.570,92', '0,01', '%', 'ALINMA BANK'],
 ['SA122050HV19', '7.656.198,08', '0,02', '%', 'ALLEGION'],
 ['IE00BFRT3W74', '101.224.088,34', '0,25', '%', 'ALLIANZ'],
 ['DE0008404005', '34.820.325,88', '0,09', '%', 'ALLSTATE CORP'],
 ['US0200021014', '5.201.468,28', '0,01', '%', 'ALLY FINANCIAL'],
 ['US02005N1000', '3.117.267,28', '0,01', '%', 'ALMARAI CO'],
 ['SA000A0ETHT1', '20.741.921,97', '0,05', '%', 'ALNYLAM PHARMACEUTICALS'],
 ['US02043Q1076', '569.553.183,07', '1,39', '%', 'ALPHABET A'],
 ['US02079K3059', '486.949.144,67', '1,19', '%', 'ALPHABET C'],
 ['US02079K1079', '5.023.785,85', '0,01', '%', 'ALSTOM'],
 ['FR0010220475', '3.857.313,06', '0,01', '%', 'ALTAGAS'],
 ['CA0213611001', '3.112.514,21', '0,01', '%', 'ALTEOGEN'],
 ['KR7196170005', '18.982.340,31', '0,05', '%', 'AMADEUS IT GROUP A'],
 ['ES0109067019', '1.130.902.275,54', '2,76', '%', 'AMAZON.COM'],
 ['US0231351067', '8.023.246,36', '0,02', '%', 'AMCOR'],
 ['JE00BJ1F3079', '8.018.143,47', '0,02', '%', 'AMEREN CORPORATION'],
 ['US0235865062', '6.808.077,95', '0,02', '%', 'AMERICA MOVIL B'],
 ['US0236081024', '15.275.765,76', '0,04', '%', 'AMERICAN ELECTRIC POWER'],
 ['US0255371017', '7.031.126,36', '0,02', '%', 'AMERICAN FINANCIAL GROUP'],
 ['US0258161092', '8.736.507,60', '0,02', '%', 'AMERICAN HOMES 4 RENT A'],
 ['US0259321042', '35.396.984,15', '0,09', '%', 'AMERICAN INTL GROUP'],
 ['US02665T3068', '61.433.898,66', '0,15', '%', 'AMERICAN TOWER CORP'],
 ['US0268747849', '21.163.060,43', '0,05', '%', 'AMERICAN WATER WORKS CO'],
 ['US03027X1000', '34.027.814,78', '0,08', '%', 'AMERIPRISE FINANCIAL'],
 ['US0304201033', '25.446.416,29', '0,06', '%', 'AMETEK'],
 ['US03076C1062', '106.655.147,46', '0,26', '%', 'AMGEN'],
 ['US0311001004', '45.955.598,63', '0,11', '%', 'AMPHENOL CORP'],
 ['US0311621009', '8.624.692,34', '0,02', '%', 'AMUNDI'],
 ['US0320951017', '61.559.408,86', '0,15', '%', 'ANALOG DEVICES'],
 ['FR0004125920', '25.485.417,75', '0,06', '%', 'ANGLO AMERICAN'],
 ['US0326541051', '1.959.951,13', '0,00', '%', 'ANGLO AMERICAN PLATINUM'],
 ['ZAE000013181', '6.646.369,78', '0,02', '%', 'ANGLOGOLD ASHANTI'],
 ['GB00B1XZS820', '32.060.780,76', '0,08', '%', 'ANHEUSER-BUSCH INBEV'],
 ['GB00BRXH2664', '4.491.600,86', '0,01', '%', 'ANNALY CAPITAL MGMT'],
 ['BE0974293251', '15.632.636,49', '0,04', '%', 'ANSYS'],
 ['US0357108390', '5.504.635,36', '0,01', '%', 'ANTA SPORTS PRODUCTS'],
 ['US03662Q1058', '6.048.721,61', '0,01', '%', 'ANTOFAGASTA'],
 ['KYG040111059', '37.650.838,16', '0,09', '%', 'ANZ GROUP HOLDINGS'],
 ['GB0000456144', '47.732.444,64', '0,12', '%', 'AON PLC A'],
 ['IE00BLP1HW54', '5.525.084,99', '0,01', '%', 'AP MOLLER MAERSK B'],
 ['DK0010244425', '3.063.133,01', '0,01', '%', 'APA GROUP'],
 ['DK0010244508', '34.601.243,20', '0,08', '%', 'APOLLO GLOBAL MGMT A'],
 ['AU000000APA1', '6.023.134,65', '0,01', '%', 'APOLLO HOSPITALS'],
 ['US03769M1062', '2.120.228.282,96', '5,18', '%', 'APPLE'],
 ['INE437A01024', '73.997.757,43', '0,18', '%', 'APPLIED MATERIALS'],
 ['US0378331005', '34.052.048,30', '0,08', '%', 'APPLOVIN CORP A'],
 ['US0382221051', '14.329.360,00', '0,04', '%', 'APTIV PLC'],
 ['US03831W1080', '3.438.648,96', '0,01', '%', 'ARAB NATIONAL BANK'],
 ['JE00BTDN8H13', '7.225.391,23', '0,02', '%', 'ARC RESOURCES'],
 ['SA0007879105', '3.339.422,01', '0,01', '%', 'ARCELORMITTAL A'],
 ['CA00208D4084', '21.103.029,58', '0,05', '%', 'ARCH CAPITAL GROUP'],
 ['LU1598757687', '13.501.363,83', '0,03', '%', 'ARCHER-DANIELS-MIDLAND'],
 ['BMG0450A1053', '17.944.114,01', '0,04', '%', 'ARES MANAGEMENT CORP'],
 ['US0394831020', '20.379.761,42', '0,05', '%', 'ARGEN X'],
 ['US03990B1017', '53.145.427,91', '0,13', '%', 'ARISTA NETWORKS'],
 ['NL0010832176', '13.312.223,12', '0,03', '%', 'ARISTOCRAT LEISURE'],
 ['US0404132054', '4.706.027,12', '0,01', '%', 'ARKEMA'],
 ['AU000000ALL7', '9.740.383,22', '0,02', '%', 'ASAHI GROUP HOLDINGS'],
 ['FR0010313833', '5.435.328,13', '0,01', '%', 'ASAHI KASEI CORP'],
 ['US3635761097', '5.855.330,45', '0,01', '%', 'ASE TECHNOLOGY HOLDING'],
 ['JP3111200006', '12.821.101,08', '0,03', '%', 'ASHTEAD GROUP'],
 ['TW0003711008', '1.699.918,76', '0,00', '%', 'ASIA VITAL COMPONENTS'],
 ['INE208A01029', '4.077.265,57', '0,01', '%', 'ASIAN PAINTS'],
 ['GB0000536739', '10.472.942,25', '0,03', '%', 'ASICS CORP'],
 ['TW0003017000', '12.399.632,09', '0,03', '%', 'ASM INTERNATIONAL'],
 ['INE021A01026', '164.424.223,09', '0,40', '%', 'ASML HLDG'],
 ['JP3118000003', '9.590.651,43', '0,02', '%', 'ASR NEDERLAND'],
 ['NL0000334118', '17.382.407,36', '0,04', '%', 'ASSA ABLOY B'],
 ['NL0010273215', '26.620.513,63', '0,07', '%', 'ASSICURAZIONI GENERALI'],
 ['US29109X1063', '1.539.988,25', '0,00', '%', 'ASSOCIATED BRITISH FOODS'],
 ['NL0011872643', '8.694.972,08', '0,02', '%', 'ASSURANT'],
 ['SE0007100581', '12.139.089,78', '0,03', '%', 'ASTELLAS PHARMA'],
 ['IT0000062072', '145.536.118,07', '0,36', '%', 'ASTRAZENECA'],
 ['GB0006731235', '4.053.844,46', '0,01', '%', 'ASUSTEK COMPUTER'],
 ['US04621X1081', '2.030.058,21', '0,00', '%', 'ASX'],
 ['JP3942400007', '122.622.704,58', '0,30', '%', 'AT&T'],
 ['GB0009895292', '28.239.144,36', '0,07', '%', 'ATLAS COPCO A'],
 ['TW0002357001', '10.725.040,49', '0,03', '%', 'ATLAS COPCO B'],
 ['AU000000ASX7', '20.390.392,18', '0,05', '%', 'ATLASSIAN (US)'],
 ['US00206R1023', '19.691.483,64', '0,05', '%', 'ATMOS ENERGY CORP'],
 ['SE0017486889', '3.835.518,17', '0,01', '%', 'AUCKLAND INTL AIRPORT'],
 ['US0494681010', '5.093.349,87', '0,01', '%', 'AUTO TRADER GROUP'],
 ['US0495601058', '34.288.371,28', '0,08', '%', 'AUTODESK'],
 ['NZAIAE0002S6', '81.774.553,69', '0,20', '%', 'AUTOMATIC DATA PROCESS'],
 ['TW0002409000', '39.184.549,51', '0,10', '%', 'AUTOZONE'],
 ['GB00BVYVFW23', '24.813.950,04', '0,06', '%', 'AVALONBAY COMMUNITIES'],
 ['US0527691069', '7.287.761,31', '0,02', '%', 'AVANTOR'],
 ['US0530151036', '3.242.394,16', '0,01', '%', 'AVENUE SUPERMARTS'],
 ['US0533321024', '10.097.746,66', '0,02', '%', 'AVERY DENNISON CORP'],
 ['US0534841012', '13.744.839,39', '0,03', '%', 'AVIVA'],
 ['US05352A1007', '650.866,55', '0,00', '%', 'AVOLTA'],
 ['INE192R01011', '54.197.477,97', '0,13', '%', 'AXA'],
 ['US0536111091', '12.298.643,40', '0,03', '%', 'AXIS BANK'],
 ['GB00BPQY8M80', '22.209.565,11', '0,05', '%', 'AXON ENTERPRISE'],
 ['CH0023405456', '1.973.487,28', '0,00', '%', 'AYALA CORP'],
 ['FR0000120628', '4.448.631,28', '0,01', '%', 'AZRIELI GROUP'],
 ['INE238A01034', '7.199.336,95', '0,02', '%', 'B3'],
 ['US05464C1018', '10.798.447,22', '0,03', '%', 'BAIDU (HK)'],
 ['PHY0486V1154', '2.112.435,29', '0,01', '%', 'BAJAJ AUTO'],
 ['IL0011194789', '10.111.353,62', '0,02', '%', 'BAJAJ FINANCE'],
 ['BRB3SAACNOR6', '3.938.202,99', '0,01', '%', 'BAJAJ FINSERV'],
 ['KYG070341048', '31.280.745,61', '0,08', '%', 'BAKER HUGHES CO'],
 ['INE296A01024', '1.726.212,74', '0,00', '%', 'BALOISE HOLDING'],
 ['INE918I01026', '7.023.647,05', '0,02', '%', 'BANCO BPM'],
 ['US05722G1004', '4.852.658,39', '0,01', '%', 'BANCO BRADESCO ON'],
 ['US0584981064', '3.498.421,06', '0,01', '%', 'BANCO BRADESCO PN'],
 ['CH0012410517', '3.441.607,04', '0,01', '%', 'BANCO BTG PACTUAL'],
 ['ES0113211835', '8.095.815,92', '0,02', '%', 'BANCO SABADELL'],
 ['IT0005218380', '58.183.356,56', '0,14', '%', 'BANCO SANTANDER'],
 ['BRBBDCACNOR1', '2.934.114,80', '0,01', '%', 'BANCOLOMBIAPREF'],
 ['BRBBDCACNPR8', '11.902.473,98', '0,03', '%', 'BANDAI NAMCOHOLDINGS'],
 ['BRBPACUNT006', '3.284.270,65', '0,01', '%', 'BANGKOK DUSITMED SERVI-NVDR'],
 ['ES0113860A34', '2.616.921,97', '0,01', '%', 'BANK ALBILAD'],
 ['CLP1506A1070', '10.896.203,99', '0,03', '%', 'BANK CENTRALASIA'],
 ['ES0113900J37', '3.819.627,16', '0,01', '%', 'BANK MANDIRI'],
 ['COB07PA00086', '47.331.586,30', '0,12', '%', 'BANK MONTREAL'],
 ['JP3778630008', '43.288.432,91', '0,11', '%', 'BANK NEW YORKMELLON'],
 ['TH0264010R10', '41.405.599,74', '0,10', '%', 'BANK NOVA SCOTIA'],
 ['SA000A0D9HK3', '183.285.409,53', '0,45', '%', 'BANK OF AMERICA CORP'],
 ['ID1000109507', '17.119.859,53', '0,04', '%', 'BANK OF CHINAH'],
 ['ID1000095003', '3.542.106,49', '0,01', '%', 'BANK OF COMMU A (HK-C)'],
 ['US0605051046', '7.174.228,22', '0,02', '%', 'BANK OF IRELAND GROUP'],
 ['CNE1000001Z5', '7.285.780,08', '0,02', '%', 'BANK OF PHIL ISLANDS'],
 ['IE00BD1RP616', '687.815,92', '0,00', '%', 'BANQUE CANTONALE VAUDOIS'],
 ['CA0636711016', '3.150.775,39', '0,01', '%', 'BANQUE SAUDI FRANSI'],
 ['US0640581007', '32.115.999,66', '0,08', '%', 'BARCLAYS'],
 ['CA0641491075', '7.785.747,03', '0,02', '%', 'BARRATT REDROW'],
 ['PHY0967S1694', '466.602,19', '0,00', '%', 'BARRY CALLEBAUT'],
 ['ID1000118201', '2.183.260,03', '0,01', '%', 'BARWA REAL ESTATE CO'],
 ['CH0531751755', '11.869.272,38', '0,03', '%', 'BAXTER INTERNATIONAL'],
 ['SA0007879782', '13.617.499,02', '0,03', '%', 'BAYER'],
 ['GB0031348658', '43.663.205,89', '0,11', '%', 'BBVA'],
 ['GB0000811801', '3.440.264,37', '0,01', '%', 'BCE INC'],
 ['CH0009002962', '6.944.108,89', '0,02', '%', 'BCO SANTANDER CHILE (NEW'],
 ['QA000A0KD6J5', '5.409.683,30', '0,01', '%', 'BE SEMICONDUCTOR IND'],
 ['US0718131099', '41.843.566,38', '0,10', '%', 'BECTON DICKINSON'],
 ['DE000BAY0017', '5.451.669,32', '0,01', '%', 'BEIERSDORF'],
 ['DE0005190003', '6.713.000,26', '0,02', '%', 'BEIGENE (HK)'],
 ['DE0005190037', '2.975.280,10', '0,01', '%', 'BEIJER REF B'],
 ['CA05534B7604', '2.566.023,30', '0,01', '%', 'BENTLEY SYSTEMS B'],
 ['NL0012866412', '14.152.667,20', '0,03', '%', 'BERKLEY (W.R.) CORP'],
 ['US0758871091', '13.291.657,85', '0,03', '%', 'BEST BUY CO'],
 ['DE0005200000', '5.227.305,79', '0,01', '%', 'BHARAT ELECTRONICS'],
 ['KYG1146Y1017', '2.014.295,97', '0,00', '%', 'BHARAT PETROLEUM CORP'],
 ['US08265T2087', '3.101.176,42', '0,01', '%', 'BID CORPORATION'],
 ['US0865161014', '2.661.251,79', '0,01', '%', 'BIDVEST GROUP'],
 ['INE263A01024', '2.182.715,14', '0,01', '%', 'BIM BIRLESIK MAGAZALAR'],
 ['INE029A01011', '13.580.314,83', '0,03', '%', 'BIOGEN'],
 ['INE397D01024', '8.779.914,76', '0,02', '%', 'BIOMARIN PHARMACEUTICAL'],
 ['ZAE000216537', '5.208.279,18', '0,01', '%', 'BIOMERIEUX'],
 ['ZAE000117321', '2.627.587,73', '0,01', '%', 'BIO-RAD LABORATORIES A'],
 ['TREBIMM00018', '6.048.174,70', '0,01', '%', 'BIO-TECHNE CORP'],
 ['US09062X1037', '6.167.067,93', '0,02', '%', 'BKW'],
 ['US09061G1013', '91.642.870,34', '0,22', '%', 'BLACKROCK'],
 ['FR0013280286', '63.171.136,64', '0,15', '%', 'BLACKSTONE GROUP'],
 ['US0905722072', '17.753.009,84', '0,04', '%', 'BLOCK'],
 ['US09073M1045', '588.080,08', '0,00', '%', 'BLUESCOPE STEEL'],
 ['CH0130293662', '14.646.676,78', '0,04', '%', 'BMW STAMM'],
 ['US09290D1019', '5.611.723,81', '0,01', '%', 'BMW VORZUG'],
 ['US09260D1072', '55.504.887,17', '0,14', '%', 'BNP PARIBAS'],
 ['US8522341036', '10.118.357,94', '0,02', '%', 'BOC HONG KONG HOLDINGS'],
 ['AU000000BSL0', '9.453.535,14', '0,02', '%', 'BOLIDEN'],
 ['FR0000131104', '1.411.060,58', '0,00', '%', 'BOLLORE'],
 ['HK2388011192', '98.001.030,41', '0,24', '%', 'BOOKING HOLDINGS'],
 ['SE0020050417', '8.006.717,13', '0,02', '%', 'BOOZ ALLEN HAMILTON A'],
 ['US09857L1089', '98.373.746,13', '0,24', '%', 'BOSTON SCIENTIFIC CORP'],
 ['US0995021062', '2.271.185,77', '0,01', '%', 'BOUYGUES'],
 ['KYG126521064', '54.993.388,79', '0,13', '%', 'BP'],
 ['US1011211018', '2.266.426,88', '0,01', '%', 'BPER BANCA'],
 ['US1011371077', '20.108.966,94', '0,05', '%', 'BRAMBLES'],
 ['FR0000120503', '6.567.061,85', '0,02', '%', 'BRENNTAG'],
 ['GB0007980591', '16.570.280,61', '0,04', '%', 'BRIDGESTONE CORP'],
 ['IT0000066123', '90.300.646,27', '0,22', '%', 'BRISTOL-MYERS SQUIBB CO'],
 ['AU000000BXB1', '2.779.755,98', '0,01', '%', 'BRITANNIA INDUSTRIES'],
 ['DE000A1DAHH0', '471.000.183,16', '1,15', '%', 'BROADCOM'],
 ['JP3830800003', '16.107.944,86', '0,04', '%', 'BROADRIDGE FINANCIAL'],
 ['US1101221083', '9.581.353,59', '0,02', '%', 'BROOKFIELD ASSET MAN LTD'],
 ['INE216A01030', '44.580.792,39', '0,11', '%', 'BROOKFIELD CORP A'],
 ['US11135F1012', '1.902.621,16', '0,00', '%', 'BROOKFIELD RENEWABLE'],
 ['US11133T1034', '19.114.457,55', '0,05', '%', 'BROWN & BROWN'],
 ['CA1130041058', '1.099.630,67', '0,00', '%', 'BROWN-FORMAN CORP B'],
 ['CA11271J1075', '9.404.685,59', '0,02', '%', 'BT GROUP'],
 ['CA11285B1085', '8.759.523,47', '0,02', '%', 'BUILDERS FIRSTSOURCE'],
 ['US1152361010', '1.677.854,72', '0,00', '%', 'BUMRUNGRAD HOSPITAL PCL-NVDR'],
 ['US1156372096', '10.619.001,57', '0,03', '%', 'BUNGE GLOBAL'],
 ['GB0030913577', '8.872.213,94', '0,02', '%', 'BUNZL'],
 ['TH0168010R13', '8.326.710,31', '0,02', '%', 'BUREAU VERITAS SA'],
 ['CH1300646267', '8.821.300,13', '0,02', '%', 'BURLINGTON STORES'],
 ['GB00B0744B38', '8.806.017,37', '0,02', '%', 'BXP'],
 ['SA1210540914', '8.319.593,85', '0,02', '%', 'BYD CO A (HK-C)'],
 ['FR0006174348', '11.298.415,58', '0,03', '%', 'BYD CO H'],
 ['US1220171060', '44.522.261,68', '0,11', '%', 'CADENCE DESIGN SYSTEMS'],
 ['CNE100001526', '7.861.080,91', '0,02', '%', 'CAE'],
 ['CNE100000296', '18.717.084,94', '0,05', '%', 'CAIXABANK'],
 ['US12541W2098', '7.871.651,57', '0,02', '%', 'CAMDEN PROPERTY TRUST'],
 ['US1273871087', '11.992.710,61', '0,03', '%', 'CAMECO CORP'],
 ['CA1247651088', '37.120.458,35', '0,09', '%', 'CANADIAN IMPERIAL BANK'],
 ['ES0140609019', '32.084.536,90', '0,08', '%', 'CANADIAN NATL RAILWAY'],
 ['US1331311027', '1.729.726,76', '0,00', '%', 'CANADIAN TIRE CORP A'],
 ['CA13321L1085', '7.523.232,57', '0,02', '%', 'CANADIAN UTILITIES A'],
 ['US1344291091', '16.776.646,66', '0,04', '%', 'CANON INC'],
 ['CA1360691010', '5.550.625,61', '0,01', '%', 'CAPCOM CO'],
 ['CA1363751027', '15.407.840,01', '0,04', '%', 'CAPGEMINI'],
 ['CA13646K1084', '43.185.682,63', '0,11', '%', 'CAPITAL ONE FINANCIAL'],
 ['CA1366812024', '1.281.435,38', '0,00', '%', 'CAPITALAND ASCENDAS REIT'],
 ['CA1367178326', '8.244.069,65', '0,02', '%', 'CAPITALAND INTEGRATED'],
 ['JP3242800005', '4.344.949,77', '0,01', '%', 'CAPITALAND INVESTMENT'],
 ['FR0000125338', '5.160.033,86', '0,01', '%', 'CAR GROUP'],
 ['US14040H1059', '24.945.448,81', '0,06', '%', 'CARDINAL HEALTH'],
 ['SG1M77906915', '9.385.749,83', '0,02', '%', 'CARLISLE COS'],
 ['SG1M51904654', '10.947.724,78', '0,03', '%', 'CARLSBERG B'],
 ['SGXE62145532', '5.967.666,17', '0,01', '%', 'CARLYLE GROUP'],
 ['ZAE000035861', '8.816.831,50', '0,02', '%', 'CARMAX'],
 ['US14149Y1082', '7.696.419,76', '0,02', '%', 'CARNIVAL CORP (US)'],
 ['US1423391002', '7.976.236,53', '0,02', '%', 'CARREFOUR'],
 ['DK0010181759', '37.621.715,66', '0,09', '%', 'CARRIER GLOBAL'],
 ['US14316J1088', '14.001.521,96', '0,03', '%', 'CARVANA A'],
 ['US1431301027', '5.665.147,78', '0,01', '%', 'CATHAY FINANCIAL HOLDING'],
 ['PA1436583006', '14.194.401,54', '0,03', '%', 'CBOE GLOBAL MARKETS'],
 ['FR0000120172', '28.774.170,25', '0,07', '%', 'CBRE GROUP'],
 ['US14448C1045', '5.047.148,63', '0,01', '%', 'CCL INDUSTRIES B'],
 ['AU000000CAR3', '12.624.920,66', '0,03', '%', 'CDW CORP'],
 ['US1468691027', '6.130.743,80', '0,01', '%', 'CELESTICA'],
 ['TW0002882008', '12.244.860,38', '0,03', '%', 'CELLNEX TELECOM'],
 ['US12503M1080', '6.249.708,68', '0,02', '%', 'CELLTRION'],
 ['US12504L1098', '5.011.717,36', '0,01', '%', 'CEMIG PN'],
 ['CA1249003098', '37.169.051,70', '0,09', '%', 'CENCORA'],
 ['US12514G1085', '18.185.692,21', '0,04', '%', 'CENTENE CORP'],
 ['ES0105066007', '8.792.098,07', '0,02', '%', 'CENTRAL JAPANRAILWAY CO'],
 ['KR7068270008', '2.119.445,79', '0,01', '%', 'CENTRAL PATTANA PCL-NVDR'],
 ['US03073E1055', '13.000.985,46', '0,03', '%', 'CENTRICA'],
 ['US15135B1017', '5.051.596,98', '0,01', '%', 'CF INDUSTRIESHOLDINGS'],
 ['US15189T1079', '2.425.002,55', '0,01', '%', 'CG POWER & INDUSTRIAL'],
 ['BRELETACNPB7', '10.937.982,81', '0,03', '%', 'CGI A'],

In [83]:
print(tabs3[0][3])
tabs3[0][2]

%

'0,07'

In [84]:
for i in range(len(tabs3)):
    tabs3[i].append("".join(tabs3[i][2:4]))

tabs3

[['US88557W1018', '29.605.115,44', '0,07', '%', '3I GROUP', '0,07%'],
 ['KYG2953R1149',
  '2.655.026,62',
  '0,01',
  '%',
  'AAC TECHNOLOGIES (CN)',
  '0,01%'],
 ['GB00B1YW4409', '49.450.996,40', '0,12', '%', '3M CO', '0,12%'],
 ['US88579Y1010', '2.652.723,48', '0,01', '%', 'ABB INDIA', '0,01%'],
 ['KYG2953R1149', '53.407.655,61', '0,13', '%', 'ABB LTD', '0,13%'],
 ['INE117A01022',
  '138.627.032,19',
  '0,34',
  '%',
  'ABBOTT LABORATORIES',
  '0,34%'],
 ['CH0012221716', '234.088.585,31', '0,57', '%', 'ABBVIE', '0,57%'],
 ['US0028241000', '9.684.515,34', '0,02', '%', 'ABN AMRO BANK A', '0,02%'],
 ['US00287Y1091', '3.307.828,00', '0,01', '%', 'ABSA GROUP', '0,01%'],
 ['NL0011540547', '8.921.788,71', '0,02', '%', 'ABU DHABI COMM BANK', '0,02%'],
 ['ZAE000255915',
  '4.752.599,36',
  '0,01',
  '%',
  'ABU DHABI NATL OIL CO',
  '0,01%'],
 ['AEA000201011', '124.753.863,37', '0,30', '%', 'ACCENTURE A', '0,30%'],
 ['AEA006101017', '188.359,26', '0,00', '%', 'ACCIONA', '0,00%'],
 ['IE00B4BNMY34', '4.838.817,36', '0,01', '%', 'ACCOR', '0,01%'],
 ['ES0125220311',
  '2.755.815,44',
  '0,01',
  '%',
  'ACCTON TECHNOLOGY CORP',
  '0,01%'],
 ['FR0000120404', '3.004.846,89', '0,01', '%', 'ACER', '0,01%'],
 ['TW0002345006',
  '2.219.996,65',
  '0,01',
  '%',
  'ACS ACTIV CONST Y SVCS',
  '0,01%'],
 ['TW0002353000', '1.841.928,36', '0,00', '%', 'ADANI ENTERPRISES', '0,00%'],
 ['ES0167050915', '3.388.746,48', '0,01', '%', 'ADANI PORTS AND SEZ', '0,01%'],
 ['INE423A01024', '5.780.304,51', '0,01', '%', 'ADDTECH B', '0,01%'],
 ['INE742F01042', '22.863.541,39', '0,06', '%', 'ADIDAS', '0,06%'],
 ['DE000A1EWWW0',
  '4.283.287,49',
  '0,01',
  '%',
  'ADNOC DRILLING COMPANY',
  '0,01%'],
 ['GB00B02J6398', '108.629.735,16', '0,27', '%', 'ADOBE', '0,27%'],
 ['AEA007301012', '1.042.973,97', '0,00', '%', 'ADP', '0,00%'],
 ['US00724F1012',
  '3.331.197,52',
  '0,01',
  '%',
  'ADVANCED INFO SERVICE-NVDR',
  '0,01%'],
 ['FR0010340141',
  '116.363.442,50',
  '0,28',
  '%',
  'ADVANCED MICRO DEVICES',
  '0,28%'],
 ['TH0268010R11', '22.717.726,53', '0,06', '%', 'ADVANTEST CORP', '0,06%'],
 ['US0079031078', '18.912.755,29', '0,05', '%', 'ADYEN NV', '0,05%'],
 ['JP3122400009', '8.188.891,77', '0,02', '%', 'AECOM', '0,02%'],
 ['NL0012969182', '9.200.334,70', '0,02', '%', 'AEGON', '0,02%'],
 ['US00766T1007', '16.875.532,53', '0,04', '%', 'AENA', '0,04%'],
 ['BMG0112X1056', '11.517.698,26', '0,03', '%', 'AEON CO', '0,03%'],
 ['ES0105046009', '18.558.075,83', '0,05', '%', 'AERCAP HOLDINGS NV', '0,05%'],
 ['JP3388200002', '37.575.282,52', '0,09', '%', 'AFLAC', '0,09%'],
 ['NL0000687663', '3.980.231,18', '0,01', '%', 'AGC', '0,01%'],
 ['US0010551028', '3.541.409,54', '0,01', '%', 'AGEAS', '0,01%'],
 ['JP3112000009',
  '26.161.264,32',
  '0,06',
  '%',
  'AGILENT TECHNOLOGIES',
  '0,06%'],
 ['BE0974264930', '40.416.110,44', '0,10', '%', 'AGNICO EAGLE MINES', '0,10%'],
 ['US00846U1016',
  '2.849.995,78',
  '0,01',
  '%',
  'AGRI BANK OF CHINA H',
  '0,01%'],
 ['CA0084741085',
  '4.130.870,83',
  '0,01',
  '%',
  'AGRI BANK OF CN A (HK-C)',
  '0,01%'],
 ['CNE100000RJ0', '18.326.117,57', '0,04', '%', 'AHOLD DELHAIZE', '0,04%'],
 ['CNE100000Q43', '54.804.772,85', '0,13', '%', 'AIA GROUP', '0,13%'],
 ['IE00BF0L3536', '2.400.373,98', '0,01', '%', 'AIR CANADA VV', '0,01%'],
 ['CA0089118776', '47.400.016,68', '0,12', '%', 'AIR LIQUIDE', '0,12%'],
 ['FR0000120073',
  '35.998.524,75',
  '0,09',
  '%',
  'AIR PRODUCTS & CHEMICALS',
  '0,09%'],
 ['US0091581068', '30.514.520,39', '0,07', '%', 'AIRBNB A', '0,07%'],
 ['US0090661010',
  '3.287.054,70',
  '0,01',
  '%',
  'AIRPORTS OFTHAILAND PCL-FOR',
  '0,01%'],
 ['TH0765010Z16',
  '2.074.350,21',
  '0,01',
  '%',
  'AIRTAC INTERNATIONAL',
  '0,01%'],
 ['KYG014081064', '1.574.163,77', '0,00', '%', 'AISIN CORP', '0,00%'],
 ['JP3102000001', '12.407.098,27', '0,03', '%', 'AJINOMOTO CO', '0,03%'],
 ['JP3119600009', '8.403.771,49', '0,02', '%', 'AKAMAI TECHNOLOGIES', '0,02%'],
 ['US00971T1016', '1.596.557,50', '0,00', '%', 'AKBANK', '0,00%'],
 ['TRAAKBNK91N6', '10.736.347,09', '0,03', '%', 'AKER BP', '0,03%'],
 ['NO0010345853', '2.570.471,64', '0,01', '%', 'AKESO (CN)', '0,01%'],
 ['KYG0146B1032', '11.288.852,30', '0,03', '%', 'AKZO NOBEL', '0,03%'],
 ['NL0013267909',
  '17.797.732,47',
  '0,04',
  '%',
  'AL RAJHI BANKING & INV',
  '0,04%'],
 ['SA0007879113',
  '2.289.537,83',
  '0,01',
  '%',
  'AL RAJHI FORCOPR INS',
  '0,01%'],
 ['SA12A0540J14', '6.415.226,32', '0,02', '%', 'ALBEMARLE CORP', '0,02%'],
 ['US0126531013',
  '4.185.156,63',
  '0,01',
  '%',
  'ALBERTSONSCOMPANIES A',
  '0,01%'],
 ['US0130911037', '2.849.839,34', '0,01', '%', 'ALCHIP TECHNOLOGIES', '0,01%'],
 ['KYG022421088', '26.511.367,44', '0,06', '%', 'ALCON', '0,06%'],
 ['CH0432492467', '5.653.694,22', '0,01', '%', 'ALDAR PROPERTIES', '0,01%'],
 ['AEA002001013',
  '9.568.100,62',
  '0,02',
  '%',
  'ALEXANDRIA REAL ESTATE',
  '0,02%'],
 ['SE0000695876',
  '92.405.341,23',
  '0,23',
  '%',
  'ALIBABA GRP HLDG (HK)',
  '0,23%'],
 ['KYG017191142', '7.024.256,74', '0,02', '%', 'ALIGN TECHNOLOGY', '0,02%'],
 ['US0162551016',
  '22.275.440,81',
  '0,05',
  '%',
  'ALIMENTATION COUCHE',
  '0,05%'],
 ['CA01626P1484', '4.193.570,92', '0,01', '%', 'ALINMA BANK', '0,01%'],
 ['SA122050HV19', '7.656.198,08', '0,02', '%', 'ALLEGION', '0,02%'],
 ['IE00BFRT3W74', '101.224.088,34', '0,25', '%', 'ALLIANZ', '0,25%'],
 ['DE0008404005', '34.820.325,88', '0,09', '%', 'ALLSTATE CORP', '0,09%'],
 ['US0200021014', '5.201.468,28', '0,01', '%', 'ALLY FINANCIAL', '0,01%'],
 ['US02005N1000', '3.117.267,28', '0,01', '%', 'ALMARAI CO', '0,01%'],
 ['SA000A0ETHT1',
  '20.741.921,97',
  '0,05',
  '%',
  'ALNYLAM PHARMACEUTICALS',
  '0,05%'],
 ['US02043Q1076', '569.553.183,07', '1,39', '%', 'ALPHABET A', '1,39%'],
 ['US02079K3059', '486.949.144,67', '1,19', '%', 'ALPHABET C', '1,19%'],
 ['US02079K1079', '5.023.785,85', '0,01', '%', 'ALSTOM', '0,01%'],
 ['FR0010220475', '3.857.313,06', '0,01', '%', 'ALTAGAS', '0,01%'],
 ['CA0213611001', '3.112.514,21', '0,01', '%', 'ALTEOGEN', '0,01%'],
 ['KR7196170005', '18.982.340,31', '0,05', '%', 'AMADEUS IT GROUP A', '0,05%'],
 ['ES0109067019', '1.130.902.275,54', '2,76', '%', 'AMAZON.COM', '2,76%'],
 ['US0231351067', '8.023.246,36', '0,02', '%', 'AMCOR', '0,02%'],
 ['JE00BJ1F3079', '8.018.143,47', '0,02', '%', 'AMEREN CORPORATION', '0,02%'],
 ['US0235865062', '6.808.077,95', '0,02', '%', 'AMERICA MOVIL B', '0,02%'],
 ['US0236081024',
  '15.275.765,76',
  '0,04',
  '%',
  'AMERICAN ELECTRIC POWER',
  '0,04%'],
 ['US0255371017',
  '7.031.126,36',
  '0,02',
  '%',
  'AMERICAN FINANCIAL GROUP',
  '0,02%'],
 ['US0258161092',
  '8.736.507,60',
  '0,02',
  '%',
  'AMERICAN HOMES 4 RENT A',
  '0,02%'],
 ['US0259321042',
  '35.396.984,15',
  '0,09',
  '%',
  'AMERICAN INTL GROUP',
  '0,09%'],
 ['US02665T3068',
  '61.433.898,66',
  '0,15',
  '%',
  'AMERICAN TOWER CORP',
  '0,15%'],
 ['US0268747849',
  '21.163.060,43',
  '0,05',
  '%',
  'AMERICAN WATER WORKS CO',
  '0,05%'],
 ['US03027X1000',
  '34.027.814,78',
  '0,08',
  '%',
  'AMERIPRISE FINANCIAL',
  '0,08%'],
 ['US0304201033', '25.446.416,29', '0,06', '%', 'AMETEK', '0,06%'],
 ['US03076C1062', '106.655.147,46', '0,26', '%', 'AMGEN', '0,26%'],
 ['US0311001004', '45.955.598,63', '0,11', '%', 'AMPHENOL CORP', '0,11%'],
 ['US0311621009', '8.624.692,34', '0,02', '%', 'AMUNDI', '0,02%'],
 ['US0320951017', '61.559.408,86', '0,15', '%', 'ANALOG DEVICES', '0,15%'],
 ['FR0004125920', '25.485.417,75', '0,06', '%', 'ANGLO AMERICAN', '0,06%'],
 ['US0326541051',
  '1.959.951,13',
  '0,00',
  '%',
  'ANGLO AMERICAN PLATINUM',
  '0,00%'],
 ['ZAE000013181', '6.646.369,78', '0,02', '%', 'ANGLOGOLD ASHANTI', '0,02%'],
 ['GB00B1XZS820',
  '32.060.780,76',
  '0,08',
  '%',
  'ANHEUSER-BUSCH INBEV',
  '0,08%'],
 ['GB00BRXH2664', '4.491.600,86', '0,01', '%', 'ANNALY CAPITAL MGMT', '0,01%'],
 ['BE0974293251', '15.632.636,49', '0,04', '%', 'ANSYS', '0,04%'],
 ['US0357108390',
  '5.504.635,36',
  '0,01',
  '%',
  'ANTA SPORTS PRODUCTS',
  '0,01%'],
 ['US03662Q1058', '6.048.721,61', '0,01', '%', 'ANTOFAGASTA', '0,01%'],
 ['KYG040111059', '37.650.838,16', '0,09', '%', 'ANZ GROUP HOLDINGS', '0,09%'],
 ['GB0000456144', '47.732.444,64', '0,12', '%', 'AON PLC A', '0,12%'],
 ['IE00BLP1HW54', '5.525.084,99', '0,01', '%', 'AP MOLLER MAERSK B', '0,01%'],
 ['DK0010244425', '3.063.133,01', '0,01', '%', 'APA GROUP', '0,01%'],
 ['DK0010244508',
  '34.601.243,20',
  '0,08',
  '%',
  'APOLLO GLOBAL MGMT A',
  '0,08%'],
 ['AU000000APA1', '6.023.134,65', '0,01', '%', 'APOLLO HOSPITALS', '0,01%'],
 ['US03769M1062', '2.120.228.282,96', '5,18', '%', 'APPLE', '5,18%'],
 ['INE437A01024', '73.997.757,43', '0,18', '%', 'APPLIED MATERIALS', '0,18%'],
 ['US0378331005', '34.052.048,30', '0,08', '%', 'APPLOVIN CORP A', '0,08%'],
 ['US0382221051', '14.329.360,00', '0,04', '%', 'APTIV PLC', '0,04%'],
 ['US03831W1080', '3.438.648,96', '0,01', '%', 'ARAB NATIONAL BANK', '0,01%'],
 ['JE00BTDN8H13', '7.225.391,23', '0,02', '%', 'ARC RESOURCES', '0,02%'],
 ['SA0007879105', '3.339.422,01', '0,01', '%', 'ARCELORMITTAL A', '0,01%'],
 ['CA00208D4084', '21.103.029,58', '0,05', '%', 'ARCH CAPITAL GROUP', '0,05%'],
 ['LU1598757687',
  '13.501.363,83',
  '0,03',
  '%',
  'ARCHER-DANIELS-MIDLAND',
  '0,03%'],
 ['BMG0450A1053',
  '17.944.114,01',
  '0,04',
  '%',
  'ARES MANAGEMENT CORP',
  '0,04%'],
 ['US0394831020', '20.379.761,42', '0,05', '%', 'ARGEN X', '0,05%'],
 ['US03990B1017', '53.145.427,91', '0,13', '%', 'ARISTA NETWORKS', '0,13%'],
 ['NL0010832176', '13.312.223,12', '0,03', '%', 'ARISTOCRAT LEISURE', '0,03%'],
 ['US0404132054', '4.706.027,12', '0,01', '%', 'ARKEMA', '0,01%'],
 ['AU000000ALL7',
  '9.740.383,22',
  '0,02',
  '%',
  'ASAHI GROUP HOLDINGS',
  '0,02%'],
 ['FR0010313833', '5.435.328,13', '0,01', '%', 'ASAHI KASEI CORP', '0,01%'],
 ['US3635761097',
  '5.855.330,45',
  '0,01',
  '%',
  'ASE TECHNOLOGY HOLDING',
  '0,01%'],
 ['JP3111200006', '12.821.101,08', '0,03', '%', 'ASHTEAD GROUP', '0,03%'],
 ['TW0003711008',
  '1.699.918,76',
  '0,00',
  '%',
  'ASIA VITAL COMPONENTS',
  '0,00%'],
 ['INE208A01029', '4.077.265,57', '0,01', '%', 'ASIAN PAINTS', '0,01%'],
 ['GB0000536739', '10.472.942,25', '0,03', '%', 'ASICS CORP', '0,03%'],
 ['TW0003017000', '12.399.632,09', '0,03', '%', 'ASM INTERNATIONAL', '0,03%'],
 ['INE021A01026', '164.424.223,09', '0,40', '%', 'ASML HLDG', '0,40%'],
 ['JP3118000003', '9.590.651,43', '0,02', '%', 'ASR NEDERLAND', '0,02%'],
 ['NL0000334118', '17.382.407,36', '0,04', '%', 'ASSA ABLOY B', '0,04%'],
 ['NL0010273215',
  '26.620.513,63',
  '0,07',
  '%',
  'ASSICURAZIONI GENERALI',
  '0,07%'],
 ['US29109X1063',
  '1.539.988,25',
  '0,00',
  '%',
  'ASSOCIATED BRITISH FOODS',
  '0,00%'],
 ['NL0011872643', '8.694.972,08', '0,02', '%', 'ASSURANT', '0,02%'],
 ['SE0007100581', '12.139.089,78', '0,03', '%', 'ASTELLAS PHARMA', '0,03%'],
 ['IT0000062072', '145.536.118,07', '0,36', '%', 'ASTRAZENECA', '0,36%'],
 ['GB0006731235', '4.053.844,46', '0,01', '%', 'ASUSTEK COMPUTER', '0,01%'],
 ['US04621X1081', '2.030.058,21', '0,00', '%', 'ASX', '0,00%'],
 ['JP3942400007', '122.622.704,58', '0,30', '%', 'AT&T', '0,30%'],
 ['GB0009895292', '28.239.144,36', '0,07', '%', 'ATLAS COPCO A', '0,07%'],
 ['TW0002357001', '10.725.040,49', '0,03', '%', 'ATLAS COPCO B', '0,03%'],
 ['AU000000ASX7', '20.390.392,18', '0,05', '%', 'ATLASSIAN (US)', '0,05%'],
 ['US00206R1023', '19.691.483,64', '0,05', '%', 'ATMOS ENERGY CORP', '0,05%'],
 ['SE0017486889',
  '3.835.518,17',
  '0,01',
  '%',
  'AUCKLAND INTL AIRPORT',
  '0,01%'],
 ['US0494681010', '5.093.349,87', '0,01', '%', 'AUTO TRADER GROUP', '0,01%'],
 ['US0495601058', '34.288.371,28', '0,08', '%', 'AUTODESK', '0,08%'],
 ['NZAIAE0002S6',
  '81.774.553,69',
  '0,20',
  '%',
  'AUTOMATIC DATA PROCESS',
  '0,20%'],
 ['TW0002409000', '39.184.549,51', '0,10', '%', 'AUTOZONE', '0,10%'],
 ['GB00BVYVFW23',
  '24.813.950,04',
  '0,06',
  '%',
  'AVALONBAY COMMUNITIES',
  '0,06%'],
 ['US0527691069', '7.287.761,31', '0,02', '%', 'AVANTOR', '0,02%'],
 ['US0530151036', '3.242.394,16', '0,01', '%', 'AVENUE SUPERMARTS', '0,01%'],
 ['US0533321024',
  '10.097.746,66',
  '0,02',
  '%',
  'AVERY DENNISON CORP',
  '0,02%'],
 ['US0534841012', '13.744.839,39', '0,03', '%', 'AVIVA', '0,03%'],
 ['US05352A1007', '650.866,55', '0,00', '%', 'AVOLTA', '0,00%'],
 ['INE192R01011', '54.197.477,97', '0,13', '%', 'AXA', '0,13%'],
 ['US0536111091', '12.298.643,40', '0,03', '%', 'AXIS BANK', '0,03%'],
 ['GB00BPQY8M80', '22.209.565,11', '0,05', '%', 'AXON ENTERPRISE', '0,05%'],
 ['CH0023405456', '1.973.487,28', '0,00', '%', 'AYALA CORP', '0,00%'],
 ['FR0000120628', '4.448.631,28', '0,01', '%', 'AZRIELI GROUP', '0,01%'],
 ['INE238A01034', '7.199.336,95', '0,02', '%', 'B3', '0,02%'],
 ['US05464C1018', '10.798.447,22', '0,03', '%', 'BAIDU (HK)', '0,03%'],
 ['PHY0486V1154', '2.112.435,29', '0,01', '%', 'BAJAJ AUTO', '0,01%'],
 ['IL0011194789', '10.111.353,62', '0,02', '%', 'BAJAJ FINANCE', '0,02%'],
 ['BRB3SAACNOR6', '3.938.202,99', '0,01', '%', 'BAJAJ FINSERV', '0,01%'],
 ['KYG070341048', '31.280.745,61', '0,08', '%', 'BAKER HUGHES CO', '0,08%'],
 ['INE296A01024', '1.726.212,74', '0,00', '%', 'BALOISE HOLDING', '0,00%'],
 ['INE918I01026', '7.023.647,05', '0,02', '%', 'BANCO BPM', '0,02%'],
 ['US05722G1004', '4.852.658,39', '0,01', '%', 'BANCO BRADESCO ON', '0,01%'],
 ['US0584981064', '3.498.421,06', '0,01', '%', 'BANCO BRADESCO PN', '0,01%'],
 ['CH0012410517', '3.441.607,04', '0,01', '%', 'BANCO BTG PACTUAL', '0,01%'],
 ['ES0113211835', '8.095.815,92', '0,02', '%', 'BANCO SABADELL', '0,02%'],
 ['IT0005218380', '58.183.356,56', '0,14', '%', 'BANCO SANTANDER', '0,14%'],
 ['BRBBDCACNOR1', '2.934.114,80', '0,01', '%', 'BANCOLOMBIAPREF', '0,01%'],
 ['BRBBDCACNPR8',
  '11.902.473,98',
  '0,03',
  '%',
  'BANDAI NAMCOHOLDINGS',
  '0,03%'],
 ['BRBPACUNT006',
  '3.284.270,65',
  '0,01',
  '%',
  'BANGKOK DUSITMED SERVI-NVDR',
  '0,01%'],
 ['ES0113860A34', '2.616.921,97', '0,01', '%', 'BANK ALBILAD', '0,01%'],
 ['CLP1506A1070', '10.896.203,99', '0,03', '%', 'BANK CENTRALASIA', '0,03%'],
 ['ES0113900J37', '3.819.627,16', '0,01', '%', 'BANK MANDIRI', '0,01%'],
 ['COB07PA00086', '47.331.586,30', '0,12', '%', 'BANK MONTREAL', '0,12%'],
 ['JP3778630008',
  '43.288.432,91',
  '0,11',
  '%',
  'BANK NEW YORKMELLON',
  '0,11%'],
 ['TH0264010R10', '41.405.599,74', '0,10', '%', 'BANK NOVA SCOTIA', '0,10%'],
 ['SA000A0D9HK3',
  '183.285.409,53',
  '0,45',
  '%',
  'BANK OF AMERICA CORP',
  '0,45%'],
 ['ID1000109507', '17.119.859,53', '0,04', '%', 'BANK OF CHINAH', '0,04%'],
 ['ID1000095003',
  '3.542.106,49',
  '0,01',
  '%',
  'BANK OF COMMU A (HK-C)',
  '0,01%'],
 ['US0605051046',
  '7.174.228,22',
  '0,02',
  '%',
  'BANK OF IRELAND GROUP',
  '0,02%'],
 ['CNE1000001Z5',
  '7.285.780,08',
  '0,02',
  '%',
  'BANK OF PHIL ISLANDS',
  '0,02%'],
 ['IE00BD1RP616',
  '687.815,92',
  '0,00',
  '%',
  'BANQUE CANTONALE VAUDOIS',
  '0,00%'],
 ['CA0636711016', '3.150.775,39', '0,01', '%', 'BANQUE SAUDI FRANSI', '0,01%'],
 ['US0640581007', '32.115.999,66', '0,08', '%', 'BARCLAYS', '0,08%'],
 ['CA0641491075', '7.785.747,03', '0,02', '%', 'BARRATT REDROW', '0,02%'],
 ['PHY0967S1694', '466.602,19', '0,00', '%', 'BARRY CALLEBAUT', '0,00%'],
 ['ID1000118201',
  '2.183.260,03',
  '0,01',
  '%',
  'BARWA REAL ESTATE CO',
  '0,01%'],
 ['CH0531751755',
  '11.869.272,38',
  '0,03',
  '%',
  'BAXTER INTERNATIONAL',
  '0,03%'],
 ['SA0007879782', '13.617.499,02', '0,03', '%', 'BAYER', '0,03%'],
 ['GB0031348658', '43.663.205,89', '0,11', '%', 'BBVA', '0,11%'],
 ['GB0000811801', '3.440.264,37', '0,01', '%', 'BCE INC', '0,01%'],
 ['CH0009002962',
  '6.944.108,89',
  '0,02',
  '%',
  'BCO SANTANDER CHILE (NEW',
  '0,02%'],
 ['QA000A0KD6J5',
  '5.409.683,30',
  '0,01',
  '%',
  'BE SEMICONDUCTOR IND',
  '0,01%'],
 ['US0718131099', '41.843.566,38', '0,10', '%', 'BECTON DICKINSON', '0,10%'],
 ['DE000BAY0017', '5.451.669,32', '0,01', '%', 'BEIERSDORF', '0,01%'],
 ['DE0005190003', '6.713.000,26', '0,02', '%', 'BEIGENE (HK)', '0,02%'],
 ['DE0005190037', '2.975.280,10', '0,01', '%', 'BEIJER REF B', '0,01%'],
 ['CA05534B7604', '2.566.023,30', '0,01', '%', 'BENTLEY SYSTEMS B', '0,01%'],
 ['NL0012866412',
  '14.152.667,20',
  '0,03',
  '%',
  'BERKLEY (W.R.) CORP',
  '0,03%'],
 ['US0758871091', '13.291.657,85', '0,03', '%', 'BEST BUY CO', '0,03%'],
 ['DE0005200000', '5.227.305,79', '0,01', '%', 'BHARAT ELECTRONICS', '0,01%'],
 ['KYG1146Y1017',
  '2.014.295,97',
  '0,00',
  '%',
  'BHARAT PETROLEUM CORP',
  '0,00%'],
 ['US08265T2087', '3.101.176,42', '0,01', '%', 'BID CORPORATION', '0,01%'],
 ['US0865161014', '2.661.251,79', '0,01', '%', 'BIDVEST GROUP', '0,01%'],
 ['INE263A01024',
  '2.182.715,14',
  '0,01',
  '%',
  'BIM BIRLESIK MAGAZALAR',
  '0,01%'],
 ['INE029A01011', '13.580.314,83', '0,03', '%', 'BIOGEN', '0,03%'],
 ['INE397D01024',
  '8.779.914,76',
  '0,02',
  '%',
  'BIOMARIN PHARMACEUTICAL',
  '0,02%'],
 ['ZAE000216537', '5.208.279,18', '0,01', '%', 'BIOMERIEUX', '0,01%'],
 ['ZAE000117321',
  '2.627.587,73',
  '0,01',
  '%',
  'BIO-RAD LABORATORIES A',
  '0,01%'],
 ['TREBIMM00018', '6.048.174,70', '0,01', '%', 'BIO-TECHNE CORP', '0,01%'],
 ['US09062X1037', '6.167.067,93', '0,02', '%', 'BKW', '0,02%'],
 ['US09061G1013', '91.642.870,34', '0,22', '%', 'BLACKROCK', '0,22%'],
 ['FR0013280286', '63.171.136,64', '0,15', '%', 'BLACKSTONE GROUP', '0,15%'],
 ['US0905722072', '17.753.009,84', '0,04', '%', 'BLOCK', '0,04%'],
 ['US09073M1045', '588.080,08', '0,00', '%', 'BLUESCOPE STEEL', '0,00%'],
 ['CH0130293662', '14.646.676,78', '0,04', '%', 'BMW STAMM', '0,04%'],
 ['US09290D1019', '5.611.723,81', '0,01', '%', 'BMW VORZUG', '0,01%'],
 ['US09260D1072', '55.504.887,17', '0,14', '%', 'BNP PARIBAS', '0,14%'],
 ['US8522341036',
  '10.118.357,94',
  '0,02',
  '%',
  'BOC HONG KONG HOLDINGS',
  '0,02%'],
 ['AU000000BSL0', '9.453.535,14', '0,02', '%', 'BOLIDEN', '0,02%'],
 ['FR0000131104', '1.411.060,58', '0,00', '%', 'BOLLORE', '0,00%'],
 ['HK2388011192', '98.001.030,41', '0,24', '%', 'BOOKING HOLDINGS', '0,24%'],
 ['SE0020050417',
  '8.006.717,13',
  '0,02',
  '%',
  'BOOZ ALLEN HAMILTON A',
  '0,02%'],
 ['US09857L1089',
  '98.373.746,13',
  '0,24',
  '%',
  'BOSTON SCIENTIFIC CORP',
  '0,24%'],
 ['US0995021062', '2.271.185,77', '0,01', '%', 'BOUYGUES', '0,01%'],
 ['KYG126521064', '54.993.388,79', '0,13', '%', 'BP', '0,13%'],
 ['US1011211018', '2.266.426,88', '0,01', '%', 'BPER BANCA', '0,01%'],
 ['US1011371077', '20.108.966,94', '0,05', '%', 'BRAMBLES', '0,05%'],
 ['FR0000120503', '6.567.061,85', '0,02', '%', 'BRENNTAG', '0,02%'],
 ['GB0007980591', '16.570.280,61', '0,04', '%', 'BRIDGESTONE CORP', '0,04%'],
 ['IT0000066123',
  '90.300.646,27',
  '0,22',
  '%',
  'BRISTOL-MYERS SQUIBB CO',
  '0,22%'],
 ['AU000000BXB1',
  '2.779.755,98',
  '0,01',
  '%',
  'BRITANNIA INDUSTRIES',
  '0,01%'],
 ['DE000A1DAHH0', '471.000.183,16', '1,15', '%', 'BROADCOM', '1,15%'],
 ['JP3830800003',
  '16.107.944,86',
  '0,04',
  '%',
  'BROADRIDGE FINANCIAL',
  '0,04%'],
 ['US1101221083',
  '9.581.353,59',
  '0,02',
  '%',
  'BROOKFIELD ASSET MAN LTD',
  '0,02%'],
 ['INE216A01030', '44.580.792,39', '0,11', '%', 'BROOKFIELD CORP A', '0,11%'],
 ['US11135F1012',
  '1.902.621,16',
  '0,00',
  '%',
  'BROOKFIELD RENEWABLE',
  '0,00%'],
 ['US11133T1034', '19.114.457,55', '0,05', '%', 'BROWN & BROWN', '0,05%'],
 ['CA1130041058', '1.099.630,67', '0,00', '%', 'BROWN-FORMAN CORP B', '0,00%'],
 ['CA11271J1075', '9.404.685,59', '0,02', '%', 'BT GROUP', '0,02%'],
 ['CA11285B1085',
  '8.759.523,47',
  '0,02',
  '%',
  'BUILDERS FIRSTSOURCE',
  '0,02%'],
 ['US1152361010',
  '1.677.854,72',
  '0,00',
  '%',
  'BUMRUNGRAD HOSPITAL PCL-NVDR',
  '0,00%'],
 ['US1156372096', '10.619.001,57', '0,03', '%', 'BUNGE GLOBAL', '0,03%'],
 ['GB0030913577', '8.872.213,94', '0,02', '%', 'BUNZL', '0,02%'],
 ['TH0168010R13', '8.326.710,31', '0,02', '%', 'BUREAU VERITAS SA', '0,02%'],
 ['CH1300646267', '8.821.300,13', '0,02', '%', 'BURLINGTON STORES', '0,02%'],
 ['GB00B0744B38', '8.806.017,37', '0,02', '%', 'BXP', '0,02%'],

In [94]:
table = pd.DataFrame(tabs3, columns = ["ISIN", "MV(DKK)", "no", "no2", "listed shares", "share"])
table

,ISIN,MV(DKK),no,no2,listed shares,share
0,US88557W1018,"29.605.115,44","0,07",%,3I GROUP,"0,07%"
1,KYG2953R1149,"2.655.026,62","0,01",%,AAC TECHNOLOGIES (CN),"0,01%"
2,GB00B1YW4409,"49.450.996,40","0,12",%,3M CO,"0,12%"
3,US88579Y1010,"2.652.723,48","0,01",%,ABB INDIA,"0,01%"
4,KYG2953R1149,"53.407.655,61","0,13",%,ABB LTD,"0,13%"
...,...,...,...,...,...,...
2882,"Østergade 42-44, Rønn",e,,,None,None
2883,Ålekistevej 68-,,,None,None,None
2884,Ålekistevej 81,,,None,None,None
2885,Ålekistevej 88-,,,None,None,None
2886,"Åmoseparken,",,,None,None,None

In [95]:
table = table.drop(['no', 'no2'], axis=1)

In [99]:
neworder=['listed shares', 'ISIN', 'MV(DKK)', 'share']
table = table[neworder]
table

              listed shares                   ISIN        MV(DKK)  share
0                  3I GROUP           US88557W1018  29.605.115,44  0,07%
1     AAC TECHNOLOGIES (CN)           KYG2953R1149   2.655.026,62  0,01%
2                     3M CO           GB00B1YW4409  49.450.996,40  0,12%
3                 ABB INDIA           US88579Y1010   2.652.723,48  0,01%
4                   ABB LTD           KYG2953R1149  53.407.655,61  0,13%
...                     ...                    ...            ...    ...
2882                   None  Østergade 42-44, Rønn              e   None
2883                   None        Ålekistevej 68-                  None
2884                   None         Ålekistevej 81                  None
2885                   None        Ålekistevej 88-                  None
2886                   None           Åmoseparken,                  None

[2887 rows x 4 columns]

*** idk when to cut the table off - i know the country shares should go but idk if bonds do as well (and then do i inclue the totals too)