In [1]:
import pdfplumber
import pandas as pd

In [2]:
pdf = pdfplumber.open("stichting_pensioenfonds_ABP.pdf")

In [3]:
tabs = []

for page in pdf.pages:
    tabs.append(page.extract_tables(table_settings={"vertical_strategy": "lines", "join_y_tolerance": 50}))

tabs

[[[['Beursgenoteerde', ''], ['beleggingen', None]]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['', ''],
   ['Afrika', '625'],
   ['Zuid-Afrika', '625'],
   ['Absa Group Ltd', '5'],
   ['Anglo American Platinum Ltd', '1'],
   ['Anglogold Ashanti Plc', '29'],
   ['Aspen Pharmacare Holdings Ltd', '1'],
   ['AVI Ltd', '7'],
   ['Bid Corp Ltd', '8'],
   ['Bidvest Group Ltd', '1'],
   ['Capitec Bank Holdings Ltd', '55'],
   ['Clicks Group Ltd', '25'],
   ['Discovery Ltd', '5'],
   ['FirstRand Ltd', '90'],
   ['Foschini Group Ltd', '1'],
   ['Gold Fields Ltd', '85'],
   ['Hyprop Investments Ltd', '2'],
   ['Impala Platinum Holdings Ltd', '32'],
   ['Investec Ltd', '8'],
   ['Life Healthcare Group Holdings Ltd', '1'],
   ['Momentum Group Ltd', '2'],
   ['Mr Price Group Ltd', '9'],
   ['MTN Group Ltd', '17'],
   ['Naspers Ltd', '117'],
   ['Nedbank Group Ltd', '6'],
   ['NEPI Rockcastle NV', '4'],
   ['Old Mutual Ltd', '5']],
  [['Regio / Land / Uitgever', 'Waarde'],
   ['Omnia Holdings Ltd', '1'],
   ['OUTsurance Group Ltd', '16'],
   ['Remgro Ltd', '1'],
   ['Sanlam Ltd', '34'],
   ['Sappi Ltd', '2'],
   ['Shoprite Holdings Ltd', '33'],
   ['Standard Bank Group Ltd', '22'],
   ['Telkom SA SOC Ltd', '1'],
   ['Vodacom Group Ltd', '1'],
   ['Vukile Property Fund Ltd', '1'],
   ['Woolworths Holdings Ltd/South Africa', '1'],
   ['Azië', '34.689'],
   ['China', '8.307'],
   ['3SBio Inc', '6'],
   ['AAC Technologies Holdings Inc', '19'],
   ['Agricultural Bank of China Ltd', '60'],
   ['Akeso Inc', '1'],
   ['Alibaba Group Holding Ltd', '586'],
   ['Anhui Conch Cement Co Ltd', '10'],
   ['Anker Innovations Technology Co Ltd', '10'],
   ['Atour Lifestyle Holdings Ltd', '17'],
   ['Autohome Inc', '25'],
   ['Baidu Inc', '54'],
   ['Bank of China \xad Luxembourg Branch', '41'],
   ['Bank of Communications Co Ltd', '2']]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['Bank of Ningbo Co Ltd', '3'],
   ['BeiGene Ltd', '2'],
   ['Beijing Jingneng Clean Energy Co Ltd', '1'],
   ['Beijing Kingsoft Office Software Inc', '1'],
   ['Beijing New Building Materials PLC', '5'],
   ['Beijing Oriental Yuhong Waterproof Technology Co Ltd', '15'],
   ['Bilibili Inc', '13'],
   ['BOC Aviation Ltd', '2'],
   ['BOE Technology Group Co Ltd', '31'],
   ['Bosideng International Holdings Ltd', '31'],
   ['Centre Testing International Group Co Ltd', '26'],
   ['CGN Power Co Ltd', '1'],
   ['China BlueChemical Ltd', '4'],
   ['China CITIC Bank Corp Ltd', '6'],
   ['China Communications Services Corp Ltd', '2'],
   ['China Construction Bank Corp', '242'],
   ['China CSSC Holdings Ltd', '2'],
   ['China Everbright Bank Co Ltd', '6'],
   ['China Feihe Ltd', '6'],
   ['China Galaxy Securities Co Ltd', '8'],
   ['China Hongqiao Group Ltd', '13'],
   ['China International Capital Corp Ltd', '16'],
   ['China International Marine Containers Group Co Ltd', '1'],
   ['China Life Insurance Co Ltd', '9'],
   ['China Medical System Holdings Ltd', '7'],
   ['China Meidong Auto Holdings Ltd', '4'],
   ['China Mengniu Dairy Co Ltd', '17'],
   ['China Merchants Bank Co Ltd', '179']],
  [['Regio / Land / Uitgever', 'Waarde'],
   ['China Merchants Shekou Industrial Zone Holdings Co Ltd', '8'],
   ['China Minsheng Banking Corp Ltd', '1'],
   ['China Nonferrous Mining Corp Ltd', '2'],
   ['China Overseas Land & Investment Ltd', '72'],
   ['China Overseas Property Holdings Ltd', '1'],
   ['China Pacific Insurance Group Co Ltd', '51'],
   ['China Railway Group Ltd', '1'],
   ['China Resources Beer Holdings Co Ltd', '52'],
   ['China Resources Beverage Holdings Co Ltd', '10'],
   ['China Resources Gas Group Ltd', '12'],
   ['China Resources Land Ltd', '470'],
   ['China Resources Mixc Lifestyle Services Ltd', '3'],
   ['China South Publishing & Media Group Co Ltd', '8'],
   ['China State Construction International Holdings Ltd', '1'],
   ['China Taiping Insurance Holdings Co Ltd', '13'],
   ['China Tower Corp Ltd', '8'],
   ['China Yangtze Power Co Ltd', '31'],
   ['Chongqing Rural Commercial Bank Co Ltd', '6'],
   ['Chow Tai Fook Jewellery Group Ltd', '4'],
   ['CITIC Securities Co Ltd', '3'],
   ['CMOC Group Ltd', '20'],
   ['Consun Pharmaceutical Group Ltd', '7'],
   ['Contemporary Amperex Technology Co Ltd', '283'],
   ['COSCO SHIPPING Holdings Co Ltd', '1'],
   ['Country Garden Services Holdings Co Ltd', '4'],
   ['CRRC Corp Ltd', '9'],
   ['CSPC Pharmaceutical Group Ltd', '1'],
   ['Dongyue Group Ltd', '3']]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['East Money Information Co Ltd', '3'],
   ['ENN Energy Holdings Ltd', '68'],
   ['FinVolution Group', '5'],
   ['Founder Securities Co Ltd', '1'],
   ['Full Truck Alliance Co Ltd', '44'],
   ['Fuyao Glass Industry Group Co Ltd', '22'],
   ['GCL Technology Holdings Ltd', '1'],
   ['GDS Holdings Ltd', '14'],
   ['Geely Automobile Holdings Ltd', '9'],
   ['GF Securities Co Ltd', '8'],
   ['Giant Biogene Holding Co ltd', '3'],
   ['Gree Electric Appliances Inc of Zhuhai', '30'],
   ['Greentown Service Group Co Ltd', '1'],
   ['Guoyuan Securities Co Ltd', '4'],
   ['H World Group Ltd', '23'],
   ['Haidilao International Holding Ltd', '7'],
   ['Haier Smart Home Co Ltd', '128'],
   ['Haitong Securities Co Ltd', '1'],
   ['Hansoh Pharmaceutical Group Co Ltd', '6'],
   ['Hisense Home Appliances Group Co Ltd', '4'],
   ['Hisense Visual Technology Co Ltd', '3'],
   ['HLA Group Corp Ltd', '9'],
   ['Huatai Securities Co Ltd', '17'],
   ['Huaxia Bank Co Ltd', '33'],
   ['Hubei Dinglong Co Ltd', '2'],
   ['Hygon Information Technology Co Ltd', '11'],
   ['Industrial & Commercial Bank Of China, Luxembourg Branch', '156'],
   ['Inner Mongolia Yili Industrial Group Co Ltd', '85']],
  [['Regio / Land / Uitgever', 'Waarde'],
   ['Innovent Biologics Inc', '3'],
   ['JD Health International Inc', '1'],
   ['JD Logistics Inc', '2'],
   ['JD.com Inc', '194'],
   ['Jiangsu Hengrui Pharmaceuticals Co Ltd', '2'],
   ['Jinduicheng Molybdenum Co Ltd', '5'],
   ['JNBY Design Ltd', '1'],
   ['Joincare Pharmaceutical Group Industry Co Ltd', '3'],
   ['JOYY Inc', '3'],
   ['Kanzhun Ltd', '3'],
   ['KE Holdings Inc', '54'],
   ['Kingdee International Software Group Co Ltd', '3'],
   ['Kingnet Network Co Ltd', '9'],
   ['Kingsoft Corp Ltd', '32'],
   ['Kuaishou Technology', '100'],
   ['Kweichow Moutai Co Ltd', '31'],
   ['Lenovo Group Ltd', '59'],
   ['Li Auto Inc', '71'],
   ['Longfor Group Holdings Ltd', '31'],
   ['Meituan', '431'],
   ['Midea Group Co Ltd', '120'],
   ['Minth Group Ltd', '18'],
   ['MMG Ltd', '24'],
   ['NARI Technology Co Ltd', '61'],
   ['NetEase Cloud Music Inc', '1'],
   ['NetEase Inc', '136'],
   ['New China Life Insurance Co Ltd', '2'],
   ['New Oriental Education & Technology Group Inc', '21']]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['Ningbo Ronbay New Energy Technology Co Ltd', '17'],
   ['NIO Inc', '1'],
   ['Nongfu Spring Co Ltd', '1'],
   ['Orient Securities Co Ltd/China', '5'],
   ['PDD Holdings Inc', '205'],
   ['PICC Property & Casualty Co Ltd', '80'],
   ['Ping An Insurance Group Co of China Ltd', '315'],
   ['Pop Mart International Group Ltd', '19'],
   ['Postal Savings Bank of China Co Ltd', '6'],
   ['Qifu Technology Inc', '40'],
   ['Sany Heavy Industry Co Ltd', '47'],
   ['SF Holding Co Ltd', '22'],
   ['SG Micro Corp', '18'],
   ['Shandong Himile Mechanical Science & Technology Co Ltd', '7'],
   ['Shandong Hi\xadspeed Co Ltd', '15'],
   ['Shandong Nanshan Aluminum Co Ltd', '14'],
   ['Shandong Weigao Group Medical Polymer Co Ltd', '6'],
   ['Shanghai Chicmax Cosmetic Co Ltd', '2'],
   ['Shanghai Pudong Development Bank Co Ltd', '28'],
   ['Shanghai Rural Commercial Bank Co Ltd', '1'],
   ['Shenzhen Inovance Technology Co Ltd', '29'],
   ['Shenzhen Mindray Bio\xadMedical Electronics Co Ltd', '44'],
   ['Shenzhen New Industries Biomedical Engineering Co Ltd', '25'],
   ['Shenzhou International Group Holdings Ltd', '31'],
   ['Sieyuan Electric Co Ltd', '21'],
   ['Sino Biopharmaceutical Ltd', '10'],
   ['Sinopharm Group Co Ltd', '1'],
   ['Sunac Services Holdings Ltd', '1']],
  [['Regio / Land / Uitgever', 'Waarde'],
   ['Sungrow Power Supply Co Ltd', '10'],
   ['Sunny Optical Technology Group Co Ltd', '36'],
   ['Sunwoda Electronic Co Ltd', '3'],
   ['Tencent Holdings Ltd', '1.578'],
   ['Tencent Music Entertainment Group', '29'],
   ['Tingyi Cayman Islands Holding Corp', '21'],
   ['Tongcheng Travel Holdings Ltd', '38'],
   ['Tongwei Co Ltd', '25'],
   ['Trip.com Group Ltd', '212'],
   ['Tsingtao Brewery Co Ltd', '2'],
   ['Universal Scientific Industrial Shanghai Co Ltd', '12'],
   ['Vipshop Holdings Ltd', '34'],
   ['Wanhua Chemical Group Co Ltd', '16'],
   ['Want Want China Holdings Ltd', '1'],
   ['Weichai Power Co Ltd', '44'],
   ['Western Mining Co Ltd', '13'],
   ['Will Semiconductor Co Ltd Shanghai', '9'],
   ['Wuliangye Yibin Co Ltd', '43'],
   ['WuXi AppTec Co Ltd', '1'],
   ['Wuxi Biologics Cayman Inc', '9'],
   ['Xiaomi Corp', '151'],
   ['Xinyi Solar Holdings Ltd', '14'],
   ['XPeng Inc', '4'],
   ['Xtep International Holdings Ltd', '5'],
   ['Yadea Group Holdings Ltd', '12'],
   ['Yealink Network Technology Corp Ltd', '4'],
   ['Yifeng Pharmacy Chain Co Ltd', '23'],
   ['Yum China Holdings Inc', '13']]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['Yunnan Yuntianhua Co Ltd', '29'],
   ['Yutong Bus Co Ltd', '26'],
   ['Zhejiang Longsheng Group Co Ltd', '28'],
   ['Zhejiang Semir Garment Co Ltd', '1'],
   ['Zhejiang Supor Co Ltd', '30'],
   ['Zhongsheng Group Holdings Ltd', '21'],
   ['Zijin Mining Group Co Ltd', '61'],
   ['ZTE Corp', '19'],
   ['ZTO Express Cayman Inc', '38'],
   ['Filippijnen', '454'],
   ['Ayala Land Inc', '59'],
   ['Bank of the Philippine Islands', '26'],
   ['BDO Unibank Inc', '34'],
   ['Bloomberry Resorts Corp', '5'],
   ['DigiPlus Interactive Corp', '1'],
   ['International Container Terminal Services Inc', '18'],
   ['Metropolitan Bank & Trust Co', '8'],
   ['SM Investments Corp', '7'],
   ['SM Prime Holdings Inc', '297'],
   ['Hong Kong', '1.906'],
   ['AIA Group Ltd', '182'],
   ['CLP Holdings Ltd', '35'],
   ['ESR Group Ltd', '309'],
   ['Futu Holdings Ltd', '15'],
   ['Hang Lung Properties Ltd', '88'],
   ['Hang Seng Bank Ltd', '19']],
  [['Regio / Land / Uitgever', 'Waarde'],
   ['Henderson Land Development Co Ltd', '9'],
   ['HKT Trust & HKT Ltd', '10'],
   ['Hong Kong & China Gas Co Ltd', '18'],
   ['Hong Kong Exchanges & Clearing Ltd', '99'],
   ['Hongkong Land Holdings Ltd', '45'],
   ['HSBC Holdings PLC', '480'],
   ['Link REIT', '305'],
   ['MTR Corp Ltd', '12'],
   ['Sun Hung Kai Properties Ltd', '122'],
   ['Swire Pacific Ltd', '8'],
   ['Swire Properties Ltd', '18'],
   ['Techtronic Industries Co Ltd', '43'],
   ['Wharf Holdings Ltd/The', '3'],
   ['Wharf Real Estate Investment Co Ltd', '88'],
   ['', ''],
   ['India', '4.456'],
   ['ABB India Ltd', '51'],
   ['Alkem Laboratories Ltd', '3'],
   ['Ambuja Cements Ltd', '1'],
   ['Anant Raj Ltd', '4'],
   ['Apollo Hospitals Enterprise Ltd', '37'],
   ['Ashok Leyland Ltd', '1'],
   ['Ashoka Buildcon Ltd', '6'],
   ['Asian Paints Ltd', '2'],
   ['Astral Ltd', '1'],
   ['Aurobindo Pharma Ltd', '4'],
   ['Avenue Supermarts Ltd', '1'],
   ['Axis Bank Ltd', '117']]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['Bajaj Auto Ltd', '23'],
   ['Bajaj Finance Ltd', '47'],
   ['Bajaj Finserv Ltd', '3'],
   ['Bajaj Holdings & Investment Ltd', '1'],
   ['Bajaj Housing Finance Ltd', '5'],
   ['Balkrishna Industries Ltd', '1'],
   ['Bank of Baroda', '24'],
   ['Bharat Forge Ltd', '8'],
   ['Bharti Airtel Ltd', '152'],
   ['Bharti Hexacom Ltd', '25'],
   ['Birlasoft Ltd', '2'],
   ['Blue Star Ltd', '25'],
   ['Britannia Industries Ltd', '8'],
   ['Can Fin Homes Ltd', '1'],
   ['Canara Bank', '11'],
   ['Ceat Ltd', '5'],
   ['CG Power & Industrial Solutions Ltd', '1'],
   ['Chambal Fertilisers and Chemicals Ltd', '1'],
   ['Cholamandalam Financial Holdings Ltd', '6'],
   ['Cholamandalam Investment and Finance Co Ltd', '59'],
   ['Cipla Ltd/India', '37'],
   ['CMS Info Systems Ltd', '2'],
   ['Coforge Ltd', '10'],
   ['Colgate\xadPalmolive India Ltd', '28'],
   ['Computer Age Management Services Ltd', '16'],
   ['Craftsman Automation Ltd', '12'],
   ['CRISIL Ltd', '3'],
   ['Cummins India Ltd', '7']],
  [['Regio / Land / Uitgever', 'Waarde'],
   ['Dabur India Ltd', '1'],
   ['Delhivery Ltd', '12'],
   ['Divi’s Laboratories Ltd', '1'],
   ['Dixon Technologies India Ltd', '15'],
   ['DLF Ltd', '83'],
   ['Dr Reddy’s Laboratories Ltd', '6'],
   ['Edelweiss Financial Services Ltd', '1'],
   ['Eicher Motors Ltd', '64'],
   ['EID Parry India Ltd', '1'],
   ['Embassy Office Parks REIT', '22'],
   ['Entero Healthcare Solutions Ltd', '15'],
   ['EPL Ltd', '2'],
   ['Escorts Kubota Ltd', '10'],
   ['Finolex Cables Ltd', '1'],
   ['Force Motors Ltd', '2'],
   ['Fortis Healthcare Ltd', '10'],
   ['GlaxoSmithKline Pharmaceuticals Ltd', '1'],
   ['Glenmark Pharmaceuticals Ltd', '22'],
   ['Global Health Ltd/India', '15'],
   ['GMR Airports Ltd', '30'],
   ['Godawari Power and Ispat Ltd', '7'],
   ['Godrej Consumer Products Ltd', '1'],
   ['Godrej Properties Ltd', '72'],
   ['Grasim Industries Ltd', '1'],
   ['Gujarat Pipavav Port Ltd', '10'],
   ['Gujarat State Petronet Ltd', '1'],
   ['Havells India Ltd', '27'],
   ['HCL Technologies Ltd', '83']]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['HDFC Asset Management Co Ltd', '14'],
   ['HDFC Bank Ltd', '416'],
   ['HDFC Life Insurance Co Ltd', '23'],
   ['Hero MotoCorp Ltd', '8'],
   ['Hindalco Industries Ltd', '25'],
   ['Hindustan Aeronautics Ltd', '39'],
   ['Hindustan Unilever Ltd', '25'],
   ['Home First Finance Co India Ltd', '6'],
   ['ICICI Bank Ltd', '301'],
   ['ICICI Lombard General Insurance Co Ltd', '10'],
   ['ICICI Prudential Life Insurance Co Ltd', '17'],
   ['ICICI Securities Ltd', '1'],
   ['IIFL Finance Ltd', '1'],
   ['IndiaMart InterMesh Ltd', '6'],
   ['Indian Energy Exchange Ltd', '4'],
   ['Indian Hotels Co Ltd/The', '63'],
   ['Indraprastha Gas Ltd', '3'],
   ['Indus Towers Ltd', '5'],
   ['Info Edge India Ltd', '27'],
   ['Infosys Ltd', '264'],
   ['InterGlobe Aviation Ltd', '22'],
   ['Inventurus Knowledge Solutions Ltd', '4'],
   ['ITD Cementation India Ltd', '2'],
   ['Jamna Auto Industries Ltd', '2'],
   ['JB Chemicals & Pharmaceuticals Ltd', '4'],
   ['Jio Financial Services Ltd', '17'],
   ['JSW Steel Ltd', '1'],
   ['Jubilant Foodworks Ltd', '1']],
  [['Regio / Land / Uitgever', 'Waarde'],
   ['Jyothy Labs Ltd', '1'],
   ['Kalyan Jewellers India Ltd', '16'],
   ['Karur Vysya Bank Ltd/The', '7'],
   ['Kfin Technologies Ltd', '7'],
   ['Kirloskar Brothers Ltd', '1'],
   ['Kirloskar Oil Engines Ltd', '2'],
   ['Kotak Mahindra Bank Ltd', '4'],
   ['KPIT Technologies Ltd', '13'],
   ['Lemon Tree Hotels Ltd', '198'],
   ['LIC Housing Finance Ltd', '9'],
   ['Lupin Ltd', '63'],
   ['Macrotech Developers Ltd', '98'],
   ['Mahanagar Gas Ltd', '20'],
   ['Mahindra & Mahindra Ltd', '36'],
   ['MakeMyTrip Ltd', '28'],
   ['Manappuram Finance Ltd', '6'],
   ['Mankind Pharma Ltd', '3'],
   ['Marico Ltd', '1'],
   ['Maruti Suzuki India Ltd', '4'],
   ['Max Healthcare Institute Ltd', '49'],
   ['Motilal Oswal Financial Services Ltd', '8'],
   ['Mphasis Ltd', '10'],
   ['MRF Ltd', '1'],
   ['Multi Commodity Exchange of India Ltd', '9'],
   ['Muthoot Finance Ltd', '3'],
   ['NCC Ltd/India', '2'],
   ['Nestle India Ltd', '1'],
   ['NIIT Learning Systems Ltd', '1']]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['Nippon Life India Asset Management Ltd', '3'],
   ['NTPC Ltd', '20'],
   ['Nuvama Wealth Management Ltd', '2'],
   ['Oberoi Realty Ltd', '22'],
   ['Oracle Financial Services Software Ltd', '5'],
   ['Page Industries Ltd', '11'],
   ['Paradeep Phosphates Ltd', '4'],
   ['Patanjali Foods Ltd', '17'],
   ['PB Fintech Ltd', '21'],
   ['Persistent Systems Ltd', '29'],
   ['Phoenix Mills Ltd/The', '44'],
   ['PI Industries Ltd', '27'],
   ['Pidilite Industries Ltd', '12'],
   ['Piramal Enterprises Ltd', '2'],
   ['PNB Housing Finance Ltd', '9'],
   ['Polycab India Ltd', '4'],
   ['Power Grid Corp of India Ltd', '122'],
   ['Prestige Estates Projects Ltd', '46'],
   ['PTC India Ltd', '8'],
   ['Punjab National Bank', '5'],
   ['Rainbow Children’s Medicare Ltd', '17'],
   ['Ramco Cements Ltd/The', '1'],
   ['Ramkrishna Forgings Ltd', '2'],
   ['REC Ltd', '49'],
   ['Reliance Infrastructure Ltd', '1'],
   ['Samvardhana Motherson International Ltd', '16'],
   ['SBI Life Insurance Co Ltd', '38'],
   ['Shree Cement Ltd', '1']],
  [['Regio / Land / Uitgever', 'Waarde'],
   ['Shriram Finance Ltd', '41'],
   ['SignatureGlobal India Ltd', '1'],
   ['Sona Blw Precision Forgings Ltd', '15'],
   ['SRF Ltd', '1'],
   ['State Bank of India', '51'],
   ['Sun Pharmaceutical Industries Ltd', '50'],
   ['Supreme Industries Ltd', '4'],
   ['Suzlon Energy Ltd', '1'],
   ['Tata Consultancy Services Ltd', '179'],
   ['Tata Elxsi Ltd', '1'],
   ['Tata Motors Ltd', '23'],
   ['Tata Power Co Ltd/The', '1'],
   ['Tata Steel Ltd', '2'],
   ['Tech Mahindra Ltd', '6'],
   ['Titagarh Rail System Ltd', '6'],
   ['Titan Co Ltd', '10'],
   ['Torrent Pharmaceuticals Ltd', '49'],
   ['Torrent Power Ltd', '1'],
   ['Transport Corp of India Ltd', '1'],
   ['Trent Ltd', '31'],
   ['Triveni Turbine Ltd', '13'],
   ['Tube Investments of India Ltd', '17'],
   ['TVS Motor Co Ltd', '1'],
   ['UltraTech Cement Ltd', '48'],
   ['Union Bank of India Ltd', '5'],
   ['United Spirits Ltd', '1'],
   ['UPL Ltd', '30'],
   ['Varun Beverages Ltd', '58']]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['Vodafone Idea Ltd', '10'],
   ['Voltas Ltd', '1'],
   ['Welspun Living Ltd', '1'],
   ['Westlife Foodworld Ltd', '13'],
   ['Wipro Ltd', '9'],
   ['Zensar Technologies Ltd', '4'],
   ['Zomato Ltd', '55'],
   ['Indonesië', '508'],
   ['Amman Mineral Internasional PT', '1'],
   ['Aspirasi Hidup Indonesia Tbk PT', '1'],
   ['Bank Central Asia Tbk PT', '139'],
   ['Bank Mandiri Persero Tbk PT', '48'],
   ['Bank Negara Indonesia Persero Tbk PT', '66'],
   ['Bank Rakyat Indonesia Persero Tbk PT', '133'],
   ['Chandra Asri Pacific Tbk PT', '1'],
   ['Daya Intiguna Yasa Tbk PT', '13'],
   ['GoTo Gojek Tokopedia Tbk PT', '1'],
   ['Indosat Tbk PT', '20'],
   ['Japfa Comfeed Indonesia Tbk PT', '2'],
   ['Semen Indonesia Persero Tbk PT', '8'],
   ['Sumber Alfaria Trijaya Tbk PT', '20'],
   ['Telkom Indonesia Persero Tbk PT', '35'],
   ['Vale Indonesia Tbk PT', '22'],
   ['Israël', '72'],
   ['Azrieli Group Ltd', '5'],
   ['Check Point Software Technologies Ltd', '39']],
  [['Regio / Land / Uitgever', 'Waarde'],
   ['Nova Ltd', '12'],
   ['Phoenix Financial Ltd', '3'],
   ['Tower Semiconductor Ltd', '12'],
   ['Japan', '7.686'],
   ['Advantest Corp', '71'],
   ['Aeon Co Ltd', '45'],
   ['Air Water Inc', '6'],
   ['Aisin Corp', '16'],
   ['Ajinomoto Co Inc', '47'],
   ['Amada Co Ltd', '7'],
   ['ANA Holdings Inc', '6'],
   ['Asahi Intecc Co Ltd', '9'],
   ['Asahi Kasei Corp', '21'],
   ['Asics Corp', '35'],
   ['Astellas Pharma Inc', '41'],
   ['Azbil Corp', '9'],
   ['Bridgestone Corp', '48'],
   ['Brother Industries Ltd', '10'],
   ['Central Japan Railway Co', '85'],
   ['Chiba Bank Ltd/The', '12'],
   ['Chugai Pharmaceutical Co Ltd', '68'],
   ['Concordia Financial Group Ltd', '14'],
   ['Dai Nippon Printing Co Ltd', '15'],
   ['Daifuku Co Ltd', '44'],
   ['Dai\xadichi Life Holdings Inc', '57'],
   ['Daiichi Sankyo Co Ltd', '120']]],
 [[['Regio / Land / Uitgever', 'Waarde'],
   ['Daito Trust Construction Co Ltd', '15'],
   ['Daiwa House Industry Co Ltd', '47'],
   ['Daiwa House REIT Investment Corp', '26'],
   ['Daiwa Securities Group Inc', '20'],
   ['Dentsu Group Inc', '12'],
   ['Disco Corp', '420'],
   ['East Japan Railway Co', '46'],
   ['Ebara Corp', '16'],
   ['Eisai Co Ltd', '18'],
   ['FANUC Corp', '55'],
   ['Fast Retailing Co Ltd', '192'],
   ['Fuji Electric Co Ltd', '18'],
   ['FUJIFILM Holdings Corp', '60'],
   ['Fujikura Ltd', '25'],
   ['Fujitsu Ltd', '74'],
   ['Fukuoka Financial Group Inc', '10'],

In [4]:
tabs2 = sum(tabs, [])
tabs3 = sum(tabs2, [])
tabs3

[['Beursgenoteerde', ''],
 ['beleggingen', None],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['', ''],
 ['Afrika', '625'],
 ['Zuid-Afrika', '625'],
 ['Absa Group Ltd', '5'],
 ['Anglo American Platinum Ltd', '1'],
 ['Anglogold Ashanti Plc', '29'],
 ['Aspen Pharmacare Holdings Ltd', '1'],
 ['AVI Ltd', '7'],
 ['Bid Corp Ltd', '8'],
 ['Bidvest Group Ltd', '1'],
 ['Capitec Bank Holdings Ltd', '55'],
 ['Clicks Group Ltd', '25'],
 ['Discovery Ltd', '5'],
 ['FirstRand Ltd', '90'],
 ['Foschini Group Ltd', '1'],
 ['Gold Fields Ltd', '85'],
 ['Hyprop Investments Ltd', '2'],
 ['Impala Platinum Holdings Ltd', '32'],
 ['Investec Ltd', '8'],
 ['Life Healthcare Group Holdings Ltd', '1'],
 ['Momentum Group Ltd', '2'],
 ['Mr Price Group Ltd', '9'],
 ['MTN Group Ltd', '17'],
 ['Naspers Ltd', '117'],
 ['Nedbank Group Ltd', '6'],
 ['NEPI Rockcastle NV', '4'],
 ['Old Mutual Ltd', '5'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Omnia Holdings Ltd', '1'],
 ['OUTsurance Group Ltd', '16'],
 ['Remgro Ltd', '1'],
 ['Sanlam Ltd', '34'],
 ['Sappi Ltd', '2'],
 ['Shoprite Holdings Ltd', '33'],
 ['Standard Bank Group Ltd', '22'],
 ['Telkom SA SOC Ltd', '1'],
 ['Vodacom Group Ltd', '1'],
 ['Vukile Property Fund Ltd', '1'],
 ['Woolworths Holdings Ltd/South Africa', '1'],
 ['Azië', '34.689'],
 ['China', '8.307'],
 ['3SBio Inc', '6'],
 ['AAC Technologies Holdings Inc', '19'],
 ['Agricultural Bank of China Ltd', '60'],
 ['Akeso Inc', '1'],
 ['Alibaba Group Holding Ltd', '586'],
 ['Anhui Conch Cement Co Ltd', '10'],
 ['Anker Innovations Technology Co Ltd', '10'],
 ['Atour Lifestyle Holdings Ltd', '17'],
 ['Autohome Inc', '25'],
 ['Baidu Inc', '54'],
 ['Bank of China \xad Luxembourg Branch', '41'],
 ['Bank of Communications Co Ltd', '2'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Bank of Ningbo Co Ltd', '3'],
 ['BeiGene Ltd', '2'],
 ['Beijing Jingneng Clean Energy Co Ltd', '1'],
 ['Beijing Kingsoft Office Software Inc', '1'],
 ['Beijing New Building Materials PLC', '5'],
 ['Beijing Oriental Yuhong Waterproof Technology Co Ltd', '15'],
 ['Bilibili Inc', '13'],
 ['BOC Aviation Ltd', '2'],
 ['BOE Technology Group Co Ltd', '31'],
 ['Bosideng International Holdings Ltd', '31'],
 ['Centre Testing International Group Co Ltd', '26'],
 ['CGN Power Co Ltd', '1'],
 ['China BlueChemical Ltd', '4'],
 ['China CITIC Bank Corp Ltd', '6'],
 ['China Communications Services Corp Ltd', '2'],
 ['China Construction Bank Corp', '242'],
 ['China CSSC Holdings Ltd', '2'],
 ['China Everbright Bank Co Ltd', '6'],
 ['China Feihe Ltd', '6'],
 ['China Galaxy Securities Co Ltd', '8'],
 ['China Hongqiao Group Ltd', '13'],
 ['China International Capital Corp Ltd', '16'],
 ['China International Marine Containers Group Co Ltd', '1'],
 ['China Life Insurance Co Ltd', '9'],
 ['China Medical System Holdings Ltd', '7'],
 ['China Meidong Auto Holdings Ltd', '4'],
 ['China Mengniu Dairy Co Ltd', '17'],
 ['China Merchants Bank Co Ltd', '179'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['China Merchants Shekou Industrial Zone Holdings Co Ltd', '8'],
 ['China Minsheng Banking Corp Ltd', '1'],
 ['China Nonferrous Mining Corp Ltd', '2'],
 ['China Overseas Land & Investment Ltd', '72'],
 ['China Overseas Property Holdings Ltd', '1'],
 ['China Pacific Insurance Group Co Ltd', '51'],
 ['China Railway Group Ltd', '1'],
 ['China Resources Beer Holdings Co Ltd', '52'],
 ['China Resources Beverage Holdings Co Ltd', '10'],
 ['China Resources Gas Group Ltd', '12'],
 ['China Resources Land Ltd', '470'],
 ['China Resources Mixc Lifestyle Services Ltd', '3'],
 ['China South Publishing & Media Group Co Ltd', '8'],
 ['China State Construction International Holdings Ltd', '1'],
 ['China Taiping Insurance Holdings Co Ltd', '13'],
 ['China Tower Corp Ltd', '8'],
 ['China Yangtze Power Co Ltd', '31'],
 ['Chongqing Rural Commercial Bank Co Ltd', '6'],
 ['Chow Tai Fook Jewellery Group Ltd', '4'],
 ['CITIC Securities Co Ltd', '3'],
 ['CMOC Group Ltd', '20'],
 ['Consun Pharmaceutical Group Ltd', '7'],
 ['Contemporary Amperex Technology Co Ltd', '283'],
 ['COSCO SHIPPING Holdings Co Ltd', '1'],
 ['Country Garden Services Holdings Co Ltd', '4'],
 ['CRRC Corp Ltd', '9'],
 ['CSPC Pharmaceutical Group Ltd', '1'],
 ['Dongyue Group Ltd', '3'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['East Money Information Co Ltd', '3'],
 ['ENN Energy Holdings Ltd', '68'],
 ['FinVolution Group', '5'],
 ['Founder Securities Co Ltd', '1'],
 ['Full Truck Alliance Co Ltd', '44'],
 ['Fuyao Glass Industry Group Co Ltd', '22'],
 ['GCL Technology Holdings Ltd', '1'],
 ['GDS Holdings Ltd', '14'],
 ['Geely Automobile Holdings Ltd', '9'],
 ['GF Securities Co Ltd', '8'],
 ['Giant Biogene Holding Co ltd', '3'],
 ['Gree Electric Appliances Inc of Zhuhai', '30'],
 ['Greentown Service Group Co Ltd', '1'],
 ['Guoyuan Securities Co Ltd', '4'],
 ['H World Group Ltd', '23'],
 ['Haidilao International Holding Ltd', '7'],
 ['Haier Smart Home Co Ltd', '128'],
 ['Haitong Securities Co Ltd', '1'],
 ['Hansoh Pharmaceutical Group Co Ltd', '6'],
 ['Hisense Home Appliances Group Co Ltd', '4'],
 ['Hisense Visual Technology Co Ltd', '3'],
 ['HLA Group Corp Ltd', '9'],
 ['Huatai Securities Co Ltd', '17'],
 ['Huaxia Bank Co Ltd', '33'],
 ['Hubei Dinglong Co Ltd', '2'],
 ['Hygon Information Technology Co Ltd', '11'],
 ['Industrial & Commercial Bank Of China, Luxembourg Branch', '156'],
 ['Inner Mongolia Yili Industrial Group Co Ltd', '85'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Innovent Biologics Inc', '3'],
 ['JD Health International Inc', '1'],
 ['JD Logistics Inc', '2'],
 ['JD.com Inc', '194'],
 ['Jiangsu Hengrui Pharmaceuticals Co Ltd', '2'],
 ['Jinduicheng Molybdenum Co Ltd', '5'],
 ['JNBY Design Ltd', '1'],
 ['Joincare Pharmaceutical Group Industry Co Ltd', '3'],
 ['JOYY Inc', '3'],
 ['Kanzhun Ltd', '3'],
 ['KE Holdings Inc', '54'],
 ['Kingdee International Software Group Co Ltd', '3'],
 ['Kingnet Network Co Ltd', '9'],
 ['Kingsoft Corp Ltd', '32'],
 ['Kuaishou Technology', '100'],
 ['Kweichow Moutai Co Ltd', '31'],
 ['Lenovo Group Ltd', '59'],
 ['Li Auto Inc', '71'],
 ['Longfor Group Holdings Ltd', '31'],
 ['Meituan', '431'],
 ['Midea Group Co Ltd', '120'],
 ['Minth Group Ltd', '18'],
 ['MMG Ltd', '24'],
 ['NARI Technology Co Ltd', '61'],
 ['NetEase Cloud Music Inc', '1'],
 ['NetEase Inc', '136'],
 ['New China Life Insurance Co Ltd', '2'],
 ['New Oriental Education & Technology Group Inc', '21'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Ningbo Ronbay New Energy Technology Co Ltd', '17'],
 ['NIO Inc', '1'],
 ['Nongfu Spring Co Ltd', '1'],
 ['Orient Securities Co Ltd/China', '5'],
 ['PDD Holdings Inc', '205'],
 ['PICC Property & Casualty Co Ltd', '80'],
 ['Ping An Insurance Group Co of China Ltd', '315'],
 ['Pop Mart International Group Ltd', '19'],
 ['Postal Savings Bank of China Co Ltd', '6'],
 ['Qifu Technology Inc', '40'],
 ['Sany Heavy Industry Co Ltd', '47'],
 ['SF Holding Co Ltd', '22'],
 ['SG Micro Corp', '18'],
 ['Shandong Himile Mechanical Science & Technology Co Ltd', '7'],
 ['Shandong Hi\xadspeed Co Ltd', '15'],
 ['Shandong Nanshan Aluminum Co Ltd', '14'],
 ['Shandong Weigao Group Medical Polymer Co Ltd', '6'],
 ['Shanghai Chicmax Cosmetic Co Ltd', '2'],
 ['Shanghai Pudong Development Bank Co Ltd', '28'],
 ['Shanghai Rural Commercial Bank Co Ltd', '1'],
 ['Shenzhen Inovance Technology Co Ltd', '29'],
 ['Shenzhen Mindray Bio\xadMedical Electronics Co Ltd', '44'],
 ['Shenzhen New Industries Biomedical Engineering Co Ltd', '25'],
 ['Shenzhou International Group Holdings Ltd', '31'],
 ['Sieyuan Electric Co Ltd', '21'],
 ['Sino Biopharmaceutical Ltd', '10'],
 ['Sinopharm Group Co Ltd', '1'],
 ['Sunac Services Holdings Ltd', '1'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Sungrow Power Supply Co Ltd', '10'],
 ['Sunny Optical Technology Group Co Ltd', '36'],
 ['Sunwoda Electronic Co Ltd', '3'],
 ['Tencent Holdings Ltd', '1.578'],
 ['Tencent Music Entertainment Group', '29'],
 ['Tingyi Cayman Islands Holding Corp', '21'],
 ['Tongcheng Travel Holdings Ltd', '38'],
 ['Tongwei Co Ltd', '25'],
 ['Trip.com Group Ltd', '212'],
 ['Tsingtao Brewery Co Ltd', '2'],
 ['Universal Scientific Industrial Shanghai Co Ltd', '12'],
 ['Vipshop Holdings Ltd', '34'],
 ['Wanhua Chemical Group Co Ltd', '16'],
 ['Want Want China Holdings Ltd', '1'],
 ['Weichai Power Co Ltd', '44'],
 ['Western Mining Co Ltd', '13'],
 ['Will Semiconductor Co Ltd Shanghai', '9'],
 ['Wuliangye Yibin Co Ltd', '43'],
 ['WuXi AppTec Co Ltd', '1'],
 ['Wuxi Biologics Cayman Inc', '9'],
 ['Xiaomi Corp', '151'],
 ['Xinyi Solar Holdings Ltd', '14'],
 ['XPeng Inc', '4'],
 ['Xtep International Holdings Ltd', '5'],
 ['Yadea Group Holdings Ltd', '12'],
 ['Yealink Network Technology Corp Ltd', '4'],
 ['Yifeng Pharmacy Chain Co Ltd', '23'],
 ['Yum China Holdings Inc', '13'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Yunnan Yuntianhua Co Ltd', '29'],
 ['Yutong Bus Co Ltd', '26'],
 ['Zhejiang Longsheng Group Co Ltd', '28'],
 ['Zhejiang Semir Garment Co Ltd', '1'],
 ['Zhejiang Supor Co Ltd', '30'],
 ['Zhongsheng Group Holdings Ltd', '21'],
 ['Zijin Mining Group Co Ltd', '61'],
 ['ZTE Corp', '19'],
 ['ZTO Express Cayman Inc', '38'],
 ['Filippijnen', '454'],
 ['Ayala Land Inc', '59'],
 ['Bank of the Philippine Islands', '26'],
 ['BDO Unibank Inc', '34'],
 ['Bloomberry Resorts Corp', '5'],
 ['DigiPlus Interactive Corp', '1'],
 ['International Container Terminal Services Inc', '18'],
 ['Metropolitan Bank & Trust Co', '8'],
 ['SM Investments Corp', '7'],
 ['SM Prime Holdings Inc', '297'],
 ['Hong Kong', '1.906'],
 ['AIA Group Ltd', '182'],
 ['CLP Holdings Ltd', '35'],
 ['ESR Group Ltd', '309'],
 ['Futu Holdings Ltd', '15'],
 ['Hang Lung Properties Ltd', '88'],
 ['Hang Seng Bank Ltd', '19'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Henderson Land Development Co Ltd', '9'],
 ['HKT Trust & HKT Ltd', '10'],
 ['Hong Kong & China Gas Co Ltd', '18'],
 ['Hong Kong Exchanges & Clearing Ltd', '99'],
 ['Hongkong Land Holdings Ltd', '45'],
 ['HSBC Holdings PLC', '480'],
 ['Link REIT', '305'],
 ['MTR Corp Ltd', '12'],
 ['Sun Hung Kai Properties Ltd', '122'],
 ['Swire Pacific Ltd', '8'],
 ['Swire Properties Ltd', '18'],
 ['Techtronic Industries Co Ltd', '43'],
 ['Wharf Holdings Ltd/The', '3'],
 ['Wharf Real Estate Investment Co Ltd', '88'],
 ['', ''],
 ['India', '4.456'],
 ['ABB India Ltd', '51'],
 ['Alkem Laboratories Ltd', '3'],
 ['Ambuja Cements Ltd', '1'],
 ['Anant Raj Ltd', '4'],
 ['Apollo Hospitals Enterprise Ltd', '37'],
 ['Ashok Leyland Ltd', '1'],
 ['Ashoka Buildcon Ltd', '6'],
 ['Asian Paints Ltd', '2'],
 ['Astral Ltd', '1'],
 ['Aurobindo Pharma Ltd', '4'],
 ['Avenue Supermarts Ltd', '1'],
 ['Axis Bank Ltd', '117'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Bajaj Auto Ltd', '23'],
 ['Bajaj Finance Ltd', '47'],
 ['Bajaj Finserv Ltd', '3'],
 ['Bajaj Holdings & Investment Ltd', '1'],
 ['Bajaj Housing Finance Ltd', '5'],
 ['Balkrishna Industries Ltd', '1'],
 ['Bank of Baroda', '24'],
 ['Bharat Forge Ltd', '8'],
 ['Bharti Airtel Ltd', '152'],
 ['Bharti Hexacom Ltd', '25'],
 ['Birlasoft Ltd', '2'],
 ['Blue Star Ltd', '25'],
 ['Britannia Industries Ltd', '8'],
 ['Can Fin Homes Ltd', '1'],
 ['Canara Bank', '11'],
 ['Ceat Ltd', '5'],
 ['CG Power & Industrial Solutions Ltd', '1'],
 ['Chambal Fertilisers and Chemicals Ltd', '1'],
 ['Cholamandalam Financial Holdings Ltd', '6'],
 ['Cholamandalam Investment and Finance Co Ltd', '59'],
 ['Cipla Ltd/India', '37'],
 ['CMS Info Systems Ltd', '2'],
 ['Coforge Ltd', '10'],
 ['Colgate\xadPalmolive India Ltd', '28'],
 ['Computer Age Management Services Ltd', '16'],
 ['Craftsman Automation Ltd', '12'],
 ['CRISIL Ltd', '3'],
 ['Cummins India Ltd', '7'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Dabur India Ltd', '1'],
 ['Delhivery Ltd', '12'],
 ['Divi’s Laboratories Ltd', '1'],
 ['Dixon Technologies India Ltd', '15'],
 ['DLF Ltd', '83'],
 ['Dr Reddy’s Laboratories Ltd', '6'],
 ['Edelweiss Financial Services Ltd', '1'],
 ['Eicher Motors Ltd', '64'],
 ['EID Parry India Ltd', '1'],
 ['Embassy Office Parks REIT', '22'],
 ['Entero Healthcare Solutions Ltd', '15'],
 ['EPL Ltd', '2'],
 ['Escorts Kubota Ltd', '10'],
 ['Finolex Cables Ltd', '1'],
 ['Force Motors Ltd', '2'],
 ['Fortis Healthcare Ltd', '10'],
 ['GlaxoSmithKline Pharmaceuticals Ltd', '1'],
 ['Glenmark Pharmaceuticals Ltd', '22'],
 ['Global Health Ltd/India', '15'],
 ['GMR Airports Ltd', '30'],
 ['Godawari Power and Ispat Ltd', '7'],
 ['Godrej Consumer Products Ltd', '1'],
 ['Godrej Properties Ltd', '72'],
 ['Grasim Industries Ltd', '1'],
 ['Gujarat Pipavav Port Ltd', '10'],
 ['Gujarat State Petronet Ltd', '1'],
 ['Havells India Ltd', '27'],
 ['HCL Technologies Ltd', '83'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['HDFC Asset Management Co Ltd', '14'],
 ['HDFC Bank Ltd', '416'],
 ['HDFC Life Insurance Co Ltd', '23'],
 ['Hero MotoCorp Ltd', '8'],
 ['Hindalco Industries Ltd', '25'],
 ['Hindustan Aeronautics Ltd', '39'],
 ['Hindustan Unilever Ltd', '25'],
 ['Home First Finance Co India Ltd', '6'],
 ['ICICI Bank Ltd', '301'],
 ['ICICI Lombard General Insurance Co Ltd', '10'],
 ['ICICI Prudential Life Insurance Co Ltd', '17'],
 ['ICICI Securities Ltd', '1'],
 ['IIFL Finance Ltd', '1'],
 ['IndiaMart InterMesh Ltd', '6'],
 ['Indian Energy Exchange Ltd', '4'],
 ['Indian Hotels Co Ltd/The', '63'],
 ['Indraprastha Gas Ltd', '3'],
 ['Indus Towers Ltd', '5'],
 ['Info Edge India Ltd', '27'],
 ['Infosys Ltd', '264'],
 ['InterGlobe Aviation Ltd', '22'],
 ['Inventurus Knowledge Solutions Ltd', '4'],
 ['ITD Cementation India Ltd', '2'],
 ['Jamna Auto Industries Ltd', '2'],
 ['JB Chemicals & Pharmaceuticals Ltd', '4'],
 ['Jio Financial Services Ltd', '17'],
 ['JSW Steel Ltd', '1'],
 ['Jubilant Foodworks Ltd', '1'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Jyothy Labs Ltd', '1'],
 ['Kalyan Jewellers India Ltd', '16'],
 ['Karur Vysya Bank Ltd/The', '7'],
 ['Kfin Technologies Ltd', '7'],
 ['Kirloskar Brothers Ltd', '1'],
 ['Kirloskar Oil Engines Ltd', '2'],
 ['Kotak Mahindra Bank Ltd', '4'],
 ['KPIT Technologies Ltd', '13'],
 ['Lemon Tree Hotels Ltd', '198'],
 ['LIC Housing Finance Ltd', '9'],
 ['Lupin Ltd', '63'],
 ['Macrotech Developers Ltd', '98'],
 ['Mahanagar Gas Ltd', '20'],
 ['Mahindra & Mahindra Ltd', '36'],
 ['MakeMyTrip Ltd', '28'],
 ['Manappuram Finance Ltd', '6'],
 ['Mankind Pharma Ltd', '3'],
 ['Marico Ltd', '1'],
 ['Maruti Suzuki India Ltd', '4'],
 ['Max Healthcare Institute Ltd', '49'],
 ['Motilal Oswal Financial Services Ltd', '8'],
 ['Mphasis Ltd', '10'],
 ['MRF Ltd', '1'],
 ['Multi Commodity Exchange of India Ltd', '9'],
 ['Muthoot Finance Ltd', '3'],
 ['NCC Ltd/India', '2'],
 ['Nestle India Ltd', '1'],
 ['NIIT Learning Systems Ltd', '1'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Nippon Life India Asset Management Ltd', '3'],
 ['NTPC Ltd', '20'],
 ['Nuvama Wealth Management Ltd', '2'],
 ['Oberoi Realty Ltd', '22'],
 ['Oracle Financial Services Software Ltd', '5'],
 ['Page Industries Ltd', '11'],
 ['Paradeep Phosphates Ltd', '4'],
 ['Patanjali Foods Ltd', '17'],
 ['PB Fintech Ltd', '21'],
 ['Persistent Systems Ltd', '29'],
 ['Phoenix Mills Ltd/The', '44'],
 ['PI Industries Ltd', '27'],
 ['Pidilite Industries Ltd', '12'],
 ['Piramal Enterprises Ltd', '2'],
 ['PNB Housing Finance Ltd', '9'],
 ['Polycab India Ltd', '4'],
 ['Power Grid Corp of India Ltd', '122'],
 ['Prestige Estates Projects Ltd', '46'],
 ['PTC India Ltd', '8'],
 ['Punjab National Bank', '5'],
 ['Rainbow Children’s Medicare Ltd', '17'],
 ['Ramco Cements Ltd/The', '1'],
 ['Ramkrishna Forgings Ltd', '2'],
 ['REC Ltd', '49'],
 ['Reliance Infrastructure Ltd', '1'],
 ['Samvardhana Motherson International Ltd', '16'],
 ['SBI Life Insurance Co Ltd', '38'],
 ['Shree Cement Ltd', '1'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Shriram Finance Ltd', '41'],
 ['SignatureGlobal India Ltd', '1'],
 ['Sona Blw Precision Forgings Ltd', '15'],
 ['SRF Ltd', '1'],
 ['State Bank of India', '51'],
 ['Sun Pharmaceutical Industries Ltd', '50'],
 ['Supreme Industries Ltd', '4'],
 ['Suzlon Energy Ltd', '1'],
 ['Tata Consultancy Services Ltd', '179'],
 ['Tata Elxsi Ltd', '1'],
 ['Tata Motors Ltd', '23'],
 ['Tata Power Co Ltd/The', '1'],
 ['Tata Steel Ltd', '2'],
 ['Tech Mahindra Ltd', '6'],
 ['Titagarh Rail System Ltd', '6'],
 ['Titan Co Ltd', '10'],
 ['Torrent Pharmaceuticals Ltd', '49'],
 ['Torrent Power Ltd', '1'],
 ['Transport Corp of India Ltd', '1'],
 ['Trent Ltd', '31'],
 ['Triveni Turbine Ltd', '13'],
 ['Tube Investments of India Ltd', '17'],
 ['TVS Motor Co Ltd', '1'],
 ['UltraTech Cement Ltd', '48'],
 ['Union Bank of India Ltd', '5'],
 ['United Spirits Ltd', '1'],
 ['UPL Ltd', '30'],
 ['Varun Beverages Ltd', '58'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Vodafone Idea Ltd', '10'],
 ['Voltas Ltd', '1'],
 ['Welspun Living Ltd', '1'],
 ['Westlife Foodworld Ltd', '13'],
 ['Wipro Ltd', '9'],
 ['Zensar Technologies Ltd', '4'],
 ['Zomato Ltd', '55'],
 ['Indonesië', '508'],
 ['Amman Mineral Internasional PT', '1'],
 ['Aspirasi Hidup Indonesia Tbk PT', '1'],
 ['Bank Central Asia Tbk PT', '139'],
 ['Bank Mandiri Persero Tbk PT', '48'],
 ['Bank Negara Indonesia Persero Tbk PT', '66'],
 ['Bank Rakyat Indonesia Persero Tbk PT', '133'],
 ['Chandra Asri Pacific Tbk PT', '1'],
 ['Daya Intiguna Yasa Tbk PT', '13'],
 ['GoTo Gojek Tokopedia Tbk PT', '1'],
 ['Indosat Tbk PT', '20'],
 ['Japfa Comfeed Indonesia Tbk PT', '2'],
 ['Semen Indonesia Persero Tbk PT', '8'],
 ['Sumber Alfaria Trijaya Tbk PT', '20'],
 ['Telkom Indonesia Persero Tbk PT', '35'],
 ['Vale Indonesia Tbk PT', '22'],
 ['Israël', '72'],
 ['Azrieli Group Ltd', '5'],
 ['Check Point Software Technologies Ltd', '39'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Nova Ltd', '12'],
 ['Phoenix Financial Ltd', '3'],
 ['Tower Semiconductor Ltd', '12'],
 ['Japan', '7.686'],
 ['Advantest Corp', '71'],
 ['Aeon Co Ltd', '45'],
 ['Air Water Inc', '6'],
 ['Aisin Corp', '16'],
 ['Ajinomoto Co Inc', '47'],
 ['Amada Co Ltd', '7'],
 ['ANA Holdings Inc', '6'],
 ['Asahi Intecc Co Ltd', '9'],
 ['Asahi Kasei Corp', '21'],
 ['Asics Corp', '35'],
 ['Astellas Pharma Inc', '41'],
 ['Azbil Corp', '9'],
 ['Bridgestone Corp', '48'],
 ['Brother Industries Ltd', '10'],
 ['Central Japan Railway Co', '85'],
 ['Chiba Bank Ltd/The', '12'],
 ['Chugai Pharmaceutical Co Ltd', '68'],
 ['Concordia Financial Group Ltd', '14'],
 ['Dai Nippon Printing Co Ltd', '15'],
 ['Daifuku Co Ltd', '44'],
 ['Dai\xadichi Life Holdings Inc', '57'],
 ['Daiichi Sankyo Co Ltd', '120'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Daito Trust Construction Co Ltd', '15'],
 ['Daiwa House Industry Co Ltd', '47'],
 ['Daiwa House REIT Investment Corp', '26'],
 ['Daiwa Securities Group Inc', '20'],
 ['Dentsu Group Inc', '12'],
 ['Disco Corp', '420'],
 ['East Japan Railway Co', '46'],
 ['Ebara Corp', '16'],
 ['Eisai Co Ltd', '18'],
 ['FANUC Corp', '55'],
 ['Fast Retailing Co Ltd', '192'],
 ['Fuji Electric Co Ltd', '18'],
 ['FUJIFILM Holdings Corp', '60'],
 ['Fujikura Ltd', '25'],
 ['Fujitsu Ltd', '74'],
 ['Fukuoka Financial Group Inc', '10'],
 ['GLP J\xadReit', '8'],
 ['Hankyu Hanshin Holdings Inc', '14'],
 ['Haseko Corp', '8'],
 ['Hikari Tsushin Inc', '9'],
 ['Hirose Electric Co Ltd', '8'],
 ['Hoshizaki Corp', '10'],
 ['Hoya Corp', '99'],
 ['Hulic Co Ltd', '38'],
 ['Ibiden Co Ltd', '10'],
 ['IHI Corp', '20'],
 ['Internet Initiative Japan Inc', '6'],
 ['Invincible Investment Corp', '15'],
 ['Regio / Land / Uitgever', 'Waarde'],
 ['Isetan Mitsukoshi Holdings Ltd', '15'],
 ['Isuzu Motors Ltd', '20'],
 ['Japan Airport Terminal Co Ltd', '6'],
 ['Japan Exchange Group Inc', '27'],
 ['Japan Hotel REIT Investment Corp', '12'],
 ['Japan Metropolitan Fund Invest', '9'],
 ['Japan Post Bank Co Ltd', '29'],
 ['Japan Real Estate Investment Corp', '8'],
 ['Kajima Corp', '19'],
 ['Kansai Electric Power Co Inc/The', '22'],
 ['Kansai Paint Co Ltd', '6'],
 ['Kao Corp', '44'],
 ['Kawasaki Kisen Kaisha Ltd', '14'],
 ['KDX Realty Investment Corp', '35'],
 ['Keio Corp', '6'],
 ['Keisei Electric Railway Co Ltd', '10'],
 ['Keyence Corp', '192'],
 ['Kintetsu Group Holdings Co Ltd', '9'],
 ['Kobe Bussan Co Ltd', '8'],

In [5]:

for line in tabs3:
    if line == ['Regio / Land / Uitgever', 'Waarde'] or line == ['', '']:
        tabs3.remove(line)

tabs3

[['Beursgenoteerde', ''],
 ['beleggingen', None],
 ['Afrika', '625'],
 ['Zuid-Afrika', '625'],
 ['Absa Group Ltd', '5'],
 ['Anglo American Platinum Ltd', '1'],
 ['Anglogold Ashanti Plc', '29'],
 ['Aspen Pharmacare Holdings Ltd', '1'],
 ['AVI Ltd', '7'],
 ['Bid Corp Ltd', '8'],
 ['Bidvest Group Ltd', '1'],
 ['Capitec Bank Holdings Ltd', '55'],
 ['Clicks Group Ltd', '25'],
 ['Discovery Ltd', '5'],
 ['FirstRand Ltd', '90'],
 ['Foschini Group Ltd', '1'],
 ['Gold Fields Ltd', '85'],
 ['Hyprop Investments Ltd', '2'],
 ['Impala Platinum Holdings Ltd', '32'],
 ['Investec Ltd', '8'],
 ['Life Healthcare Group Holdings Ltd', '1'],
 ['Momentum Group Ltd', '2'],
 ['Mr Price Group Ltd', '9'],
 ['MTN Group Ltd', '17'],
 ['Naspers Ltd', '117'],
 ['Nedbank Group Ltd', '6'],
 ['NEPI Rockcastle NV', '4'],
 ['Old Mutual Ltd', '5'],
 ['Omnia Holdings Ltd', '1'],
 ['OUTsurance Group Ltd', '16'],
 ['Remgro Ltd', '1'],
 ['Sanlam Ltd', '34'],
 ['Sappi Ltd', '2'],
 ['Shoprite Holdings Ltd', '33'],
 ['Standard Bank Group Ltd', '22'],
 ['Telkom SA SOC Ltd', '1'],
 ['Vodacom Group Ltd', '1'],
 ['Vukile Property Fund Ltd', '1'],
 ['Woolworths Holdings Ltd/South Africa', '1'],
 ['Azië', '34.689'],
 ['China', '8.307'],
 ['3SBio Inc', '6'],
 ['AAC Technologies Holdings Inc', '19'],
 ['Agricultural Bank of China Ltd', '60'],
 ['Akeso Inc', '1'],
 ['Alibaba Group Holding Ltd', '586'],
 ['Anhui Conch Cement Co Ltd', '10'],
 ['Anker Innovations Technology Co Ltd', '10'],
 ['Atour Lifestyle Holdings Ltd', '17'],
 ['Autohome Inc', '25'],
 ['Baidu Inc', '54'],
 ['Bank of China \xad Luxembourg Branch', '41'],
 ['Bank of Communications Co Ltd', '2'],
 ['Bank of Ningbo Co Ltd', '3'],
 ['BeiGene Ltd', '2'],
 ['Beijing Jingneng Clean Energy Co Ltd', '1'],
 ['Beijing Kingsoft Office Software Inc', '1'],
 ['Beijing New Building Materials PLC', '5'],
 ['Beijing Oriental Yuhong Waterproof Technology Co Ltd', '15'],
 ['Bilibili Inc', '13'],
 ['BOC Aviation Ltd', '2'],
 ['BOE Technology Group Co Ltd', '31'],
 ['Bosideng International Holdings Ltd', '31'],
 ['Centre Testing International Group Co Ltd', '26'],
 ['CGN Power Co Ltd', '1'],
 ['China BlueChemical Ltd', '4'],
 ['China CITIC Bank Corp Ltd', '6'],
 ['China Communications Services Corp Ltd', '2'],
 ['China Construction Bank Corp', '242'],
 ['China CSSC Holdings Ltd', '2'],
 ['China Everbright Bank Co Ltd', '6'],
 ['China Feihe Ltd', '6'],
 ['China Galaxy Securities Co Ltd', '8'],
 ['China Hongqiao Group Ltd', '13'],
 ['China International Capital Corp Ltd', '16'],
 ['China International Marine Containers Group Co Ltd', '1'],
 ['China Life Insurance Co Ltd', '9'],
 ['China Medical System Holdings Ltd', '7'],
 ['China Meidong Auto Holdings Ltd', '4'],
 ['China Mengniu Dairy Co Ltd', '17'],
 ['China Merchants Bank Co Ltd', '179'],
 ['China Merchants Shekou Industrial Zone Holdings Co Ltd', '8'],
 ['China Minsheng Banking Corp Ltd', '1'],
 ['China Nonferrous Mining Corp Ltd', '2'],
 ['China Overseas Land & Investment Ltd', '72'],
 ['China Overseas Property Holdings Ltd', '1'],
 ['China Pacific Insurance Group Co Ltd', '51'],
 ['China Railway Group Ltd', '1'],
 ['China Resources Beer Holdings Co Ltd', '52'],
 ['China Resources Beverage Holdings Co Ltd', '10'],
 ['China Resources Gas Group Ltd', '12'],
 ['China Resources Land Ltd', '470'],
 ['China Resources Mixc Lifestyle Services Ltd', '3'],
 ['China South Publishing & Media Group Co Ltd', '8'],
 ['China State Construction International Holdings Ltd', '1'],
 ['China Taiping Insurance Holdings Co Ltd', '13'],
 ['China Tower Corp Ltd', '8'],
 ['China Yangtze Power Co Ltd', '31'],
 ['Chongqing Rural Commercial Bank Co Ltd', '6'],
 ['Chow Tai Fook Jewellery Group Ltd', '4'],
 ['CITIC Securities Co Ltd', '3'],
 ['CMOC Group Ltd', '20'],
 ['Consun Pharmaceutical Group Ltd', '7'],
 ['Contemporary Amperex Technology Co Ltd', '283'],
 ['COSCO SHIPPING Holdings Co Ltd', '1'],
 ['Country Garden Services Holdings Co Ltd', '4'],
 ['CRRC Corp Ltd', '9'],
 ['CSPC Pharmaceutical Group Ltd', '1'],
 ['Dongyue Group Ltd', '3'],
 ['East Money Information Co Ltd', '3'],
 ['ENN Energy Holdings Ltd', '68'],
 ['FinVolution Group', '5'],
 ['Founder Securities Co Ltd', '1'],
 ['Full Truck Alliance Co Ltd', '44'],
 ['Fuyao Glass Industry Group Co Ltd', '22'],
 ['GCL Technology Holdings Ltd', '1'],
 ['GDS Holdings Ltd', '14'],
 ['Geely Automobile Holdings Ltd', '9'],
 ['GF Securities Co Ltd', '8'],
 ['Giant Biogene Holding Co ltd', '3'],
 ['Gree Electric Appliances Inc of Zhuhai', '30'],
 ['Greentown Service Group Co Ltd', '1'],
 ['Guoyuan Securities Co Ltd', '4'],
 ['H World Group Ltd', '23'],
 ['Haidilao International Holding Ltd', '7'],
 ['Haier Smart Home Co Ltd', '128'],
 ['Haitong Securities Co Ltd', '1'],
 ['Hansoh Pharmaceutical Group Co Ltd', '6'],
 ['Hisense Home Appliances Group Co Ltd', '4'],
 ['Hisense Visual Technology Co Ltd', '3'],
 ['HLA Group Corp Ltd', '9'],
 ['Huatai Securities Co Ltd', '17'],
 ['Huaxia Bank Co Ltd', '33'],
 ['Hubei Dinglong Co Ltd', '2'],
 ['Hygon Information Technology Co Ltd', '11'],
 ['Industrial & Commercial Bank Of China, Luxembourg Branch', '156'],
 ['Inner Mongolia Yili Industrial Group Co Ltd', '85'],
 ['Innovent Biologics Inc', '3'],
 ['JD Health International Inc', '1'],
 ['JD Logistics Inc', '2'],
 ['JD.com Inc', '194'],
 ['Jiangsu Hengrui Pharmaceuticals Co Ltd', '2'],
 ['Jinduicheng Molybdenum Co Ltd', '5'],
 ['JNBY Design Ltd', '1'],
 ['Joincare Pharmaceutical Group Industry Co Ltd', '3'],
 ['JOYY Inc', '3'],
 ['Kanzhun Ltd', '3'],
 ['KE Holdings Inc', '54'],
 ['Kingdee International Software Group Co Ltd', '3'],
 ['Kingnet Network Co Ltd', '9'],
 ['Kingsoft Corp Ltd', '32'],
 ['Kuaishou Technology', '100'],
 ['Kweichow Moutai Co Ltd', '31'],
 ['Lenovo Group Ltd', '59'],
 ['Li Auto Inc', '71'],
 ['Longfor Group Holdings Ltd', '31'],
 ['Meituan', '431'],
 ['Midea Group Co Ltd', '120'],
 ['Minth Group Ltd', '18'],
 ['MMG Ltd', '24'],
 ['NARI Technology Co Ltd', '61'],
 ['NetEase Cloud Music Inc', '1'],
 ['NetEase Inc', '136'],
 ['New China Life Insurance Co Ltd', '2'],
 ['New Oriental Education & Technology Group Inc', '21'],
 ['Ningbo Ronbay New Energy Technology Co Ltd', '17'],
 ['NIO Inc', '1'],
 ['Nongfu Spring Co Ltd', '1'],
 ['Orient Securities Co Ltd/China', '5'],
 ['PDD Holdings Inc', '205'],
 ['PICC Property & Casualty Co Ltd', '80'],
 ['Ping An Insurance Group Co of China Ltd', '315'],
 ['Pop Mart International Group Ltd', '19'],
 ['Postal Savings Bank of China Co Ltd', '6'],
 ['Qifu Technology Inc', '40'],
 ['Sany Heavy Industry Co Ltd', '47'],
 ['SF Holding Co Ltd', '22'],
 ['SG Micro Corp', '18'],
 ['Shandong Himile Mechanical Science & Technology Co Ltd', '7'],
 ['Shandong Hi\xadspeed Co Ltd', '15'],
 ['Shandong Nanshan Aluminum Co Ltd', '14'],
 ['Shandong Weigao Group Medical Polymer Co Ltd', '6'],
 ['Shanghai Chicmax Cosmetic Co Ltd', '2'],
 ['Shanghai Pudong Development Bank Co Ltd', '28'],
 ['Shanghai Rural Commercial Bank Co Ltd', '1'],
 ['Shenzhen Inovance Technology Co Ltd', '29'],
 ['Shenzhen Mindray Bio\xadMedical Electronics Co Ltd', '44'],
 ['Shenzhen New Industries Biomedical Engineering Co Ltd', '25'],
 ['Shenzhou International Group Holdings Ltd', '31'],
 ['Sieyuan Electric Co Ltd', '21'],
 ['Sino Biopharmaceutical Ltd', '10'],
 ['Sinopharm Group Co Ltd', '1'],
 ['Sunac Services Holdings Ltd', '1'],
 ['Sungrow Power Supply Co Ltd', '10'],
 ['Sunny Optical Technology Group Co Ltd', '36'],
 ['Sunwoda Electronic Co Ltd', '3'],
 ['Tencent Holdings Ltd', '1.578'],
 ['Tencent Music Entertainment Group', '29'],
 ['Tingyi Cayman Islands Holding Corp', '21'],
 ['Tongcheng Travel Holdings Ltd', '38'],
 ['Tongwei Co Ltd', '25'],
 ['Trip.com Group Ltd', '212'],
 ['Tsingtao Brewery Co Ltd', '2'],
 ['Universal Scientific Industrial Shanghai Co Ltd', '12'],
 ['Vipshop Holdings Ltd', '34'],
 ['Wanhua Chemical Group Co Ltd', '16'],
 ['Want Want China Holdings Ltd', '1'],
 ['Weichai Power Co Ltd', '44'],
 ['Western Mining Co Ltd', '13'],
 ['Will Semiconductor Co Ltd Shanghai', '9'],
 ['Wuliangye Yibin Co Ltd', '43'],
 ['WuXi AppTec Co Ltd', '1'],
 ['Wuxi Biologics Cayman Inc', '9'],
 ['Xiaomi Corp', '151'],
 ['Xinyi Solar Holdings Ltd', '14'],
 ['XPeng Inc', '4'],
 ['Xtep International Holdings Ltd', '5'],
 ['Yadea Group Holdings Ltd', '12'],
 ['Yealink Network Technology Corp Ltd', '4'],
 ['Yifeng Pharmacy Chain Co Ltd', '23'],
 ['Yum China Holdings Inc', '13'],
 ['Yunnan Yuntianhua Co Ltd', '29'],
 ['Yutong Bus Co Ltd', '26'],
 ['Zhejiang Longsheng Group Co Ltd', '28'],
 ['Zhejiang Semir Garment Co Ltd', '1'],
 ['Zhejiang Supor Co Ltd', '30'],
 ['Zhongsheng Group Holdings Ltd', '21'],
 ['Zijin Mining Group Co Ltd', '61'],
 ['ZTE Corp', '19'],
 ['ZTO Express Cayman Inc', '38'],
 ['Filippijnen', '454'],
 ['Ayala Land Inc', '59'],
 ['Bank of the Philippine Islands', '26'],
 ['BDO Unibank Inc', '34'],
 ['Bloomberry Resorts Corp', '5'],
 ['DigiPlus Interactive Corp', '1'],
 ['International Container Terminal Services Inc', '18'],
 ['Metropolitan Bank & Trust Co', '8'],
 ['SM Investments Corp', '7'],
 ['SM Prime Holdings Inc', '297'],
 ['Hong Kong', '1.906'],
 ['AIA Group Ltd', '182'],
 ['CLP Holdings Ltd', '35'],
 ['ESR Group Ltd', '309'],
 ['Futu Holdings Ltd', '15'],
 ['Hang Lung Properties Ltd', '88'],
 ['Hang Seng Bank Ltd', '19'],
 ['Henderson Land Development Co Ltd', '9'],
 ['HKT Trust & HKT Ltd', '10'],
 ['Hong Kong & China Gas Co Ltd', '18'],
 ['Hong Kong Exchanges & Clearing Ltd', '99'],
 ['Hongkong Land Holdings Ltd', '45'],
 ['HSBC Holdings PLC', '480'],
 ['Link REIT', '305'],
 ['MTR Corp Ltd', '12'],
 ['Sun Hung Kai Properties Ltd', '122'],
 ['Swire Pacific Ltd', '8'],
 ['Swire Properties Ltd', '18'],
 ['Techtronic Industries Co Ltd', '43'],
 ['Wharf Holdings Ltd/The', '3'],
 ['Wharf Real Estate Investment Co Ltd', '88'],
 ['India', '4.456'],
 ['ABB India Ltd', '51'],
 ['Alkem Laboratories Ltd', '3'],
 ['Ambuja Cements Ltd', '1'],
 ['Anant Raj Ltd', '4'],
 ['Apollo Hospitals Enterprise Ltd', '37'],
 ['Ashok Leyland Ltd', '1'],
 ['Ashoka Buildcon Ltd', '6'],
 ['Asian Paints Ltd', '2'],
 ['Astral Ltd', '1'],
 ['Aurobindo Pharma Ltd', '4'],
 ['Avenue Supermarts Ltd', '1'],
 ['Axis Bank Ltd', '117'],
 ['Bajaj Auto Ltd', '23'],
 ['Bajaj Finance Ltd', '47'],
 ['Bajaj Finserv Ltd', '3'],
 ['Bajaj Holdings & Investment Ltd', '1'],
 ['Bajaj Housing Finance Ltd', '5'],
 ['Balkrishna Industries Ltd', '1'],
 ['Bank of Baroda', '24'],
 ['Bharat Forge Ltd', '8'],
 ['Bharti Airtel Ltd', '152'],
 ['Bharti Hexacom Ltd', '25'],
 ['Birlasoft Ltd', '2'],
 ['Blue Star Ltd', '25'],
 ['Britannia Industries Ltd', '8'],
 ['Can Fin Homes Ltd', '1'],
 ['Canara Bank', '11'],
 ['Ceat Ltd', '5'],
 ['CG Power & Industrial Solutions Ltd', '1'],
 ['Chambal Fertilisers and Chemicals Ltd', '1'],
 ['Cholamandalam Financial Holdings Ltd', '6'],
 ['Cholamandalam Investment and Finance Co Ltd', '59'],
 ['Cipla Ltd/India', '37'],
 ['CMS Info Systems Ltd', '2'],
 ['Coforge Ltd', '10'],
 ['Colgate\xadPalmolive India Ltd', '28'],
 ['Computer Age Management Services Ltd', '16'],
 ['Craftsman Automation Ltd', '12'],
 ['CRISIL Ltd', '3'],
 ['Cummins India Ltd', '7'],
 ['Dabur India Ltd', '1'],
 ['Delhivery Ltd', '12'],
 ['Divi’s Laboratories Ltd', '1'],
 ['Dixon Technologies India Ltd', '15'],
 ['DLF Ltd', '83'],
 ['Dr Reddy’s Laboratories Ltd', '6'],
 ['Edelweiss Financial Services Ltd', '1'],
 ['Eicher Motors Ltd', '64'],
 ['EID Parry India Ltd', '1'],
 ['Embassy Office Parks REIT', '22'],
 ['Entero Healthcare Solutions Ltd', '15'],
 ['EPL Ltd', '2'],
 ['Escorts Kubota Ltd', '10'],
 ['Finolex Cables Ltd', '1'],
 ['Force Motors Ltd', '2'],
 ['Fortis Healthcare Ltd', '10'],
 ['GlaxoSmithKline Pharmaceuticals Ltd', '1'],
 ['Glenmark Pharmaceuticals Ltd', '22'],
 ['Global Health Ltd/India', '15'],
 ['GMR Airports Ltd', '30'],
 ['Godawari Power and Ispat Ltd', '7'],
 ['Godrej Consumer Products Ltd', '1'],
 ['Godrej Properties Ltd', '72'],
 ['Grasim Industries Ltd', '1'],
 ['Gujarat Pipavav Port Ltd', '10'],
 ['Gujarat State Petronet Ltd', '1'],
 ['Havells India Ltd', '27'],
 ['HCL Technologies Ltd', '83'],
 ['HDFC Asset Management Co Ltd', '14'],
 ['HDFC Bank Ltd', '416'],
 ['HDFC Life Insurance Co Ltd', '23'],
 ['Hero MotoCorp Ltd', '8'],
 ['Hindalco Industries Ltd', '25'],
 ['Hindustan Aeronautics Ltd', '39'],
 ['Hindustan Unilever Ltd', '25'],
 ['Home First Finance Co India Ltd', '6'],
 ['ICICI Bank Ltd', '301'],
 ['ICICI Lombard General Insurance Co Ltd', '10'],
 ['ICICI Prudential Life Insurance Co Ltd', '17'],
 ['ICICI Securities Ltd', '1'],
 ['IIFL Finance Ltd', '1'],
 ['IndiaMart InterMesh Ltd', '6'],
 ['Indian Energy Exchange Ltd', '4'],
 ['Indian Hotels Co Ltd/The', '63'],
 ['Indraprastha Gas Ltd', '3'],
 ['Indus Towers Ltd', '5'],
 ['Info Edge India Ltd', '27'],
 ['Infosys Ltd', '264'],
 ['InterGlobe Aviation Ltd', '22'],
 ['Inventurus Knowledge Solutions Ltd', '4'],
 ['ITD Cementation India Ltd', '2'],
 ['Jamna Auto Industries Ltd', '2'],
 ['JB Chemicals & Pharmaceuticals Ltd', '4'],
 ['Jio Financial Services Ltd', '17'],
 ['JSW Steel Ltd', '1'],
 ['Jubilant Foodworks Ltd', '1'],
 ['Jyothy Labs Ltd', '1'],
 ['Kalyan Jewellers India Ltd', '16'],
 ['Karur Vysya Bank Ltd/The', '7'],
 ['Kfin Technologies Ltd', '7'],
 ['Kirloskar Brothers Ltd', '1'],
 ['Kirloskar Oil Engines Ltd', '2'],
 ['Kotak Mahindra Bank Ltd', '4'],
 ['KPIT Technologies Ltd', '13'],
 ['Lemon Tree Hotels Ltd', '198'],
 ['LIC Housing Finance Ltd', '9'],
 ['Lupin Ltd', '63'],
 ['Macrotech Developers Ltd', '98'],
 ['Mahanagar Gas Ltd', '20'],
 ['Mahindra & Mahindra Ltd', '36'],
 ['MakeMyTrip Ltd', '28'],
 ['Manappuram Finance Ltd', '6'],
 ['Mankind Pharma Ltd', '3'],
 ['Marico Ltd', '1'],
 ['Maruti Suzuki India Ltd', '4'],
 ['Max Healthcare Institute Ltd', '49'],
 ['Motilal Oswal Financial Services Ltd', '8'],
 ['Mphasis Ltd', '10'],
 ['MRF Ltd', '1'],
 ['Multi Commodity Exchange of India Ltd', '9'],
 ['Muthoot Finance Ltd', '3'],
 ['NCC Ltd/India', '2'],
 ['Nestle India Ltd', '1'],
 ['NIIT Learning Systems Ltd', '1'],
 ['Nippon Life India Asset Management Ltd', '3'],
 ['NTPC Ltd', '20'],
 ['Nuvama Wealth Management Ltd', '2'],
 ['Oberoi Realty Ltd', '22'],
 ['Oracle Financial Services Software Ltd', '5'],
 ['Page Industries Ltd', '11'],
 ['Paradeep Phosphates Ltd', '4'],
 ['Patanjali Foods Ltd', '17'],
 ['PB Fintech Ltd', '21'],
 ['Persistent Systems Ltd', '29'],
 ['Phoenix Mills Ltd/The', '44'],
 ['PI Industries Ltd', '27'],
 ['Pidilite Industries Ltd', '12'],
 ['Piramal Enterprises Ltd', '2'],
 ['PNB Housing Finance Ltd', '9'],
 ['Polycab India Ltd', '4'],
 ['Power Grid Corp of India Ltd', '122'],
 ['Prestige Estates Projects Ltd', '46'],
 ['PTC India Ltd', '8'],
 ['Punjab National Bank', '5'],
 ['Rainbow Children’s Medicare Ltd', '17'],
 ['Ramco Cements Ltd/The', '1'],
 ['Ramkrishna Forgings Ltd', '2'],
 ['REC Ltd', '49'],
 ['Reliance Infrastructure Ltd', '1'],
 ['Samvardhana Motherson International Ltd', '16'],
 ['SBI Life Insurance Co Ltd', '38'],
 ['Shree Cement Ltd', '1'],
 ['Shriram Finance Ltd', '41'],
 ['SignatureGlobal India Ltd', '1'],
 ['Sona Blw Precision Forgings Ltd', '15'],
 ['SRF Ltd', '1'],
 ['State Bank of India', '51'],
 ['Sun Pharmaceutical Industries Ltd', '50'],
 ['Supreme Industries Ltd', '4'],
 ['Suzlon Energy Ltd', '1'],
 ['Tata Consultancy Services Ltd', '179'],
 ['Tata Elxsi Ltd', '1'],
 ['Tata Motors Ltd', '23'],
 ['Tata Power Co Ltd/The', '1'],
 ['Tata Steel Ltd', '2'],
 ['Tech Mahindra Ltd', '6'],
 ['Titagarh Rail System Ltd', '6'],
 ['Titan Co Ltd', '10'],
 ['Torrent Pharmaceuticals Ltd', '49'],
 ['Torrent Power Ltd', '1'],
 ['Transport Corp of India Ltd', '1'],
 ['Trent Ltd', '31'],
 ['Triveni Turbine Ltd', '13'],
 ['Tube Investments of India Ltd', '17'],
 ['TVS Motor Co Ltd', '1'],
 ['UltraTech Cement Ltd', '48'],
 ['Union Bank of India Ltd', '5'],
 ['United Spirits Ltd', '1'],
 ['UPL Ltd', '30'],
 ['Varun Beverages Ltd', '58'],
 ['Vodafone Idea Ltd', '10'],
 ['Voltas Ltd', '1'],
 ['Welspun Living Ltd', '1'],
 ['Westlife Foodworld Ltd', '13'],
 ['Wipro Ltd', '9'],
 ['Zensar Technologies Ltd', '4'],
 ['Zomato Ltd', '55'],
 ['Indonesië', '508'],
 ['Amman Mineral Internasional PT', '1'],
 ['Aspirasi Hidup Indonesia Tbk PT', '1'],
 ['Bank Central Asia Tbk PT', '139'],
 ['Bank Mandiri Persero Tbk PT', '48'],
 ['Bank Negara Indonesia Persero Tbk PT', '66'],
 ['Bank Rakyat Indonesia Persero Tbk PT', '133'],
 ['Chandra Asri Pacific Tbk PT', '1'],
 ['Daya Intiguna Yasa Tbk PT', '13'],
 ['GoTo Gojek Tokopedia Tbk PT', '1'],
 ['Indosat Tbk PT', '20'],
 ['Japfa Comfeed Indonesia Tbk PT', '2'],
 ['Semen Indonesia Persero Tbk PT', '8'],
 ['Sumber Alfaria Trijaya Tbk PT', '20'],
 ['Telkom Indonesia Persero Tbk PT', '35'],
 ['Vale Indonesia Tbk PT', '22'],
 ['Israël', '72'],
 ['Azrieli Group Ltd', '5'],
 ['Check Point Software Technologies Ltd', '39'],
 ['Nova Ltd', '12'],
 ['Phoenix Financial Ltd', '3'],
 ['Tower Semiconductor Ltd', '12'],
 ['Japan', '7.686'],
 ['Advantest Corp', '71'],
 ['Aeon Co Ltd', '45'],
 ['Air Water Inc', '6'],
 ['Aisin Corp', '16'],
 ['Ajinomoto Co Inc', '47'],
 ['Amada Co Ltd', '7'],
 ['ANA Holdings Inc', '6'],
 ['Asahi Intecc Co Ltd', '9'],
 ['Asahi Kasei Corp', '21'],
 ['Asics Corp', '35'],
 ['Astellas Pharma Inc', '41'],
 ['Azbil Corp', '9'],
 ['Bridgestone Corp', '48'],
 ['Brother Industries Ltd', '10'],
 ['Central Japan Railway Co', '85'],
 ['Chiba Bank Ltd/The', '12'],
 ['Chugai Pharmaceutical Co Ltd', '68'],
 ['Concordia Financial Group Ltd', '14'],
 ['Dai Nippon Printing Co Ltd', '15'],
 ['Daifuku Co Ltd', '44'],
 ['Dai\xadichi Life Holdings Inc', '57'],
 ['Daiichi Sankyo Co Ltd', '120'],
 ['Daito Trust Construction Co Ltd', '15'],
 ['Daiwa House Industry Co Ltd', '47'],
 ['Daiwa House REIT Investment Corp', '26'],
 ['Daiwa Securities Group Inc', '20'],
 ['Dentsu Group Inc', '12'],
 ['Disco Corp', '420'],
 ['East Japan Railway Co', '46'],
 ['Ebara Corp', '16'],
 ['Eisai Co Ltd', '18'],
 ['FANUC Corp', '55'],
 ['Fast Retailing Co Ltd', '192'],
 ['Fuji Electric Co Ltd', '18'],
 ['FUJIFILM Holdings Corp', '60'],
 ['Fujikura Ltd', '25'],
 ['Fujitsu Ltd', '74'],
 ['Fukuoka Financial Group Inc', '10'],
 ['GLP J\xadReit', '8'],
 ['Hankyu Hanshin Holdings Inc', '14'],
 ['Haseko Corp', '8'],
 ['Hikari Tsushin Inc', '9'],
 ['Hirose Electric Co Ltd', '8'],
 ['Hoshizaki Corp', '10'],
 ['Hoya Corp', '99'],
 ['Hulic Co Ltd', '38'],
 ['Ibiden Co Ltd', '10'],
 ['IHI Corp', '20'],
 ['Internet Initiative Japan Inc', '6'],
 ['Invincible Investment Corp', '15'],
 ['Isetan Mitsukoshi Holdings Ltd', '15'],
 ['Isuzu Motors Ltd', '20'],
 ['Japan Airport Terminal Co Ltd', '6'],
 ['Japan Exchange Group Inc', '27'],
 ['Japan Hotel REIT Investment Corp', '12'],
 ['Japan Metropolitan Fund Invest', '9'],
 ['Japan Post Bank Co Ltd', '29'],
 ['Japan Real Estate Investment Corp', '8'],
 ['Kajima Corp', '19'],
 ['Kansai Electric Power Co Inc/The', '22'],
 ['Kansai Paint Co Ltd', '6'],
 ['Kao Corp', '44'],
 ['Kawasaki Kisen Kaisha Ltd', '14'],
 ['KDX Realty Investment Corp', '35'],
 ['Keio Corp', '6'],
 ['Keisei Electric Railway Co Ltd', '10'],
 ['Keyence Corp', '192'],
 ['Kintetsu Group Holdings Co Ltd', '9'],
 ['Kobe Bussan Co Ltd', '8'],
 ['Koito Manufacturing Co Ltd', '7'],
 ['Komatsu Ltd', '61'],
 ['Konami Group Corp', '21'],
 ['Kubota Corp', '32'],
 ['Kuraray Co Ltd', '10'],
 ['Kurita Water Industries Ltd', '9'],
 ['Kyoto Financial Group Inc', '9'],
 ['Kyowa Kirin Co Ltd', '8'],
 ['Kyushu Railway Co', '8'],
 ['Lasertec Corp', '20'],
 ['Lixil Corp', '7'],
 ['LY Corp', '16'],
 ['M3 Inc', '9'],
 ['Makita Corp', '19'],
 ['Marui Group Co Ltd', '7'],
 ['MatsukiyoCocokara & Co', '13'],
 ['Mazda Motor Corp', '9'],
 ['McDonald’s Holdings Co Japan Ltd', '7'],
 ['Mebuki Financial Group Inc', '9'],
 ['Medipal Holdings Corp', '7'],
 ['MINEBEA MITSUMI Inc', '14'],
 ['MISUMI Group Inc', '10'],
 ['Mitsubishi Chemical Group Corp', '16'],
 ['Mitsubishi Electric Corp', '82'],
 ['Mitsubishi Estate Co Ltd', '67'],
 ['Mitsubishi HC Capital Inc', '16'],

In [7]:
table = pd.DataFrame(tabs3[2:], columns=['Publisher', 'Value in Millions of Euros'])
table

                          Publisher Value in Millions of Euros
0                            Afrika                        625
1                       Zuid-Afrika                        625
2                    Absa Group Ltd                          5
3       Anglo American Platinum Ltd                          1
4             Anglogold Ashanti Plc                         29
...                             ...                        ...
2082                           Peru                        226
2083  Cia de Minas Buenaventura SAA                          3
2084                  Credicorp Ltd                        139
2085           Southern Copper Corp                         85
2086                         Totaal                    181.555

[2087 rows x 2 columns]

In [9]:
table2 = table.drop([0, 1, 37, 38, 228, 238, 259, 447, 463, 469, 678, 680, 688, 711, 718, 747, 769, 895, 921, 936, 944, 1015, 1016, 1033, 1045, 1084, 1097, 1140, 1147, 1151, 1155, 1174, 1197, 1212, 1218, 1234, 1238, 1239, 1256, 1259, 1276, 1345, 1391, 1417, 1418, 1472, 1500, 1944, 1945, 2003, 2011, 2012, 2016, 2068, 2080, 2082])

In [10]:
table2

                          Publisher Value in Millions of Euros
2                    Absa Group Ltd                          5
3       Anglo American Platinum Ltd                          1
4             Anglogold Ashanti Plc                         29
5     Aspen Pharmacare Holdings Ltd                          1
6                           AVI Ltd                          7
...                             ...                        ...
2081                 Bancolombia SA                          7
2083  Cia de Minas Buenaventura SAA                          3
2084                  Credicorp Ltd                        139
2085           Southern Copper Corp                         85
2086                         Totaal                    181.555

[2031 rows x 2 columns]

In [12]:
table2.to_csv("stichting_pensioenfonds_ABP.csv")