In [1]:
import pdfplumber
import re
import pandas as pd

In [2]:
pdf = pdfplumber.open("bpfbouw.pdf")

In [3]:
tabs = []

for page in pdf.pages:
    text = page.extract_text()
    if text:
            pattern = re.compile(r'^(.+?)\s+([\d.]+,\d+)$', re.MULTILINE)
            matches = pattern.findall(text)
            tabs.append(matches)

#tabs

In [4]:
tabs2=sum(tabs, [])

In [5]:
table = pd.DataFrame(tabs2, columns=["share", "amount x €1000"])
table.head()

                                         share amount x €1000
0                                       Afrika       87.955,7
1                                       Egypte          487,6
2  Commercial International Bank - Egypt (CIB)          487,6
3                                  Zuid-Afrika       87.468,1
4                  Anglo American Platinum Ltd          168,6

In [6]:
table2 = table.drop([0, 1, 3, 38, 39, 239, 257, 284, 458, 475, 719, 721, 727, 753, 757, 775, 799, 883, 924, 936, 938, 1019, 1020, 1035, 1052, 1105, 1120, 1175, 1184, 1189, 1193, 1221, 1255, 1275, 1284, 1302, 1306, 1336, 1360, 1364, 1382, 1467, 1506, 1545, 1546, 1634, 1662, 2385, 2386, 2443, 2446, 2447, 2497, 2510, 2513])

In [7]:
table2.head()

                                         share amount x €1000
2  Commercial International Bank - Egypt (CIB)          487,6
4                  Anglo American Platinum Ltd          168,6
5                        Anglogold Ashanti Plc        4.441,8
6                                 Bid Corp Ltd          624,4
7                    Capitec Bank Holdings Ltd        4.625,4

In [8]:
table2.to_csv("bpfbouw.csv")