In [5]:
import pdfplumber
import pandas as pd

In [6]:
pdf = pdfplumber.open("danicapension.pdf")

In [7]:
tabs = []



for page in pdf.pages:
    tabs.append(page.extract_tables(table_settings={"vertical_strategy": "text", "horizontal_strategy": "text", "text_keep_blank_chars": False}))


#tabs

In [8]:
biglist=sum(tabs, [])

In [9]:
biggerlist=sum(biglist, [])

In [10]:
biggestlist=[]

for i in range(len(biggerlist)):
    if biggerlist[i]!= ['', '', '', '']:
        if biggerlist[i]!=['', '', '', '', '']:
            biggestlist.append(biggerlist[i])

#biggestlist

In [11]:
test = biggestlist[300][0:-2]

test2 = " ".join(test)
#test2

In [12]:
for i in range(len(biggestlist)):
    combo = []
    combo = biggestlist[i][0:-2]
    del biggestlist[i][0:-2]
    combo = "".join(combo)
    biggestlist[i].append(combo)

#biggestlist

In [13]:
table = pd.DataFrame(biggestlist[4:-5], columns=['marketvalue', 'share%', 'listedshares'])
table.head()

  marketvalue share%       listedshares
0       7.407   3,9%         Apple Inc.
1       6.941   3,7%    Microsoft Corp.
2       6.773   3,6%  Nvidia Corp. (US)
3       5.526   2,9%         Amazon.com
4       4.311   2,3%     Novo Nordisk B

In [14]:
reorder = ['listedshares', 'marketvalue', 'share%']
table2 = table[reorder]
table2.head()

        listedshares marketvalue share%
0         Apple Inc.       7.407   3,9%
1    Microsoft Corp.       6.941   3,7%
2  Nvidia Corp. (US)       6.773   3,6%
3         Amazon.com       5.526   2,9%
4     Novo Nordisk B       4.311   2,3%

In [15]:
table2.to_csv('danicapension.csv')