In [5]:
import pandas as pd
import pdfplumber

In [6]:
pdf = pdfplumber.open("stichting_pensioenfonds_ABP.pdf")

In [7]:
tabs = []

for page in pdf.pages:
    tabs.append(
        page.extract_tables(
            table_settings={
                "vertical_strategy": "lines",
                "join_y_tolerance": 50,
            }
        )
    )

# tabs

In [8]:
tabs2 = sum(tabs, [])
tabs3 = sum(tabs2, [])
# tabs3

In [9]:
for line in tabs3:
    if line == ["Regio / Land / Uitgever", "Waarde"] or line == ["", ""]:
        tabs3.remove(line)

# tabs3

In [10]:
table = pd.DataFrame(
    tabs3[2:], columns=["Publisher", "Value in Millions of Euros"]
)
table.head()

                     Publisher Value in Millions of Euros
0                       Afrika                        625
1                  Zuid-Afrika                        625
2               Absa Group Ltd                          5
3  Anglo American Platinum Ltd                          1
4        Anglogold Ashanti Plc                         29

In [11]:
table2 = table.drop(
    [
        0,
        1,
        37,
        38,
        228,
        238,
        259,
        447,
        463,
        469,
        678,
        680,
        688,
        711,
        718,
        747,
        769,
        895,
        921,
        936,
        944,
        1015,
        1016,
        1033,
        1045,
        1084,
        1097,
        1140,
        1147,
        1151,
        1155,
        1174,
        1197,
        1212,
        1218,
        1234,
        1238,
        1239,
        1256,
        1259,
        1276,
        1345,
        1391,
        1417,
        1418,
        1472,
        1500,
        1944,
        1945,
        2003,
        2011,
        2012,
        2016,
        2068,
        2080,
        2082,
    ]
)

In [12]:
table2.head()

                       Publisher Value in Millions of Euros
2                 Absa Group Ltd                          5
3    Anglo American Platinum Ltd                          1
4          Anglogold Ashanti Plc                         29
5  Aspen Pharmacare Holdings Ltd                          1
6                        AVI Ltd                          7

In [13]:
table2.to_csv("stichting_pensioenfonds_ABP.csv")