In [317]:
import pandas as pd
import pdfplumber

In [318]:
pdf = pdfplumber.open("vervoer.pdf")

In [319]:
tabs = []

for page in pdf.pages:
    text = page.extract_text(layout=True, x_density=4)
    tabs.append(text.strip() + "\n")

# tabs

CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox
CropBox missing from /Page, defaulting to MediaBox

In [320]:
tabs2 = " ".join(tabs)

# tabs2

In [321]:
tabs3 = tabs2.splitlines()
tabs4 = []
for tab in tabs3:
    tab = tab.strip()
    tabs4.append(tab.split("  "))

tabs4 = sum(tabs4, [])

In [322]:
for tab in tabs4:
    if tab == "" or tab == " " or tab == "  " or tab == "   ":
        tabs4.remove(tab)

for tab in tabs4:
    if tab == "Overzicht beleggingen per 31-12-2024":
        tabs4.remove(tab)

for tab in tabs4:
    if "Pagina" in tab:
        tabs4.remove(tab)

for tab in tabs4:
    if "Marktwaarde" in tab:
        tabs4.remove(tab)

tabs4 = tabs4[13:]

In [323]:
tabs5 = []
for tab in tabs4:
    if tab != "":
        tabs5.append(tab)

# tabs5

In [324]:
del tabs5[19:23]

In [325]:
chunks = [tabs5[i : i + 4] for i in range(0, len(tabs5), 4)]
chunks = chunks[:1494]

# print(chunks)

In [328]:
table = pd.DataFrame(chunks, columns=["1", "2", "3", "4"])
table.head()

,1,2,3,4
0,Apple Inc,353.689,Federal Republic of Germany,4.454.269
1,Microsoft Corp,305.495,Staat der Nederlanden,4.382.489
2,NVIDIA CORP,274.670,South Africa Government Bond,127.107
3,Taiwan Semiconductor Manufacturing,241.295,Czech Republic Government Bond,115.647
4,Amazoncom Inc,224.131,Malaysia Government Bond,Issuer naam

In [329]:
shares = table[["1", "2"]].copy()
shares.columns = ["issuer name", "marketvalue x €1000"]
shares.head()

                          issuer name marketvalue x €1000
0                           Apple Inc             353.689
1                      Microsoft Corp             305.495
2                         NVIDIA CORP             274.670
3  Taiwan Semiconductor Manufacturing             241.295
4                       Amazoncom Inc             224.131

In [330]:
fixed_income_securities = table[["3", "4"]].copy()
fixed_income_securities.columns = ["issuer name", "marketvalue x €1000"]
fixed_income_securities.head()

                       issuer name marketvalue x €1000
0      Federal Republic of Germany           4.454.269
1            Staat der Nederlanden           4.382.489
2     South Africa Government Bond             127.107
3   Czech Republic Government Bond             115.647
4         Malaysia Government Bond         Issuer naam

In [331]:
shares.to_csv("vervoershares.csv")
fixed_income_securities.to_csv("vervoerfixedincome.csv")